Repository Despair-Games/poketernity, pull requests merged in 2025-01, with the labels that each got.

#168 [Dev] Test and eslint github workflows are back
  .github/CODEOWNERS
  .github/workflows/deploy-beta.yml
  .github/workflows/deploy.yml
  .github/workflows/eslint.yml
  .github/workflows/github-pages.yml
  .github/workflows/test-shard-template.yml
  README.md
Labels: GitHub

#166 [Move][P2] Fix Secret Power interaction with multi-hit enhancers
  src/data/move-attrs/secret-power-attr.ts
  test/abilities/parental_bond.test.ts
Labels: Move, P2 Bug

#136 [P3] Update sticky web application message
  src/data/arena-tag.ts
Labels: Move, P3 Bug

#163 [Sprite] Replaced vivillon poke-ball pattern T3
  public/images/pokemon/variant/666-poke-ball.json
  public/images/pokemon/variant/666-poke-ball_3.json
  public/images/pokemon/variant/666-poke-ball_3.png
  public/images/pokemon/variant/_masterlist.json
  public/images/pokemon/variant/back/666-poke-ball.json
Labels: Sprite/Animation

#165 [Refactor] Damage Reduction abilities return their multiplier value instead of processing damage after calculation.
  src/data/ab-attrs/allied-field-damage-reduction-ab-attr.ts
  src/data/ab-attrs/damage-boost-ab-attr.ts
  src/data/ab-attrs/form-block-damage-ab-attr.ts
  src/data/ab-attrs/received-move-damage-multiplier-ab-attr.ts
  src/field/pokemon.ts
Labels: Refactor

#170 [Move][Refactor] Fixed Defog interactions + Arena Tag attribute cleanup
  src/data/all-moves.ts
  src/data/move-attrs/add-arena-tag-attr.ts
  src/data/move-attrs/add-pledge-effect-attr.ts
  src/data/move-attrs/remove-arena-tags-attr.ts
  src/data/move-attrs/remove-arena-trap-attr.ts
  src/data/move-attrs/remove-screens-attr.ts
  src/enums/arena-tag-relative-side.ts
  test/moves/brick_break.test.ts
  test/moves/defog.test.ts
  test/moves/rapid_spin.test.ts
Labels: Move, Refactor

#169 [Move] Add `getHealRatio` helper function to `HealAttr`
  src/data/move-attrs/boost-heal-attr.ts
  src/data/move-attrs/heal-attr.ts
  src/data/move-attrs/swallow-heal-attr.ts
  src/data/move-attrs/weather-heal-attr.ts
  test/moves/floral_healing.test.ts
  test/moves/synthesis.test.ts
Labels: Move

#145 [Ability][Checkup] Added documentation and tests for Anger Point
  src/data/ab-attrs/post-defend-crit-stat-stage-change-ab-attr.ts
  src/data/abilities.ts
  src/enums/stat.ts
  src/phases/stat-stage-change-phase.ts
  test/abilities/anger_point.test.ts
Labels: Ability, P2 Bug, Checkup

#139 [Ability][Checkup][Bug] Fixing up Fluffy's interactions with Long Reach + adding tests/utilities for Fluffy
  src/data/abilities.ts
  test/abilities/fluffy.test.ts
Labels: Ability, P2 Bug, Checkup

#158 [Tests] Reuse global scene between tests
  src/battle-scene.ts
  src/ui/starter-select-ui-handler.ts
  test/abilities/unseen_fist.test.ts
  test/achievements/achievement.test.ts
  test/phases/phases.test.ts
  test/testUtils/gameManager.ts
  test/testUtils/mocks/mocksContainer/mockRectangle.ts
Labels: Tests

#105 [Refactor] Move trainers into individual files
  src/battle-scene.ts
  src/battle.ts
  src/data/balance/trainer-configs/all-trainer-configs.ts
  src/data/balance/trainer-configs/champion-trainer-configs.ts
  src/data/balance/trainer-configs/elite-four-trainer-configs.ts
  src/data/balance/trainer-configs/evil-boss-trainer-configs.ts
  src/data/balance/trainer-configs/evil-team-trainer-configs.ts
  src/data/balance/trainer-configs/generic-trainer-configs.ts
  src/data/balance/trainer-configs/gym-leader-configs.ts
  src/data/balance/trainer-configs/me-trainer-configs.ts
  src/data/balance/trainer-configs/rival-trainer-configs.ts
  src/data/dialogue.ts
  src/data/mystery-encounters/encounters/a-trainers-test-encounter.ts
  src/data/mystery-encounters/encounters/absolute-avarice-encounter.ts
  src/data/mystery-encounters/encounters/berries-abound-encounter.ts
  src/data/mystery-encounters/encounters/bug-type-superfan-encounter.ts
  src/data/mystery-encounters/encounters/clowning-around-encounter.ts
  src/data/mystery-encounters/encounters/dancing-lessons-encounter.ts
  src/data/mystery-encounters/encounters/fight-or-flight-encounter.ts
  src/data/mystery-encounters/encounters/fun-and-games-encounter.ts
  src/data/mystery-encounters/encounters/global-trade-system-encounter.ts
  src/data/mystery-encounters/encounters/mysterious-challengers-encounter.ts
  src/data/mystery-encounters/encounters/safari-zone-encounter.ts
  src/data/mystery-encounters/encounters/teleporting-hijinks-encounter.ts
  src/data/mystery-encounters/encounters/the-expert-pokemon-breeder-encounter.ts
  src/data/mystery-encounters/encounters/uncommon-breed-encounter.ts
  src/data/mystery-encounters/encounters/weird-dream-encounter.ts
  src/data/mystery-encounters/utils/encounter-phase-utils.ts
  src/data/trainer-config.ts
  src/enums/trainer-pool-tier.ts
  src/enums/trainer-slot.ts
  src/field/pokemon.ts
  src/field/trainer.ts
  src/phases/abstract-battle-phase.ts
  src/phases/encounter-phase.ts
  src/phases/game-over-phase.ts
  src/phases/mystery-encounter-phases/battle-phase.ts
  src/phases/summon-phase.ts
  src/phases/switch-summon-phase.ts
  src/phases/trainer-victory-phase.ts
  src/system/game-data.ts
  src/system/pokemon-data.ts
  src/system/voucher.ts
  test/moves/effectiveness.test.ts
Labels: Refactor

#182 [P3] Fix protection bypass moves activating conditional protection messages
  src/data/arena-tag.ts
  src/data/battler-tags.ts
  src/phases/move-effect-phase.ts
Labels: Move, P3 Bug

#180 [Bug] Fix Happy Hour's effect disappearing immediately after usage
  src/data/all-moves.ts
  src/data/arena-tag.ts
  src/data/move-attrs/add-arena-tag-attr.ts
  test/moves/happy_hour.test.ts
Labels: Move, P2 Bug

#198 [Tests] Fix Trainer's Test unit test to check trainer type instead of name
  test/mystery-encounter/encounters/a-trainers-test-encounter.test.ts
Labels: Tests

#147 [Refactor][Bug] Clean up Pokemon turn counts, again
  src/field/pokemon.ts
  src/phases/battle-end-phase.ts
  src/phases/switch-summon-phase.ts
  src/phases/turn-end-phase.ts
  src/phases/turn-init-phase.ts
  test/moves/fake_out.test.ts
Labels: Move, P2 Bug

#202 [UI][P3] Temporarily use luxury ball to show epic tier items in shop
  src/data/pokeball.ts
  src/enums/pokeball.ts
  src/phases/command-phase.ts
  src/ui/ball-ui-handler.ts
  src/ui/modifier-select-ui-handler.ts
Labels: P3 Bug, UI/UX

#217 [Dev] Make workflows run on ubuntu-22 instead of ubuntu-latest
  .github/workflows/deploy-beta.yml
  .github/workflows/deploy.yml
  .github/workflows/eslint.yml
  .github/workflows/github-pages.yml
  .github/workflows/test-shard-template.yml
Labels: GitHub

#206 [Bug] Fix field moves not working when a target is fainted
  src/phases/move-effect-phase.ts
  src/phases/move-phase.ts
  test/moves/fairy_lock.test.ts
  test/moves/safeguard.test.ts
  test/moves/toxic_spikes.test.ts
  test/testUtils/helpers/moveHelper.ts
Labels: Move, P2 Bug

#218 [Refactor] Improvements on FixedInt
  src/battle-scene.ts
  src/field/damage-number-handler.ts
  src/field/pokemon-sprite-sparkle-handler.ts
  src/field/pokemon.ts
  src/phases/damage-anim-phase.ts
  src/phases/egg-hatch-phase.ts
  src/phases/evolution-phase.ts
  src/phases/form-change-phase.ts
  src/phases/party-heal-phase.ts
  src/phases/reload-session-phase.ts
  src/system/game-data.ts
  src/system/game-speed.ts
  src/ui/abstact-option-select-ui-handler.ts
  src/ui/arena-flyout.ts
  src/ui/battle-flyout.ts
  src/ui/battle-info.ts
  src/ui/egg-gacha-ui-handler.ts
  src/ui/fight-ui-handler.ts
  src/ui/form-modal-ui-handler.ts
  src/ui/login-form-ui-handler.ts
  src/ui/menu-ui-handler.ts
  src/ui/move-info-overlay.ts
  src/ui/mystery-encounter-ui-handler.ts
  src/ui/pokemon-icon-anim-handler.ts
  src/ui/pokemon-info-container.ts
  src/ui/run-history-ui-handler.ts
  src/ui/save-slot-select-ui-handler.ts
  src/ui/saving-icon-handler.ts
  src/ui/starter-select-ui-handler.ts
  src/ui/summary-ui-handler.ts
  src/ui/target-select-ui-handler.ts
  src/ui/time-of-day-widget.ts
  src/ui/title-ui-handler.ts
  src/utils.ts
Labels: Refactor

#130 [P2] Court change no longer misses and swaps safeguard+pledge moves and can fail if nothing swappable
  src/data/all-abilities.ts
  src/data/all-moves.ts
  src/data/move-attrs/swap-arena-tags-attr.ts
  test/moves/court_change.test.ts
Labels: Move, P2 Bug

#230 [Misc] Replace `!!` with `> 0` check in `MovePhase.canMove`
  src/phases/move-phase.ts
Labels: Miscellaneous

#216 [Balance] Tweak Johto gyms
  src/data/balance/signatureSpecies.ts
Labels: Balance

#231 [Dev] Fix waive roll fee override
  src/overrides.ts
  src/phases/learn-move-phase.ts
  src/phases/select-modifier-phase.ts
  src/ui/modifier-select-ui-handler.ts
Labels: Miscellaneous

#172 [Ability][Checkup][Bug] Fur Coat Test + Documentation + Fixing incorrect damage calculations re: DefAtkAttr moves
  src/data/ab-attrs/stat-multiplier-ab-attr.ts
  src/data/all-abilities.ts
  src/data/all-moves.ts
  src/data/move-attrs/def-atk-attr.ts
  src/field/pokemon.ts
  test/abilities/fur_coat.test.ts
Labels: Ability, Checkup

#220 [Misc] Added Code of Conduct to repository.
  CODE_OF_CONDUCT.md
  README.md
Labels: Miscellaneous

#240 [Test] Rename `game.pokemonHelper` to `game.field`
  test/moves/toxic_spikes.test.ts
  test/moves/whirlwind.test.ts
  test/moves/will_o_wisp.test.ts
  test/testUtils/gameManager.ts
  test/testUtils/helpers/fieldHelper.ts
Labels: Tests

#219 [P1 Bug] Fix Sticky Hold and Unaware bugs from AbAttr refactor
  src/battle-scene.ts
  src/data/ab-attrs/ignore-opponent-stat-stages-ab-attr.ts
  src/data/move-attrs/steal-held-item-chance-attr.ts
  test/abilities/sticky_hold.test.ts
  test/abilities/unaware.test.ts
Labels: Ability, P1 Bug

#241 [P2] Fix Tera Shell changing type effectiveness from simulated calls
  src/data/ab-attrs/full-hp-resist-type-ab-attr.ts
Labels: Ability, P2 Bug

#249 [Refactor] Remove string assignments from Tutorial and Tag Type enums
  src/data/all-moves.ts
  src/enums/arena-tag-type.ts
  src/enums/battler-tag-type.ts
  src/field/arena.ts
  src/phases/encounter-phase.ts
  src/phases/login-phase.ts
  src/phases/stat-stage-change-phase.ts
  src/system/game-data.ts
  src/tutorial.ts
  src/ui/arena-flyout.ts
  src/ui/egg-gacha-ui-handler.ts
  src/ui/menu-ui-handler.ts
  src/ui/modifier-select-ui-handler.ts
  src/ui/starter-select-ui-handler.ts
  test/moves/alluring_voice.test.ts
Labels: Refactor

#186 [Refactor] Consolidate anims into a single class
  src/animations.ts
  src/battle-scene.ts
  src/data/all-abilities.ts
  src/data/mystery-encounters/encounters/fun-and-games-encounter.ts
  src/data/mystery-encounters/encounters/global-trade-system-encounter.ts
  src/data/mystery-encounters/utils/encounter-pokemon-utils.ts
  src/data/mystery-encounters/utils/encounter-transformation-sequence.ts
  src/field/anims.ts
  src/field/mystery-encounter-intro.ts
  src/field/pokemon.ts
  src/phases/abstract-form-change-base-phase.ts
  src/phases/attempt-capture-phase.ts
  src/phases/egg-hatch-phase.ts
  src/phases/evolution-phase.ts
  src/phases/form-change-phase.ts
  src/phases/summon-phase.ts
Labels: Refactor

#253 [Ability][Checkup] Changed file name/ability attribute of Early Bird + trySetStatus considers turnsRemaining even if asPhase is set to 'false'
  src/data/ab-attrs/reduce-sleep-duration-ab-attr.ts
  src/data/all-abilities.ts
  src/field/pokemon.ts
  src/phases/move-phase.ts
  test/abilities/early_bird.test.ts
Labels: Ability, Checkup

#228 [Balance] Tweak Hoenn gyms
  src/data/balance/signatureSpecies.ts
Labels: Balance

#247 [Test] Enable `--no-isolate` for unit tests
  .github/pull_request_template.md
  .github/workflows/test-shard-template.yml
  README.md
  package.json
  src/battle-scene.ts
  src/field/pokemon.ts
  src/overrides.ts
  test/battlerTags/substitute.test.ts
  test/data/status_effect.test.ts
  test/moves/fusion_flare_bolt.test.ts
  test/mystery-encounter/encounter-test-utils.ts
  test/phases/select-modifier-phase.test.ts
  test/plugins/api/account-api.test.ts
  test/plugins/api/admin-api.test.ts
  test/plugins/api/api.test.ts
  test/plugins/api/daily-api.test.ts
  test/plugins/api/savedata-api.test.ts
  test/plugins/api/session-savedata-api.test.ts
  test/plugins/api/system-savedata-api.test.ts
  test/testUtils/gameManager.ts
  test/testUtils/gameWrapper.ts
  test/testUtils/helpers/overridesHelper.ts
  test/testUtils/listenersManager.ts
  test/testUtils/mocks/mockCanvas.ts
  test/testUtils/mocks/mockConsoleLog.ts
  test/testUtils/mocks/mockContext.ts
  test/testUtils/testFileInitialization.ts
  test/vitest.setup.ts
  vitest.config.ts
Labels: Tests

#254 [Balance] Removed Tokens from the game
  src/field/pokemon.ts
  src/modifier/modifier-type.ts
  src/modifier/modifier.ts
  src/phases/add-enemy-buff-modifier-phase.ts
  src/phases/move-effect-phase.ts
  src/phases/turn-end-phase.ts
  src/phases/victory-phase.ts
  src/system/game-data.ts
Labels: Balance, Item

#269 [Dev] Revert back workflows to use ubuntu-latest
  .github/workflows/deploy-beta.yml
  .github/workflows/deploy.yml
  .github/workflows/eslint.yml
  .github/workflows/github-pages.yml
  .github/workflows/test-shard-template.yml
Labels: GitHub

#274 [Test] Change Glaive Rush test to not modify moves' accuracy
  test/moves/glaive_rush.test.ts
Labels: Tests

#273 [Bug] Fix generic trapped text not displaying
  src/phases/command-phase.ts
Labels: Ability, P3 Bug

#282 [Bug] Fix Misty Explosion making contact
  src/data/move.ts
Labels: Move, P2 Bug

#285 [MISC] add app abbreviation env & constant
  .env
  src/constants.ts
  src/vite.env.d.ts
  test/testUtils/saves/everything.pkty.txt
Labels: Miscellaneous

#270 [Beta][P2] Fix tutorial seen flags not being set/read properly
  src/constants.ts
  src/system/game-data.ts
  src/tutorial.ts
Labels: P2 Bug, Beta

#120 [Move] Partially Reimplement Future Sight and Doom Desire
  src/data/ab-attrs/post-defend-apply-arena-trap-tag-ab-attr.ts
  src/data/all-moves.ts
  src/data/arena-tag.ts
  src/data/move-attrs/add-arena-tag-attr.ts
  src/data/move-attrs/add-arena-trap-tag-hit-attr.ts
  src/data/move-attrs/delayed-attack-attr.ts
  src/enums/arena-tag-type.ts
  src/field/arena.ts
  src/phases/attempt-run-phase.ts
  src/phases/move-phase.ts
  src/phases/victory-phase.ts
  src/ui/arena-flyout.ts
  test/abilities/infiltrator.test.ts
  test/abilities/magic_guard.test.ts
  test/abilities/wimp_out.test.ts
  test/battle/damage_calculation.test.ts
  test/battle/inverse_battle.test.ts
  test/moves/future_sight.test.ts
Labels: Move

#229 [Balance] Tweak Sinnoh gyms
  src/data/balance/signatureSpecies.ts
Labels: Balance

#271 [Balance] Tweak Kalos gyms
  src/data/balance/signatureSpecies.ts
Labels: Balance

#243 [Balance] Tweak Unova gyms
  src/data/balance/signatureSpecies.ts
Labels: Balance

#290 [Bug] Fix `arena.addTag()` args orderings
  src/data/arena-tag.ts
  src/data/move-attrs/swap-arena-tags-attr.ts
  test/moves/brick_break.test.ts
  test/moves/court_change.test.ts
  test/moves/defog.test.ts
  test/moves/rapid_spin.test.ts
Labels: Move, P2 Bug

#287 [Beta][Feature] Use `Set` for seen tutorials
  src/system/game-data.ts
Labels: Enhancement, Beta

#275 [MISC] Vite 6.0.7 | vitest 2.1.8
  package-lock.json
  package.json
Labels: Miscellaneous

#199 [Refactor] Improved type enforcement for `applyMoveAttrs`
  src/data/move-attrs/bypass-sleep-attr.ts
  src/data/move-attrs/override-move-effect-attr.ts
  src/data/move-attrs/variable-move-type-attr.ts
  src/data/move-attrs/variable-move-type-chart-attr.ts
  src/data/move.ts
  src/phases/move-effect-phase.ts
Labels: Move, Refactor

#268 [Checkup][Moves] Move Validation
  src/data/all-moves.ts
  src/enums/move-category.ts
  src/enums/type.ts
  test/moves/all_moves.json
  test/moves/all_moves.test.ts
Labels: Move, P2 Bug, Checkup

#288 [Refactor][Bug] Cleaning up functions related to releasing a Pokemon
  src/battle-scene.ts
  src/ui/party-ui-handler.ts
Labels: P1 Bug, Refactor

#292 [Misc] Update CREDITS.md
  CREDITS.md
Labels: Documentation, Miscellaneous

#293 [Refactor] Replace `OPP_` with `ENEMY_` in overrides
  src/battle-scene.ts
  src/field/pokemon.ts
  src/modifier/modifier.ts
  src/overrides.ts
  src/phases/encounter-phase.ts
  test/testUtils/gameManager.ts
  test/testUtils/helpers/challengeModeHelper.ts
  test/testUtils/helpers/classicModeHelper.ts
  test/testUtils/helpers/dailyModeHelper.ts
  test/testUtils/helpers/moveHelper.ts
  test/testUtils/helpers/overridesHelper.ts
Labels: Refactor, Tests

#263 [P1 Bug] Several Sky Drop updates
  src/data/ab-attrs/commander-ab-attr.ts
  src/data/all-moves.ts
  src/data/arena-tag.ts
  src/data/battler-tags.ts
  src/data/move-attrs/sky-drop-attr.ts
  src/field/pokemon.ts
  src/phases/command-phase.ts
  src/phases/faint-phase.ts
  src/phases/move-effect-phase.ts
  test/abilities/commander.test.ts
  test/moves/sky_drop.test.ts
Labels: Move, P1 Bug

#296 [Bug] Fix args for usages of `applyAbAttrs`
  src/data/ab-attrs/terrain-event-type-change-ab-attr.ts
  src/data/ability.ts
  src/data/move-attrs/status-effect-attr.ts
  src/field/arena.ts
  test/abilities/poison_puppeteer.test.ts
  test/abilities/suction_cups.test.ts
Labels: Ability, P2 Bug, P3 Bug

#297 [Ability][Checkup] Triage Checkup
  src/data/ab-attrs/change-move-priority-ab-attr.ts
  src/data/all-abilities.ts
  test/abilities/triage.test.ts
Labels: Checkup

#295 [Refactor] Add `AbstractConstructor` util + Convert parent move/ability attributes to `abstract`
  src/battle-scene.ts
  src/data/ab-attrs/field-move-power-boost-ab-attr.ts
  src/data/ab-attrs/post-attack-ab-attr.ts
  src/data/ab-attrs/post-battle-ab-attr.ts
  src/data/ab-attrs/post-battle-init-ab-attr.ts
  src/data/ab-attrs/post-biome-change-ab-attr.ts
  src/data/ab-attrs/post-damage-ab-attr.ts
  src/data/ab-attrs/post-defend-ab-attr.ts
  src/data/ab-attrs/post-faint-ab-attr.ts
  src/data/ab-attrs/post-item-lost-ab-attr.ts
  src/data/ab-attrs/post-knock-out-ab-attr.ts
  src/data/ab-attrs/post-move-used-ab-attr.ts
  src/data/ab-attrs/post-stat-stage-change-ab-attr.ts
  src/data/ab-attrs/post-summon-ab-attr.ts
  src/data/ab-attrs/post-terrain-change-ab-attr.ts
  src/data/ab-attrs/post-turn-ab-attr.ts
  src/data/ab-attrs/post-victory-ab-attr.ts
  src/data/ab-attrs/post-weather-change-ab-attr.ts
  src/data/ab-attrs/post-weather-lapse-ab-attr.ts
  src/data/ab-attrs/pre-apply-battler-tag-ab-attr.ts
  src/data/ab-attrs/pre-attack-ab-attr.ts
  src/data/ab-attrs/pre-defend-ab-attr.ts
  src/data/ab-attrs/pre-set-status-ab-attr.ts
  src/data/ab-attrs/pre-stat-stage-change-ab-attr.ts
  src/data/ab-attrs/pre-switch-out-ab-attr.ts
  src/data/ab-attrs/pre-weather-damage-ab-attr.ts
  src/data/ab-attrs/pre-weather-effect-ab-attr.ts
  src/data/ab-attrs/variable-move-power-ab-attr.ts
  src/data/ability.ts
  src/data/arena-tag.ts
  src/data/move-attrs/modified-damage-attr.ts
  src/data/move-attrs/move-effect-attr.ts
  src/data/move-attrs/move-header-attr.ts
  src/data/move-attrs/override-move-effect-attr.ts
  src/data/move-attrs/variable-accuracy-attr.ts
  src/data/move-attrs/variable-atk-attr.ts
  src/data/move-attrs/variable-def-attr.ts
  src/data/move-attrs/variable-move-category-attr.ts
  src/data/move-attrs/variable-move-type-attr.ts
  src/data/move-attrs/variable-move-type-chart-attr.ts
  src/data/move-attrs/variable-move-type-multiplier-attr.ts
  src/data/move-attrs/variable-power-attr.ts
  src/data/move.ts
  src/data/pokemon-forms.ts
  src/field/arena.ts
  src/field/pokemon.ts
  src/utils.ts
Labels: Ability, Move, Refactor

#316 [Misc] Replace `globalScene` with `this` in `BattleScene`
  src/battle-scene.ts
Labels: Miscellaneous

#298 [Bug] Prevent pokemon with 0 HP from being statused
  src/field/pokemon.ts
  test/data/status_effect.test.ts
Labels: P2 Bug, Miscellaneous

#319 [Refactor] Future-proof `allMoves` to accommodate non-sequential `Moves` enum values
  src/battle-scene.ts
  src/data/all-moves.ts
  src/data/balance/egg-moves.ts
  test/testUtils/testFileInitialization.ts
Labels: Move, Refactor

#317 [Dev] Fix the RNG debugger
  src/battle-scene.ts
Labels: Miscellaneous

#312 [Bug] Fix being able to import data/session/run-history
  src/constants.ts
  src/system/game-data.ts
  src/ui/login-form-ui-handler.ts
  test/testUtils/testUtils.ts
Labels: P3 Bug

#272 [MISC] Improve minify json files vite plugin
  package-lock.json
  package.json
  src/plugins/vite/vite-minify-json-plugin.ts
  vite.config.ts
Labels: Miscellaneous

#311 [Ability][Checkup][Bug] Gale Wings Checkup
  src/data/all-abilities.ts
  test/abilities/gale_wings.test.ts
Labels: Ability, P2 Bug, Checkup

#315 [Refactor] Refactor trainer-config.initForChampion to prepare for gameplay changes
  src/data/balance/signatureSpecies.ts
  src/data/balance/trainer-configs/champion-trainer-configs.ts
  src/data/trainer-config.ts
Labels: Balance, Refactor

#303 [Checkup][P1 Bug] Aftermath checkup
  src/data/ab-attrs/post-faint-ab-attr.ts
  src/data/ab-attrs/post-faint-clear-weather-ab-attr.ts
  src/data/ab-attrs/post-faint-contact-damage-ab-attr.ts
  src/data/ab-attrs/post-faint-hp-damage-ab-attr.ts
  src/data/ab-attrs/post-faint-unsuppressed-weather-form-change-ab-attr.ts
  src/phases/faint-phase.ts
  test/abilities/aftermath.test.ts
Labels: Ability, P1 Bug, P2 Bug, Checkup

#318 [Refactor] trainer-config.initForEvilTeamLeader
  src/data/balance/trainer-configs/evil-boss-trainer-configs.ts
  src/data/trainer-config.ts
Labels: Refactor

#328 [P2] Fire+Grass pledge should not damage magic guard
  src/data/arena-tag.ts
  test/moves/pledge_moves.test.ts
Labels: Move, P2 Bug

#325 [Refactor] Cleanup achievement description code
  src/system/achv.ts
  src/system/voucher.ts
  src/ui/achv-bar.ts
  src/ui/achvs-ui-handler.ts
  test/achievements/achievement.test.ts
Labels: Refactor

#326 [Bug] Fix certain DoT anims showing on wrong side
  src/battle-scene.ts
  src/phases/common-anim-phase.ts
Labels: Move, P3 Bug

#294 [Move] Add gmax arena damage over time effects
  src/data/all-moves.ts
  src/data/arena-tag.ts
  src/data/move-attrs/swap-arena-tags-attr.ts
  src/enums/arena-tag-type.ts
  src/enums/moves.ts
  test/moves/all_moves.json
  test/moves/gmax_dot_arena.test.ts
Labels: Move

#310 [Ability][Checkup][Bug] Move Flag Power Boost Abilities Checkup
  src/data/ab-attrs/move-flag-power-boost-ab-attr.ts
  src/data/ab-attrs/recovery-boost-ab-attr.ts
  src/data/all-abilities.ts
  src/data/move-attrs/heal-attr.ts
  test/abilities/mega_launcher.test.ts
  test/abilities/move_flag_power_boost.test.ts
  test/abilities/punk_rock.test.ts
  test/abilities/triage.test.ts
Labels: Ability, P2 Bug, Checkup

#332 [Move] Add attr for changing stats of all opps
  src/data/all-moves.ts
  src/data/move-attrs/stat-stage-change-all-opps-attr.ts
  test/moves/gmax_opp_stat_stage_change.test.ts
Labels: Move

#324 [Documentation] Document getWaveMoneyAmount
  src/battle-scene.ts
Labels: Documentation

#323 [Refactor] Various improvements to achievements
  src/@types/common.ts
  src/battle-scene.ts
  src/system/achv.ts
  src/system/voucher.ts
  src/ui/achv-bar.ts
  src/ui/achvs-ui-handler.ts
  test/achievements/achievement.test.ts
Labels: Refactor, Miscellaneous

#238 [UI] Refactor Option Select and Confirm UI handlers
  src/data/mystery-encounters/encounters/bug-type-superfan-encounter.ts
  src/data/mystery-encounters/encounters/clowning-around-encounter.ts
  src/data/mystery-encounters/encounters/dancing-lessons-encounter.ts
  src/data/mystery-encounters/encounters/delibirdy-encounter.ts
  src/data/mystery-encounters/encounters/field-trip-encounter.ts
  src/data/mystery-encounters/encounters/global-trade-system-encounter.ts
  src/data/mystery-encounters/encounters/training-session-encounter.ts
  src/data/mystery-encounters/utils/encounter-dialogue-utils.ts
  src/data/mystery-encounters/utils/encounter-phase-utils.ts
  src/data/mystery-encounters/utils/encounter-pokemon-utils.ts
  src/data/nature.ts
  src/phases/attempt-capture-phase.ts
  src/phases/check-switch-phase.ts
  src/phases/egg-lapse-phase.ts
  src/phases/evolution-phase.ts
  src/phases/game-over-phase.ts
  src/phases/learn-move-phase.ts
  src/phases/scan-ivs-phase.ts
  src/phases/select-biome-phase.ts
  src/phases/select-gender-phase.ts
  src/phases/select-modifier-phase.ts
  src/phases/title-phase.ts
  src/system/game-data.ts
  src/system/settings/settings-gamepad.ts
  src/tutorial.ts
  src/ui/abstact-option-select-ui-handler.ts
  src/ui/abstract-option-select-ui-handler.ts
  src/ui/autocomplete-ui-handler.ts
  src/ui/awaitable-ui-handler.ts
  src/ui/battle-message-ui-handler.ts
  src/ui/confirm-ui-handler.ts
  src/ui/interfaces/confirm-menu-config.ts
  src/ui/interfaces/option-select-config.ts
  src/ui/interfaces/option-select-ui-item.ts
  src/ui/login-form-ui-handler.ts
  src/ui/menu-ui-handler.ts
  src/ui/option-select-ui-handler.ts
  src/ui/party-ui-handler.ts
  src/ui/pokemon-info-container.ts
  src/ui/save-slot-select-ui-handler.ts
  src/ui/scroll-bar.ts
  src/ui/settings/abstract-settings-ui-handler.ts
  src/ui/settings/option-select-ui-handler.ts
  src/ui/settings/settings-display-ui-handler.ts
  src/ui/starter-select-ui-handler.ts
  src/ui/test-dialogue-ui-handler.ts
  src/ui/text.ts
  src/ui/title-ui-handler.ts
  src/ui/ui.ts
  test/mystery-encounter/encounter-test-utils.ts
  test/mystery-encounter/encounters/clowning-around-encounter.test.ts
  test/rng/reload.test.ts
  test/testUtils/mocks/mockTextureManager.ts
  test/testUtils/mocks/mocksContainer/mockBBCodeText.ts
  test/testUtils/mocks/mocksContainer/mockInputText.ts
  test/testUtils/testFileInitialization.ts
  test/ui/starter-select.test.ts
Labels: Refactor, UI/UX

#341 [Security] update vite to `6.0.11` (security patch)
  package-lock.json
  package.json
Labels: Dependencies

#338 [Test] `toNextTurn` now takes double battles into account
  test/abilities/arena_trap.test.ts
  test/abilities/forecast.test.ts
  test/moves/powder.test.ts
  test/testUtils/gameManager.ts
Labels: Tests

#339 [Test] Fix flaky Wimp Out test
  test/abilities/wimp_out.test.ts
Labels: Tests

#346 [Test] Fix Toxic Spikes double battle test to actually use a double battle
  test/moves/toxic_spikes.test.ts
Labels: Tests

#334 [Move] Add low hanging fruit gmax move effects
  src/data/all-moves.ts
Labels: Move

#342 [Misc] Patch minify-public-json-files plugin (aesthetic) to `2.0.1`
  src/plugins/vite/vite-minify-public-json-files.ts
  vite.config.ts
Labels: Miscellaneous

#347 [Misc] Update `utils.ts`
  src/modifier/modifier-type.ts
  src/ui/fight-ui-handler.ts
  src/ui/pokemon-hatch-info-container.ts
  src/ui/settings/abstract-settings-ui-handler.ts
  src/ui/starter-select-ui-handler.ts
  src/ui/summary-ui-handler.ts
  src/utils.ts
  test/utils/utils.test.ts
Labels: Refactor, Miscellaneous

#329 [Refactor][Ability] Add `REVEALED` and `IGNORE` modes for ability application
  src/data/ab-attrs/copy-fainted-ally-ability-ab-attr.ts
  src/data/ab-attrs/download-ab-attr.ts
  src/data/ab-attrs/frisk-ab-attr.ts
  src/data/ab-attrs/post-defend-ability-give-ab-attr.ts
  src/data/ab-attrs/post-defend-ability-swap-ab-attr.ts
  src/data/ab-attrs/post-summon-copy-ability-ab-attr.ts
  src/data/ability-filter-options.ts
  src/data/ability-utils.ts
  src/data/ability.ts
  src/data/all-moves.ts
  src/data/move-attrs/chance-based-move-effect-attr.ts
  src/data/move-attrs/def-atk-attr.ts
  src/data/move-attrs/photon-geyser-category-attr.ts
  src/data/move-attrs/shell-side-arm-category-attr.ts
  src/data/move-attrs/target-atk-user-atk-attr.ts
  src/data/move-attrs/tera-move-category-attr.ts
  src/enums/ability-apply-mode.ts
  src/field/pokemon.ts
  src/phases/hit-check-phase.ts
  src/phases/move-effect-phase.ts
  src/phases/show-ability-phase.ts
  src/ui/fight-ui-handler.ts
  test/abilities/infiltrator.test.ts
  test/abilities/unaware.test.ts
  test/moves/photon_geyser.test.ts
  test/moves/shell_side_arm.test.ts
  test/moves/tera_blast.test.ts
  test/moves/u_turn.test.ts
Labels: Ability, Refactor, AI

#304 [Test][Security] Upgrade to vitest `3.0.2`, update vitest configuration
  .github/workflows/test-shard-template.yml
  .github/workflows/tests.yml
  package-lock.json
  package.json
  src/plugins/i18n.ts
  test/battlerTags/stockpiling.test.ts
  test/vitest.setup.ts
  vitest.config.ts
  vitest.workspace.ts
Labels: Dependencies, Tests, Security

#352 [Checkup] Overcoat / Bulletproof / Soundproof
  src/data/ab-attrs/block-weather-damage-attr.ts
  src/data/ab-attrs/move-flag-immunity-ab-attr.ts
  src/data/all-abilities.ts
  src/data/all-moves.ts
  src/data/battler-tags.ts
  src/data/move.ts
  src/enums/move-flags.ts
  test/abilities/bulletproof.test.ts
  test/abilities/move_flag_immunity.test.ts
  test/abilities/move_flag_power_boost.test.ts
  test/abilities/overcoat.test.ts
  test/abilities/soundproof.test.ts
  test/moves/all_moves.test.ts
Labels: Checkup

#353 [Balance] Bring back gmax immunities
  src/data/ab-attrs/post-defend-ability-give-ab-attr.ts
  src/data/ab-attrs/post-defend-ability-swap-ab-attr.ts
  src/data/ab-attrs/post-defend-move-disable-ab-attr.ts
  src/data/all-moves.ts
  src/data/battler-tags.ts
  src/data/move-attrs/force-switch-out-attr.ts
  src/data/move-conditions.ts
Labels: Balance

#348 [Move] Add a Gmax flag
  src/data/all-moves.ts
  src/data/move-attrs/stat-stage-change-all-opps-attr.ts
  src/data/move.ts
  src/enums/move-flags.ts
  src/phases/move-effect-phase.ts
Labels: Move, Refactor

#367 [Misc] Remove duplicate import from `pokemon-species.ts`
  src/data/pokemon-species.ts
Labels: Miscellaneous

#362 [Move] Implement gmax status moves
  src/data/all-moves.ts
Labels: Move

#355 [Balance] Revert custom gmax data
  src/data/pokemon-species.ts
Labels: Balance

#365 [Move] Implement gmax centiferno and sandblast
  src/data/all-moves.ts
  src/data/battler-tags.ts
  src/data/move-attrs/add-battler-tag-attr.ts
  src/data/move-attrs/lapse-battler-tag-attr.ts
  src/data/move-attrs/remove-battler-tag-attr.ts
  src/enums/battler-tag-type.ts
  test/battlerTags/vortexTrapTag.test.ts
Labels: Move

#366 [Move] Implement rest of g-max moves
  src/data/all-moves.ts
  src/data/battler-tags.ts
  src/phases/move-effect-phase.ts
  test/moves/all_moves.json
Labels: Move

#372 [Test] Update Unaware test to use `expect.toBeOneOf()`
  test/abilities/unaware.test.ts
Labels: Tests

#356 [AI-Rework] Add starter code for move scoring functions
  src/data/move-attrs/move-attr.ts
  src/data/move-conditions.ts
  src/data/move.ts
  src/field/pokemon.ts
Labels: Move, AI

#375 [Test] Add tests for Present
  test/moves/present.test.ts
Labels: Tests

#379 [Misc] Moved all_moves data and test into test/data
  test/data/all_moves.json
  test/data/all_moves.test.ts
  test/moves/all_moves.json
Labels: Miscellaneous

#358 [Move][Checkup] Reimplement Body Press, Foul Play, and Psyshock et al.
  src/data/move-attrs/deals-physical-damage-attr.ts
  src/data/move-attrs/def-atk-attr.ts
  src/data/move-attrs/target-atk-user-atk-attr.ts
  src/data/move-attrs/variable-atk-attr.ts
  src/data/move-attrs/variable-def-attr.ts
  src/data/move.ts
  src/field/pokemon.ts
  test/abilities/unaware.test.ts
  test/moves/body_press.test.ts
  test/moves/foul_play.test.ts
  test/moves/psyshock.test.ts
Labels: Move, Refactor

#337 [Move][Checkup] Present RNG Fixes
  src/data/move-attrs/present-power-attr.ts
  src/field/pokemon.ts
  test/abilities/triage.test.ts
  test/moves/present.test.ts
Labels: Move, P2 Bug, Checkup

#381 [Ability][Checkup] Huge Power Checkup + Self-Inflicted Confusion Damage now ignores abilities
  src/data/battler-tags.ts
  test/abilities/huge_power.test.ts
Labels: Ability, P2 Bug, Checkup

#382 [Dev] RNG debugger now outputs source of RNG calls
  src/battle-scene.ts
  src/battle.ts
  src/data/egg.ts
  src/data/mystery-encounters/utils/encounter-phase-utils.ts
  src/field/pokemon.ts
  src/loggers.ts
  src/utils.ts
Labels: Miscellaneous

#363 [UI/UX] Make settings options cursor wrap
  src/@types/Settings.ts
  src/ui/settings/abstract-settings-ui-handler.ts
  src/ui/settings/settings-ui-items.ts
Labels: UI/UX
