Repository Despair-Games/poketernity, pull requests merged in 2025-08, with the labels that each got.

#1306 [Refactor] Change `Pokemon#moveset` to `protected`
  src/data/abilities/ab-attrs/forewarn-ab-attr.ts
  src/data/berry.ts
  src/data/challenge.ts
  src/data/moves/move-attrs/less-pp-more-power-attr.ts
  src/data/moves/move-attrs/random-moveset-move-attr.ts
  src/data/mystery-encounters/encounters/absolute-avarice-encounter.ts
  src/data/mystery-encounters/encounters/clowning-around-encounter.ts
  src/data/mystery-encounters/encounters/dancing-lessons-encounter.ts
  src/data/mystery-encounters/encounters/field-trip-encounter.ts
  src/data/mystery-encounters/encounters/global-trade-system-encounter.ts
  src/data/mystery-encounters/encounters/part-timer-encounter.ts
  src/data/mystery-encounters/encounters/uncommon-breed-encounter.ts
  src/data/mystery-encounters/encounters/weird-dream-encounter.ts
  src/data/mystery-encounters/mystery-encounter-requirements.ts
  src/data/mystery-encounters/utils/encounter-phase-utils.ts
  src/data/pokemon-evolutions.ts
  src/data/species-form-change-triggers/species-form-change-move-learned-trigger.ts
  src/data/trainer-configs/evil-team-trainer-configs.ts
  src/field/pokemon.ts
  src/modifier/modifier-type.ts
  src/phases/learn-move-phase.ts
  src/phases/party-heal-phase.ts
  src/system/pokemon-data.ts
  src/ui/components/pokemon-info-container.ts
  src/ui/handlers/party-ui-handler.ts
  src/ui/handlers/summary-ui-handler.ts
  test/abilities/dancer.test.ts
  test/game-modes/daily-mode.test.ts
  test/moves/instruct.test.ts
  test/moves/powder.test.ts
  test/moves/sketch.test.ts
  test/mystery-encounter/encounters/absolute-avarice-encounter.test.ts
  test/mystery-encounter/encounters/an-offer-you-cant-refuse-encounter.test.ts
  test/mystery-encounter/encounters/clowning-around-encounter.test.ts
  test/mystery-encounter/encounters/dancing-lessons-encounter.test.ts
  test/mystery-encounter/encounters/fight-or-flight-encounter.test.ts
  test/mystery-encounter/encounters/part-timer-encounter.test.ts
  test/mystery-encounter/encounters/the-pokemon-salesman-encounter.test.ts
  test/mystery-encounter/encounters/the-strong-stuff-encounter.test.ts
  test/mystery-encounter/encounters/trash-to-treasure-encounter.test.ts
  test/mystery-encounter/encounters/uncommon-breed-encounter.test.ts
  test/phases/form-change-phase.test.ts
  test/test-utils/game-manager-utils.ts
  test/test-utils/helpers/move-helper.ts
Labels: Refactor

#1302 [Refactor] Convert `enum`s to `const` objects part 3
  src/@types/move-types.ts
  src/@types/settings.ts
  src/data/exp.ts
  src/data/init/init-encounter-anims.ts
  src/enums/encounter-anim.ts
  src/enums/event-modifier-type.ts
  src/enums/exp-gain-speed.ts
  src/enums/exp-gains-speed.ts
  src/enums/exp-notification.ts
  src/enums/field-position.ts
  src/enums/gacha-type.ts
  src/enums/game-data-type.ts
  src/enums/game-modes.ts
  src/enums/gender.ts
  src/enums/growth-rate.ts
  src/enums/hit-check-result.ts
  src/enums/hit-result.ts
  src/enums/hp-bar-speed.ts
  src/field/damage-number-handler.ts
  src/field/pokemon.ts
  src/loading-scene.ts
  src/phases/damage-anim-phase.ts
  src/phases/move-charge-phase.ts
  src/phases/move-effect-phase.ts
  src/phases/show-party-exp-bar-phase.ts
  src/system/game-data.ts
  src/system/settings/default-settings.ts
  src/ui/components/battle-info.ts
  src/ui/components/party-exp-bar.ts
  src/ui/handlers/egg-gacha-ui-handler.ts
  src/ui/handlers/starter-select-ui-handler.ts
  src/ui/settings/settings-ui-items.ts
  test/test-utils/game-manager.ts
  test/test-utils/helpers/settings-helper.ts
  test/ui/battle-info.test.ts
Labels: Refactor

#1313 github: add workflow to lint PR title
  .github/pull_request_template.md
  .github/scripts/pr-title.ts
  .github/workflows/pr-title.yml
  biome.jsonc
  package.json
  pnpm-lock.yaml
Labels: GitHub

#1315 fix(art): Fix ME exclamation image not being loaded properly
  src/phases/encounter-phase.ts
Labels: P3, Art / Graphics

#1319 misc: remove unused code from `BattleScene#initStarterColors`
  src/battle-scene.ts
Labels: Miscellaneous

#1309 dev: add and apply `lint/style/useShorthandAssign` Biome rule
  biome.jsonc
  src/animations.ts
  src/battle-scene.ts
  src/data/abilities/ab-attrs/double-battle-chance-ab-attr.ts
  src/data/animations/battle-anims.ts
  src/data/moves/move-attrs/hit-heal-attr.ts
  src/data/mystery-encounters/encounters/absolute-avarice-encounter.ts
  src/data/mystery-encounters/utils/encounter-phase-utils.ts
  src/data/pokemon-species-form.ts
  src/field/pokemon.ts
  src/modifier/modifier.ts
  test/abilities/dry-skin.test.ts
  test/abilities/unaware.test.ts
  test/abilities/volt-absorb.test.ts
Labels: Development

#1314 refactor: Pokemon IDs are now unique and can't be `0`
  src/battle-scene.ts
  src/data/mystery-encounters/utils/encounter-phase-utils.ts
  src/field/pokemon.ts
  src/system/pokemon-data.ts
  test/test-utils/helpers/rng-helper.ts
Labels: Refactor

#1312 ai-rework: Add Effect Scores for Status Effect inflicting moves
  src/constants/ability-constants.ts
  src/constants/ai-constants.ts
  src/data/moves/move-attrs/move-effect-attr.ts
  src/data/moves/move-attrs/multi-status-effect-attr.ts
  src/data/moves/move-attrs/status-effect-attr.ts
  src/data/moves/move.ts
  src/field/enemy-pokemon.ts
  test/ai/move-effect-scores/spore.test.ts
  test/ai/move-effect-scores/thunder-wave.test.ts
  test/ai/move-effect-scores/toxic.test.ts
  test/ai/move-effect-scores/will-o-wisp.test.ts
Labels: AI, Addendum

#1325 dev: add simple Biome rules
  biome.jsonc
  src/battle-scene.ts
  src/data/mystery-encounters/encounters/absolute-avarice-encounter.ts
  src/data/mystery-encounters/encounters/bug-type-superfan-encounter.ts
  src/field/enemy-pokemon.ts
  src/loggers.ts
  src/modifier/modifier-type.ts
  src/system/game-data.ts
  src/ui/handlers/party-ui-handler.ts
  src/utils/common-utils.ts
  test/abilities/power-construct.test.ts
  test/abilities/schooling.test.ts
  test/abilities/shields-down.test.ts
  test/mystery-encounter/mystery-encounter-utils.test.ts
  test/ui/transfer-item.test.ts
Labels: Development

#1330 ai-rework: Add Effect Scores for healing effects
  src/data/moves/move-attrs/heal-attr.ts
  src/data/moves/move-attrs/heal-on-ally-attr.ts
  src/data/moves/move-attrs/hit-heal-attr.ts
  src/data/moves/move-attrs/hp-split-attr.ts
  test/ai/move-effect-scores/drain-punch.test.ts
  test/ai/move-effect-scores/heal-pulse.test.ts
  test/ai/move-effect-scores/pain-split.test.ts
  test/ai/move-effect-scores/pollen-puff.test.ts
  test/ai/move-effect-scores/recover.test.ts
  test/ai/move-effect-scores/strength-sap.test.ts
Labels: AI, Addendum

#1308 refactor: convert `enum`s to `const` objects part 4
  src/battle-scene.ts
  src/data/abilities/ab-attrs/redirect-move-ab-attr.ts
  src/data/abilities/ab-attrs/type-immunity-ab-attr.ts
  src/data/init/init-moves.ts
  src/data/moves/move-attrs/call-move-attr.ts
  src/data/moves/move-attrs/multi-hit-attr.ts
  src/data/moves/move.ts
  src/enums/battler-index.ts
  src/enums/evolution-item.ts
  src/enums/font-style.ts
  src/enums/form-change-item.ts
  src/enums/images-folder.ts
  src/enums/item-rarity.ts
  src/enums/learn-move-type.ts
  src/enums/modifier-pool-type.ts
  src/enums/modifier-tier.ts
  src/enums/money-format.ts
  src/enums/move-category.ts
  src/enums/move-effect-trigger.ts
  src/enums/move-flags.ts
  src/enums/move-result.ts
  src/enums/move-source-type.ts
  src/enums/move-target.ts
  src/enums/multi-hit-type.ts
  src/enums/mystery-encounter-mode.ts
  src/enums/mystery-encounter-option-mode.ts
  src/enums/mystery-encounter-tier.ts
  src/enums/mystery-encounter-type.ts
  src/enums/party-member-strength.ts
  src/enums/player-gender.ts
  src/enums/pokeball-type.ts
  src/field/pokemon.ts
  src/phases/encounter-phase.ts
  src/phases/game-over-phase.ts
  src/system/achievements.ts
  src/turn-command-manager.ts
  src/ui/components/move-info-overlay.ts
  src/ui/handlers/achievements-ui-handler.ts
  src/ui/handlers/ball-ui-handler.ts
  src/ui/handlers/fight-ui-handler.ts
  src/ui/handlers/mystery-encounter-ui-handler.ts
  src/ui/handlers/run-history-ui-handler.ts
  src/ui/handlers/run-info-ui-handler.ts
  src/ui/handlers/summary-ui-handler.ts
  src/ui/ui.ts
  src/utils/common-utils.ts
  test/abilities/battle-bond.test.ts
  test/data/all-moves.test.ts
  test/test-utils/helpers/settings-helper.ts
  test/test-utils/matchers/to-have-move-result-matcher.ts
Labels: Refactor

#1333 dev: remove default export from `overrides.ts`
  src/battle-scene.ts
  src/data/battler-tags/confused-tag.ts
  src/data/battler-tags/infatuated-tag.ts
  src/data/egg.ts
  src/data/trainer-config.ts
  src/field/arena.ts
  src/field/enemy-pokemon.ts
  src/field/player-pokemon.ts
  src/field/pokemon.ts
  src/game-mode.ts
  src/modifier/modifier-type.ts
  src/modifier/modifier.ts
  src/overrides.ts
  src/phases/egg-lapse-phase.ts
  src/phases/encounter-phase.ts
  src/phases/enemy-command-phase.ts
  src/phases/learn-move-phase.ts
  src/phases/move-phase.ts
  src/phases/select-modifier-phase.ts
  src/phases/select-starter-phase.ts
  src/system/game-data.ts
  src/tutorial.ts
  src/ui/handlers/egg-gacha-ui-handler.ts
  src/ui/handlers/modifier-select-ui-handler.ts
  src/ui/handlers/starter-select-ui-handler.ts
  test/test-utils/game-manager.ts
  test/test-utils/helpers/challenge-mode-helper.ts
  test/test-utils/helpers/classic-mode-helper.ts
  test/test-utils/helpers/daily-mode-helper.ts
  test/test-utils/helpers/move-helper.ts
  test/test-utils/helpers/overrides-helper.ts
  test/vitest.setup.ts
Labels: Development

#1337 ai-rework: Add scoring for `StatStageChangeAttr` + subclasses
  src/constants/ability-constants.ts
  src/constants/ai-constants.ts
  src/data/moves/move-attrs/chance-based-move-effect-attr.ts
  src/data/moves/move-attrs/cut-hp-stat-stage-boost-attr.ts
  src/data/moves/move-attrs/faint-countdown-attr.ts
  src/data/moves/move-attrs/growth-stat-stage-change-attr.ts
  src/data/moves/move-attrs/heal-attr.ts
  src/data/moves/move-attrs/heal-on-ally-attr.ts
  src/data/moves/move-attrs/heal-status-effect-attr.ts
  src/data/moves/move-attrs/helping-hand-attr.ts
  src/data/moves/move-attrs/move-attr.ts
  src/data/moves/move-attrs/psycho-shift-effect-attr.ts
  src/data/moves/move-attrs/stat-stage-change-attr.ts
  src/data/moves/move-attrs/status-effect-attr.ts
  src/data/moves/move-attrs/telekinesis-attr.ts
  src/data/moves/move-conditions/shell-trap-condition.ts
  src/data/moves/move.ts
  src/field/pokemon.ts
  test/ai/move-effect-scores/agility.test.ts
  test/ai/move-effect-scores/belly-drum.test.ts
  test/ai/move-effect-scores/charm.test.ts
  test/ai/move-effect-scores/defog.test.ts
  test/ai/move-effect-scores/iron-defense.test.ts
  test/ai/move-effect-scores/scary-face.test.ts
  test/ai/move-effect-scores/screech.test.ts
  test/ai/move-effect-scores/strength-sap.test.ts
  test/ai/move-effect-scores/swords-dance.test.ts
Labels: AI, Addendum

#1341 ai-rework: Move ability- and move-revealing test utils to `FieldHelper`
  test/ai/move-condition-scores/counter.test.ts
  test/ai/move-condition-scores/upper-hand.test.ts
  test/ai/move-effect-scores/ability-change.test.ts
  test/ai/move-effect-scores/ability-copy.test.ts
  test/ai/move-effect-scores/ability-give.test.ts
  test/ai/move-effect-scores/belly-drum.test.ts
  test/ai/move-effect-scores/charm.test.ts
  test/ai/move-effect-scores/conditional-protect.test.ts
  test/ai/move-effect-scores/drain-punch.test.ts
  test/ai/move-effect-scores/heal-block.test.ts
  test/ai/move-effect-scores/magnet-rise.test.ts
  test/ai/move-effect-scores/powder.test.ts
  test/ai/move-effect-scores/psycho-shift.test.ts
  test/ai/move-effect-scores/scary-face.test.ts
  test/ai/move-effect-scores/screech.test.ts
  test/ai/move-effect-scores/strength-sap.test.ts
  test/ai/move-effect-scores/suppress-abilities.test.ts
  test/ai/move-effect-scores/switch-abilities.test.ts
  test/test-utils/enemy-command-utils.ts
  test/test-utils/helpers/field-helper.ts
Labels: AI, Tests, Addendum

#1340 ai-rework: Add Effect Scores for misc. stat-modifying attributes
  src/data/moves/move-attrs/acupressure-stat-stage-change-attr.ts
  src/data/moves/move-attrs/average-stats-attr.ts
  src/data/moves/move-attrs/copy-stats-attr.ts
  src/data/moves/move-attrs/invert-stats-attr.ts
  src/data/moves/move-attrs/order-up-stat-boost-attr.ts
  src/data/moves/move-attrs/post-victory-stat-stage-change-attr.ts
  src/data/moves/move-attrs/reset-stats-attr.ts
  src/data/moves/move-attrs/shift-stat-attr.ts
  src/data/moves/move-attrs/steal-positive-stats-attr.ts
  src/data/moves/move-attrs/swap-stat-attr.ts
  src/data/moves/move-attrs/swap-stat-stages-attr.ts
  src/data/moves/move.ts
  test/ai/move-effect-scores/acupressure.test.ts
  test/ai/move-effect-scores/average-stats.test.ts
  test/ai/move-effect-scores/clear-smog.test.ts
  test/ai/move-effect-scores/fell-stinger.test.ts
  test/ai/move-effect-scores/haze.test.ts
  test/ai/move-effect-scores/psych-up.test.ts
  test/ai/move-effect-scores/spectral-thief.test.ts
  test/ai/move-effect-scores/speed-swap.test.ts
  test/ai/move-effect-scores/swap-stat-stages.test.ts
  test/ai/move-effect-scores/topsy-turvy.test.ts
Labels: AI, Addendum

#1343 dev: remove unused packages/functions/etc
  .dependency-cruiser.cjs
  package.json
  pnpm-lock.yaml
  src/@types/settings.ts
  src/@types/starter-data.ts
  src/battle.ts
  src/constants/move-constants.ts
  src/data/abilities/ab-attrs/post-damage-force-switch-ab-attr.ts
  src/data/abilities/ab-attrs/post-turn-heal-ab-attr.ts
  src/data/abilities/ab-attrs/post-weather-lapse-ab-attr.ts
  src/data/berry.ts
  src/data/biome-utils.ts
  src/data/daily-run.ts
  src/data/dialogue.ts
  src/data/pokemon-evolutions.ts
  src/data/pokemon-evolutions/enemy-pokemon-evolution-levels.ts
  src/data/pokemon-evolutions/gen8-pokemon-family-evolutions.ts
  src/data/pokemon-forms.ts
  src/data/starter-colors.ts
  src/data/terrain.ts
  src/data/trainer-config.ts
  src/modifier/modifier-type.ts
  src/phases/pokemon-heal-phase.ts
  src/phases/stat-stage-change-phase.ts
  src/plugins/api/api.ts
  src/system/game-data.ts
  src/system/settings/default-settings.ts
  src/system/voucher.ts
  src/ui/components/arena-flyout.ts
  src/ui/components/daily-run-scoreboard.ts
  src/ui/components/move-info-overlay.ts
  src/ui/handlers/save-slot-select-ui-handler.ts
  src/ui/handlers/target-select-ui-handler.ts
  src/utils/color-utils.ts
  src/utils/common-utils.ts
  src/utils/debug-utils.ts
  src/utils/inputs-utils.ts
  src/utils/string-utils.ts
  test/test-utils/phase-interceptor.ts
  test/test-utils/test-utils.ts
Labels: Development
