Repository Despair-Games/poketernity, pull requests merged in 2025-07, with the labels that each got.

#1279 [Dev] Fix issues with `pnpm` and `lefthook`
  lefthook.yml
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  scripts/dependency-graph.js
Labels: Dependencies, Development

#1280 Review suggestions for PR1236
  src/data/abilities/ab-attrs/post-damage-force-switch-ab-attr.ts
  src/data/arena-tags/tailwind-tag.ts
  src/data/moves/move-attrs/force-switch-out-attr.ts
  src/field/pokemon.ts
  src/phase-manager.ts
  src/phases/check-switch-phase.ts
  src/phases/recall-phase.ts
  src/phases/revival-blessing-phase.ts
  src/phases/summon-phase.ts
  src/phases/switch-phase.ts
  src/utils/anim-utils.ts
Labels: Addendum

#1284 [P2] Fix Disable reversing the target's move history on condition check
  src/data/battler-tags/move-restriction-battler-tag.ts
  src/data/init/init-moves.ts
  src/field/pokemon.ts
  test/moves/disable.test.ts
Labels: Move, P2

#1267 [Refactor] Put optional params of `Pokemon#getEffectiveStat` in object
  src/data/abilities/ab-attrs/download-ab-attr.ts
  src/data/battler-tags/confused-tag.ts
  src/data/battler-tags/highest-stat-boost-tag.ts
  src/data/init/init-abilities.ts
  src/data/moves/move-attrs/tera-move-category-attr.ts
  src/data/moves/move-attrs/use-higher-attacking-stat-attr.ts
  src/data/moves/move.ts
  src/field/pokemon.ts
  test/abilities/unaware.test.ts
  test/test-utils/matchers/to-have-effective-stat-matcher.ts
Labels: Refactor

#1282 [Refactor] Replace `.fill().map` "loops" with real `for` loops
  src/animations.ts
  src/data/mystery-encounters/encounters/training-session-encounter.ts
  src/enums/voucher-type.ts
  src/field/arena.ts
  src/field/pokemon.ts
  src/modifier/modifier-type.ts
  src/ui/components/iv-graph.ts
  src/ui/handlers/egg-gacha-ui-handler.ts
  src/ui/handlers/starter-select-ui-handler.ts
Labels: Refactor

#1291 [Refactor] Remove unnecessary `arena` params
  src/@types/move-types.ts
  src/battle-scene.ts
  src/data/arena-tags/arena-room-tag.ts
  src/data/arena-tags/arena-tag.ts
  src/data/arena-tags/aurora-veil-tag.ts
  src/data/arena-tags/conditional-protect-tag.ts
  src/data/arena-tags/crafty-shield-tag.ts
  src/data/arena-tags/delayed-attack-tag.ts
  src/data/arena-tags/entry-hazard-tag.ts
  src/data/arena-tags/fairy-lock-tag.ts
  src/data/arena-tags/fire-grass-pledge-tag.ts
  src/data/arena-tags/grass-water-pledge-tag.ts
  src/data/arena-tags/gravity-tag.ts
  src/data/arena-tags/happy-hour-tag.ts
  src/data/arena-tags/ion-deluge-tag.ts
  src/data/arena-tags/light-screen-tag.ts
  src/data/arena-tags/mat-block-tag.ts
  src/data/arena-tags/mist-tag.ts
  src/data/arena-tags/mud-sport-tag.ts
  src/data/arena-tags/no-crit-tag.ts
  src/data/arena-tags/pending-heal-tag.ts
  src/data/arena-tags/quick-guard-tag.ts
  src/data/arena-tags/reflect-tag.ts
  src/data/arena-tags/safeguard-tag.ts
  src/data/arena-tags/spikes-tag.ts
  src/data/arena-tags/sticky-web-tag.ts
  src/data/arena-tags/tailwind-tag.ts
  src/data/arena-tags/toxic-spikes-tag.ts
  src/data/arena-tags/trick-room-tag.ts
  src/data/arena-tags/type-hazard-tag.ts
  src/data/arena-tags/type-immune-damage-over-time-tag.ts
  src/data/arena-tags/water-fire-pledge-tag.ts
  src/data/arena-tags/water-sport-tag.ts
  src/data/arena-tags/weaken-move-screen-tag.ts
  src/data/arena-tags/weaken-move-type-tag.ts
  src/data/arena-tags/wide-guard-tag.ts
  src/data/arena-tags/wish-tag.ts
  src/data/mystery-encounters/utils/encounter-phase-utils.ts
  src/field/arena.ts
  src/game-mode.ts
  src/phases/title-phase.ts
  test/game-modes/game-mode.test.ts
Labels: Refactor

#1296 [Dev] `test:silent` now passes `--silent='passed-only'` to Vitest
  package.json
Labels: Tests, Development

#1252 [Refactor] Change unsuppressable/etc `AbAttr`s into flags
  src/data/abilities/ab-attrs/copy-fainted-ally-ability-ab-attr.ts
  src/data/abilities/ab-attrs/no-transform-ability-ab-attr.ts
  src/data/abilities/ab-attrs/post-defend-ability-give-ab-attr.ts
  src/data/abilities/ab-attrs/post-defend-ability-swap-ab-attr.ts
  src/data/abilities/ab-attrs/post-summon-ab-attr.ts
  src/data/abilities/ab-attrs/post-summon-copy-ability-ab-attr.ts
  src/data/abilities/ab-attrs/suppress-field-abilities-ab-attr.ts
  src/data/abilities/ab-attrs/uncopiable-ability-ab-attr.ts
  src/data/abilities/ab-attrs/unsuppressable-ability-ab-attr.ts
  src/data/abilities/ab-attrs/unswappable-ability-ab-attr.ts
  src/data/abilities/ability.ts
  src/data/init/init-abilities.ts
  src/data/moves/move-attrs/ability-change-attr.ts
  src/data/moves/move-attrs/ability-copy-attr.ts
  src/data/moves/move-attrs/ability-give-attr.ts
  src/data/moves/move-attrs/suppress-abilities-attr.ts
  src/data/moves/move-attrs/switch-abilities-attr.ts
  src/enums/ab-attr-flag.ts
  src/field/pokemon.ts
  test/abilities/flower-gift.test.ts
  test/abilities/forecast.test.ts
  test/abilities/neutralizing-gas.test.ts
  test/moves/doodle.test.ts
  test/moves/entrainment.test.ts
  test/moves/role-play.test.ts
  test/moves/simple-beam.test.ts
  test/moves/skill-swap.test.ts
Labels: Ability, Refactor

#1286 [Refactor] Remove `PhaseManager.queueMovePhase`
  src/data/abilities/ab-attrs/post-dancing-move-ab-attr.ts
  src/data/moves/move-attrs/call-move-attr.ts
  src/data/moves/move-attrs/repeat-move-attr.ts
  src/data/mystery-encounters/utils/encounter-phase-utils.ts
  src/phase-manager.ts
  src/phases/move-charge-phase.ts
  src/phases/move-phase.ts
  src/turn-command-manager.ts
Labels: Refactor

#1290 [Refactor] Rename `Arena#applyTagsForSide` to `Arena#applyTags`
  src/data/arena-tags/arena-tag.ts
  src/data/moves/move-attrs/chance-based-move-effect-attr.ts
  src/data/moves/move-attrs/flinch-attr.ts
  src/data/moves/move.ts
  src/field/arena.ts
  src/field/pokemon.ts
  src/phases/base/hit-check-phase.ts
  src/phases/post-summon-phase.ts
  src/phases/stat-stage-change-phase.ts
  src/turn-command-manager.ts
Labels: Refactor

#1304 [Refactor] Add type safety to `Arena#applyTags`
  src/data/arena-tags/mist-tag.ts
  src/data/moves/move-attrs/chance-based-move-effect-attr.ts
  src/data/moves/move-attrs/flinch-attr.ts
  src/data/moves/move.ts
  src/field/arena.ts
  src/field/pokemon.ts
  src/phases/base/hit-check-phase.ts
  src/phases/post-summon-phase.ts
  src/phases/stat-stage-change-phase.ts
  src/turn-command-manager.ts
Labels: Refactor

#1297 [Refactor] Refactor inputs controller and (input) config handler
  src/@types/inputs-types.ts
  src/@types/settings.ts
  src/battle-scene.ts
  src/configs/inputs/cfg-keyboard-qwerty.ts
  src/configs/inputs/config-handler.ts
  src/configs/inputs/pad-dualshock.ts
  src/configs/inputs/pad-generic.ts
  src/configs/inputs/pad-procon.ts
  src/configs/inputs/pad-unlicensed-snes.ts
  src/configs/inputs/pad-xbox360.ts
  src/enums/keyboard-layout.ts
  src/inputs/gamepad-configs.ts
  src/inputs/inputs-controller.ts
  src/inputs/keyboard-configs.ts
  src/inputs/ui-inputs.ts
  src/system/game-data.ts
  src/system/settings/default-settings.ts
  src/system/settings/settings-manager.ts
  src/ui/handlers/starter-select-ui-handler.ts
  src/ui/settings/controls-settings-ui-handler.ts
  src/ui/settings/gamepad-binding-ui-handler.ts
  src/ui/settings/gamepad-settings-ui-handler.ts
  src/ui/settings/keyboard-binding-ui-handler.ts
  src/ui/settings/keyboard-settings-ui-handler.ts
  src/ui/settings/navigation-menu.ts
  src/ui/settings/settings-ui-handler.ts
  src/ui/ui.ts
  src/utils/inputs-utils.ts
  test/inputs/inputs.test.ts
  test/settings/helpers/in-game-manip.ts
  test/settings/helpers/menu-manip.ts
  test/settings/keyboard-layout.test.ts
  test/settings/rebinding-setting.test.ts
  test/test-utils/inputs-handler.ts
  tsconfig.json
Labels: Refactor
