Repository Despair-Games/poketernity, pull requests merged in 2025-09, with the labels that each got.

#1345 misc: remove obsolete daily scoreboard functionality
  src/@types/api-types.ts
  src/enums/scoreboard-category.ts
  src/plugins/api/daily-api.ts
  test/plugins/api/daily-api.test.ts
Labels: Miscellaneous

#1349 misc: rename `HalfSacrificialAttr` to `HalfMaxHpRecoilAttr`
  src/data/init/init-moves.ts
  src/data/moves/move-attrs/half-max-hp-recoil-attr.ts
Labels: Miscellaneous

#1346 ai-rework: Add Effect Scores for self-damaging move effects
  src/constants/ability-constants.ts
  src/constants/ai-constants.ts
  src/data/moves/move-attrs/add-substitute-attr.ts
  src/data/moves/move-attrs/cut-hp-stat-stage-boost-attr.ts
  src/data/moves/move-attrs/half-sacrificial-attr.ts
  src/data/moves/move-attrs/recoil-attr.ts
  src/data/moves/move-attrs/remove-type-attr.ts
  src/data/moves/move-attrs/sacrificial-attr.ts
  src/data/moves/move-attrs/sacrificial-full-restore-attr.ts
  src/data/moves/move.ts
  src/field/enemy-pokemon.ts
  src/field/pokemon.ts
  test/ai/move-effect-scores/brave-bird.test.ts
  test/ai/move-effect-scores/burn-up.test.ts
  test/ai/move-effect-scores/explosion.test.ts
  test/ai/move-effect-scores/mind-blown.test.ts
  test/ai/move-effect-scores/sacrificial-full-restore.test.ts
  test/ai/move-effect-scores/substitute.test.ts
Labels: AI, Addendum

#1353 refactor: replace `x !== nil ? x : y` with `x ?? y`
  src/data/moves/move-attrs/multi-hit-attr.ts
  src/data/pokemon-form.ts
  src/field/enemy-pokemon.ts
  src/field/pokemon.ts
  src/plugins/api/api-base.ts
  test/test-utils/helpers/move-helper.ts
Labels: Refactor

#1328 refactor: convert `CustomPokemonData` to an `interface`
  src/@types/pokemon-types.ts
  src/data/custom-pokemon-data.ts
  src/data/mystery-encounters/encounters/clowning-around-encounter.ts
  src/data/mystery-encounters/encounters/slumbering-snorlax-encounter.ts
  src/data/mystery-encounters/encounters/the-strong-stuff-encounter.ts
  src/data/mystery-encounters/encounters/weird-dream-encounter.ts
  src/data/mystery-encounters/utils/encounter-phase-utils.ts
  src/data/mystery-encounters/utils/encounter-pokemon-utils.ts
  src/field/pokemon.ts
  src/system/pokemon-data.ts
  test/mystery-encounter/encounters/clowning-around-encounter.test.ts
  test/mystery-encounter/encounters/the-strong-stuff-encounter.test.ts
  test/mystery-encounter/encounters/weird-dream-encounter.test.ts
Labels: Refactor

#1351 ai-rework: Add Effect Scores for Terrain- and Weather-changing effects
  src/constants/ability-constants.ts
  src/constants/move-constants.ts
  src/data/init/init-moves.ts
  src/data/moves/move-attrs/change-terrain-attr.ts
  src/data/moves/move-attrs/change-weather-attr.ts
  src/data/moves/move-attrs/clear-terrain-attr.ts
  src/data/moves/move-attrs/clear-weather-attr.ts
  src/data/moves/move-attrs/terrain-change-attr.ts
  src/data/moves/move-attrs/weather-change-attr.ts
  src/data/moves/move.ts
  src/data/terrain.ts
  src/data/weather.ts
  src/field/arena.ts
  src/field/enemy-pokemon.ts
  src/field/pokemon.ts
  src/phases/move-phase.ts
  src/phases/weather-effect-phase.ts
  src/pipelines/field-sprite.ts
  src/utils/terrain-utils.ts
  src/utils/weather-utils.ts
  test/ai/move-effect-scores/defog.test.ts
  test/ai/move-effect-scores/electric-terrain.test.ts
  test/ai/move-effect-scores/grassy-terrain.test.ts
  test/ai/move-effect-scores/misty-terrain.test.ts
  test/ai/move-effect-scores/psychic-terrain.test.ts
  test/ai/move-effect-scores/rain-dance.test.ts
  test/ai/move-effect-scores/sandstorm.test.ts
  test/ai/move-effect-scores/snowscape.test.ts
  test/ai/move-effect-scores/sunny-day.test.ts
Labels: AI, Addendum

#1358 ai-rework: Update Effect Score calculation for charge moves
  src/data/moves/charge-move.ts
  src/data/moves/move-attrs/instant-charge-attr.ts
  src/data/moves/move-attrs/semi-invulnerable-attr.ts
  src/data/moves/move-attrs/sky-drop-attr.ts
  test/ai/move-effect-scores/sky-drop.test.ts
  test/ai/move-effect-scores/solar-beam.test.ts
Labels: AI, Addendum

#1360 refactor: add getter for weather type to `Arena`
  src/data/abilities/ab-attrs/post-faint-clear-weather-ab-attr.ts
  src/data/abilities/ab-attrs/post-weather-change-form-change-ab-attr.ts
  src/data/abilities/ab-attrs/post-weather-lapse-ab-attr.ts
  src/data/abilities/ab-attrs/post-weather-lapse-damage-ab-attr.ts
  src/data/abilities/ab-attrs/post-weather-lapse-heal-ab-attr.ts
  src/data/abilities/ab-attrs/pre-switch-out-clear-weather-ab-attr.ts
  src/data/abilities/ab-attrs/terrain-event-type-change-ab-attr.ts
  src/data/init/init-moves.ts
  src/data/moves/move-attrs/copy-biome-type-attr.ts
  src/data/moves/move-attrs/nature-power-attr.ts
  src/data/moves/move-attrs/secret-power-attr.ts
  src/data/moves/move-attrs/terrain-pulse-type-attr.ts
  src/data/moves/move-attrs/thunder-accuracy-attr.ts
  src/data/moves/move-attrs/weather-ball-type-attr.ts
  src/data/moves/move-attrs/weather-heal-attr.ts
  src/data/mystery-encounters/mystery-encounter-requirements.ts
  src/data/terrain.ts
  src/data/weather.ts
  src/field/arena.ts
  src/field/pokemon.ts
  src/phases/move-phase.ts
  src/phases/turn-end-phase.ts
  src/phases/weather-effect-phase.ts
  src/pipelines/field-sprite.ts
  test/abilities/sand-spit.test.ts
  test/arena/strong-winds.test.ts
  test/moves/chilly-reception.test.ts
  test/moves/grassy-glide.test.ts
  test/test-utils/matchers/to-have-terrain-matcher.ts
  test/test-utils/matchers/to-have-weather-matcher.ts
Labels: Refactor

#1368 fix(ui): Fix battle info texture name for boss pokemon
  src/ui/components/battle-info.ts
Labels: P3, UI/UX

#1362 ai-rework: Add Effect Scores for type-modifying moves
  src/data/init/init-moves.ts
  src/data/moves/move-attrs/add-type-attr.ts
  src/data/moves/move-attrs/change-type-attr.ts
  src/data/moves/move-attrs/copy-biome-type-attr.ts
  src/data/moves/move-attrs/copy-type-attr.ts
  src/data/moves/move-attrs/first-move-type-attr.ts
  src/data/moves/move-attrs/resist-last-move-type-attr.ts
  src/data/moves/move-attrs/set-type-attr.ts
  test/ai/move-effect-scores/conversion.test.ts
  test/ai/move-effect-scores/forests-curse.test.ts
  test/ai/move-effect-scores/reflect-type.test.ts
  test/ai/move-effect-scores/sky-drop.test.ts
  test/ai/move-effect-scores/soak.test.ts
  test/test-utils/helpers/field-helper.ts
Labels: AI, Addendum

#1369 feat(ability): fully implement Victory Star
  src/data/abilities/ab-attrs/accuracy-multiplier-ab-attr.ts
  src/data/abilities/ab-attrs/effective-stat-multiplier-ab-attr.ts
  src/data/abilities/ab-attrs/evasiveness-multiplier-ab-attr.ts
  src/data/abilities/ab-attrs/field-accuracy-multiplier-ab-attr.ts
  src/data/abilities/ab-attrs/field-multiply-stat-ab-attr.ts
  src/data/abilities/ab-attrs/field-stat-multiplier-ab-attr.ts
  src/data/abilities/ab-attrs/low-hp-move-type-attack-multiplier-ab-attr.ts
  src/data/abilities/ab-attrs/treasure-of-ruin-ab-attr.ts
  src/data/abilities/ab-attrs/weather-based-speed-doubler-ab-attr.ts
  src/data/init/init-abilities.ts
  src/enums/ab-attr-flag.ts
  src/field/pokemon.ts
  src/phases/base/hit-check-phase.ts
  test/abilities/sand-veil.test.ts
  test/abilities/treasures-of-ruin.test.ts
  test/abilities/victory-star.test.ts
Labels: Ability

#1370 refactor: reorganize `Arena` class, simplify Hydro Steam
  src/audio-manager.ts
  src/battle-scene.ts
  src/data/init/init-moves.ts
  src/data/moves/move-attrs/ignore-weather-type-debuff-attr.ts
  src/data/mystery-encounters/encounters/the-expert-pokemon-breeder-encounter.ts
  src/field/arena.ts
  src/field/pokemon.ts
  src/phases/title-phase.ts
  test/moves/hydro-steam.test.ts
Labels: Refactor
