Repository Despair-Games/poketernity, pull requests merged in 2025-05, with the labels that each got.

#1084 [AI][Balance] Enemy AI trainers will now tera
  src/data/trainer-config.ts
  src/data/trainer-configs/champion-trainer-configs.ts
  src/data/trainer-configs/evil-boss-trainer-configs.ts
Labels: Balance, AI

#1095 [Refactor] Rename SeedTag to SeededTag
  src/data/battler-tags/seeded-tag.ts
  src/data/battler-tags/utils/get-battler-tag.ts
Labels: Refactor

#1103 [Refactor] Remove deprecated `nextCommandPhaseQueue` and deferred phase scheduling
  src/data/abilities/ab-attrs/heal-from-berry-use-ab-attr.ts
  src/data/abilities/ab-attrs/post-summon-ally-heal-ab-attr.ts
  src/data/abilities/ab-attrs/post-turn-heal-ab-attr.ts
  src/data/abilities/ab-attrs/post-turn-status-heal-ab-attr.ts
  src/data/abilities/ab-attrs/post-weather-lapse-heal-ab-attr.ts
  src/data/abilities/ab-attrs/type-immunity-heal-ab-attr.ts
  src/data/arena-tag.ts
  src/data/battler-tags/aqua-ring-tag.ts
  src/data/battler-tags/ingrain-tag.ts
  src/data/battler-tags/seeded-tag.ts
  src/data/berry.ts
  src/data/moves/move-attrs/heal-attr.ts
  src/data/moves/move-attrs/hit-heal-attr.ts
  src/data/moves/move-attrs/present-power-attr.ts
  src/modifier/modifier.ts
  src/phase-manager.ts
  src/phases/quiet-form-change-phase.ts
  src/phases/turn-end-phase.ts
Labels: Refactor

#1102 [Test] Fix a flaky Download test
  test/abilities/download.test.ts
Labels: Tests

#1074 [Refactor] Consolidate arena tag functions
  src/battle.ts
  src/data/abilities/ab-attrs/post-defend-apply-entry-hazard-tag-ab-attr.ts
  src/data/abilities/ab-attrs/post-summon-stat-stage-change-on-arena-ab-attr.ts
  src/data/init/init-abilities.ts
  src/data/init/init-moves.ts
  src/data/moves/move-attrs/add-arena-tag-attr.ts
  src/data/moves/move-attrs/add-entry-hazard-tag-attr.ts
  src/data/moves/move-attrs/delayed-attack-attr.ts
  src/data/moves/move-attrs/sacrificial-full-restore-attr.ts
  src/data/moves/move-attrs/swap-arena-tags-attr.ts
  src/data/moves/move-conditions/fail-on-gravity-condition.ts
  src/data/moves/move.ts
  src/field/arena.ts
  src/field/pokemon.ts
  src/field/trainer.ts
  src/phases/command-phase.ts
  src/phases/money-reward-phase.ts
  src/ui/components/arena-flyout.ts
  test/abilities/good-as-gold.test.ts
  test/abilities/magic-bounce.test.ts
  test/abilities/screen-cleaner.test.ts
  test/arena/arena-gravity.test.ts
  test/moves/brick-break.test.ts
  test/moves/ceaseless-edge.test.ts
  test/moves/court-change.test.ts
  test/moves/defog.test.ts
  test/moves/destiny-bond.test.ts
  test/moves/fairy-lock.test.ts
  test/moves/future-sight.test.ts
  test/moves/heal-block.test.ts
  test/moves/healing-wish-lunar-dance.test.ts
  test/moves/magic-coat.test.ts
  test/moves/pledge-moves.test.ts
  test/moves/protect.test.ts
  test/moves/rapid-spin.test.ts
  test/moves/secret-power.test.ts
  test/moves/substitute.test.ts
  test/moves/tailwind.test.ts
  test/moves/tidy-up.test.ts
  test/moves/toxic-spikes.test.ts
  test/moves/trick-room.test.ts
Labels: Refactor

#1105 [Beta] Nemona has proper tera
  src/data/trainer-config.ts
  src/data/trainer-configs/champion-trainer-configs.ts
Labels: P2, Refactor, Beta

#1108 [Dev][Refactor] Reduce api noise
  .env
  .env.beta
  .env.development
  .env.production
  .env.test
  src/plugins/api/api-base.ts
  src/plugins/api/api.ts
  src/vite.env.d.ts
  test/plugins/api/api.test.ts
Labels: Refactor, Development

#1075 [Misc] Add exp formula for gens 1-7
  src/battle.ts
  src/data/exp.ts
  src/data/pokemon-species-form.ts
  src/field/pokemon.ts
Labels: Miscellaneous

#1118 [Misc] Fix ME `build()` functions
  src/data/mystery-encounters/mystery-encounter-option.ts
  src/data/mystery-encounters/mystery-encounter.ts
Labels: Miscellaneous

#1090 [Refactor] Add and implement `coerceArray` utility function
  src/data/abilities/ab-attrs/flinch-stat-stage-change-ab-attr.ts
  src/data/abilities/ab-attrs/pre-apply-battler-tag-immunnity-ab-attr.ts
  src/data/battler-tags/battler-tag.ts
  src/data/battler-tags/utils/apply-battler-tags.ts
  src/data/init/init-encounter-anims.ts
  src/data/mystery-encounters/mystery-encounter-requirements.ts
  src/data/mystery-encounters/mystery-encounter.ts
  src/data/mystery-encounters/requirements/can-learn-move-requirement.ts
  src/data/mystery-encounters/utils/encounter-phase-utils.ts
  src/data/species-form-change-triggers/species-form-change-status-effect-trigger.ts
  src/data/trainer-config.ts
  src/field/arena.ts
  src/field/pokemon-sprite-tera-sparkle-handler.ts
  src/field/pokemon.ts
  src/plugins/cache-busted-loader-plugin.ts
  src/scene-base.ts
  src/ui/helpers/pokemon-icon-anim-helper.ts
  src/utils/common-utils.ts
  test/test-utils/helpers/moveHelper.ts
  test/test-utils/helpers/overridesHelper.ts
Labels: Refactor

#1111 [Balance] Add custom team templates for gym leaders 6-8
  src/data/trainer-config.ts
  src/field/trainer.ts
Labels: Balance, Refactor

#1122 [Dev] Fix merge conflict in trainer.ts and trainer-config.ts
  src/data/trainer-config.ts
  src/field/trainer.ts
Labels: Beta

#1119 [Refactor] Make UI's handler list private
  src/@types/InputsEvent.ts
  src/@types/TouchControlsEvent.ts
  src/data/mystery-encounters/utils/encounter-pokemon-utils.ts
  src/event-bus.ts
  src/inputs-controller.ts
  src/phases/attempt-capture-phase.ts
  src/phases/command-phase.ts
  src/phases/learn-move-phase.ts
  src/ui/handlers/command-ui-handler.ts
  src/ui/handlers/summary-ui-handler.ts
  src/ui/settings/gamepad-settings-ui-handler.ts
  src/ui/settings/keyboard-settings-ui-handler.ts
  src/ui/ui.ts
  test/mystery-encounter/encounter-test-utils.ts
  test/mystery-encounter/encounters/berries-abound-encounter.test.ts
  test/mystery-encounter/encounters/bug-type-superfan-encounter.test.ts
  test/mystery-encounter/encounters/clowning-around-encounter.test.ts
  test/mystery-encounter/encounters/dancing-lessons-encounter.test.ts
  test/mystery-encounter/encounters/delibirdy-encounter.test.ts
  test/mystery-encounter/encounters/department-store-sale-encounter.test.ts
  test/mystery-encounter/encounters/field-trip-encounter.test.ts
  test/mystery-encounter/encounters/fight-or-flight-encounter.test.ts
  test/mystery-encounter/encounters/fun-and-games-encounter.test.ts
  test/mystery-encounter/encounters/global-trade-system-encounter.test.ts
  test/mystery-encounter/encounters/mysterious-challengers-encounter.test.ts
  test/mystery-encounter/encounters/part-timer-encounter.test.ts
  test/mystery-encounter/encounters/teleporting-hijinks-encounter.test.ts
  test/mystery-encounter/encounters/the-strong-stuff-encounter.test.ts
  test/mystery-encounter/encounters/the-winstrate-challenge-encounter.test.ts
  test/mystery-encounter/encounters/trash-to-treasure-encounter.test.ts
  test/mystery-encounter/encounters/weird-dream-encounter.test.ts
  test/phases/select-modifier-phase.test.ts
Labels: Refactor

#1127 [Bug] The form change message now correctly displays the Pokemon's previous form
  src/phases/form-change-phase.ts
Labels: P3

#1100 [Refactor] Delete `PokemonSpeciesForm.isObtainable()`
  src/data/egg.ts
  src/data/mystery-encounters/utils/encounter-pokemon-utils.ts
  src/data/pokemon-species-form.ts
  src/data/pokemon-species.ts
  src/field/pokemon.ts
  src/phases/attempt-capture-phase.ts
  src/ui/handlers/starter-select-ui-handler.ts
  test/eggs/egg.test.ts
Labels: Refactor

#1107 [Refactor] Add `SpeciesFormChange#is[Mega|Primal|Max]`
  src/data/pokemon-forms.ts
  src/field/pokemon.ts
Labels: Refactor, Localization

#1129 [Test] Update some egg tests, fix broken Manaphy egg test
  test/eggs/egg.test.ts
Labels: Tests

#1113 [Refactor] Consolidate `try/catch` for sprites in one place
  src/data/mystery-encounters/encounters/global-trade-system-encounter.ts
  src/data/mystery-encounters/utils/encounter-transformation-sequence.ts
  src/field/pokemon.ts
  src/phaser-extensions.ts
  src/phases/abstract-form-change-base-phase.ts
  src/phases/egg-hatch-phase.ts
  src/phases/evolution-phase.ts
  src/phases/form-change-phase.ts
  src/phases/quiet-form-change-phase.ts
  src/ui/handlers/summary-ui-handler.ts
Labels: Refactor

#1079 [Refactor] Rewrite Battle Animation config interfaces
  src/data/animations/anim-config-schema.ts
  src/data/animations/anim-config.ts
  src/data/animations/battle-anims.ts
  src/data/animations/charge-anims.ts
  src/data/animations/common-anims.ts
  src/data/animations/common-battle-anim.ts
  src/data/animations/ease-functions.ts
  src/data/animations/encounter-anims.ts
  src/data/animations/encounter-battle-anim.ts
  src/data/animations/move-anim.ts
  src/data/animations/move-anims.ts
  src/data/animations/move-charge-anim.ts
  src/data/init/init-anims.ts
  src/data/init/init-common-anims.ts
  src/data/init/init-encounter-anims.ts
  src/data/init/init-move-anim.ts
  src/data/init/init-move-charge-anim.ts
  src/enums/anim-timed-event-type.ts
  src/utils/anim-utils.ts
  test/animations/anim-config-schema.test.ts
Labels: Refactor, Art / Graphics

#1123 [Bug] Fix gym leader party generation
  src/data/trainer-config.ts
Labels: P2, Miscellaneous

#1133 [Dev] Move script files into `scripts/` directory
  package.json
  scripts/create-test-boilerplate.js
  scripts/dependency-graph.js
  scripts/update_exp_sprites.ps1
Labels: Refactor, Development

#1130 [Refactor] Initialize `waveData` and `turnData` in constructor
  src/data/abilities/apply-ab-attrs.ts
  src/data/berry.ts
  src/data/init/init-abilities.ts
  src/data/moves/move-attrs/last-move-double-power-attr.ts
  src/data/moves/move-attrs/round-power-attr.ts
  src/field/pokemon.ts
  src/phases/faint-phase.ts
  src/phases/move-effect-phase.ts
  src/phases/stat-stage-change-phase.ts
  src/turn-command-manager.ts
Labels: Refactor

#1126 [Balance] Change exp formula to gen 1-4
  src/battle-scene.ts
  src/data/exp.ts
  src/phases/post-knockout-phase.ts
Labels: Balance

#1139 [Dev] Update `compilerOptions.target` to `ES2022` from `ES2020`
  package-lock.json
  package.json
  tsconfig.json
Labels: Development

#1125 [Addendum][AI-Rework][Test] Add matchers + Improve test utils
  src/data/moves/move-attrs/flinch-attr.ts
  src/data/moves/move-attrs/secret-power-attr.ts
  src/field/pokemon.ts
  test/@types/vitest.d.ts
  test/ai/enemy-command.test.ts
  test/ai/low-accuracy.test.ts
  test/ai/priority.test.ts
  test/ai/utils/enemy-command-utils.ts
  test/matchers.setup.ts
  test/moves/fusion-flare-bolt.test.ts
  test/test-utils/matchers/to-never-select-move-matcher.ts
  test/test-utils/matchers/to-prefer-selecting-move-matcher.ts
Labels: AI, Tests, Addendum

#1138 [Bug] Fix parsing of local save data
  src/system/game-data.ts
Labels: P1, Save Data

#1132 [Refactor] Change `Status` from class to interface
  src/@types/Status.ts
  src/constants/game-constants.ts
  src/data/abilities/ab-attrs/reduce-sleep-duration-ab-attr.ts
  src/data/mystery-encounters/utils/encounter-phase-utils.ts
  src/data/mystery-encounters/utils/encounter-pokemon-utils.ts
  src/data/status-effect.ts
  src/field/enemy-pokemon.ts
  src/field/player-pokemon.ts
  src/field/pokemon.ts
  src/modifier/init-modifier-pools.ts
  src/modifier/modifier-type.ts
  src/phases/move-phase.ts
  src/phases/obtain-status-effect-phase.ts
  src/phases/pokemon-heal-phase.ts
  src/phases/post-summon-phase.ts
  src/phases/post-turn-status-effect-phase.ts
  src/system/pokemon-data.ts
  test/abilities/early-bird.test.ts
  test/abilities/magic-bounce.test.ts
  test/abilities/magic-guard.test.ts
  test/battle/reload.test.ts
  test/data/status_effect.test.ts
  test/items/toxic-orb.test.ts
  test/moves/magic-coat.test.ts
  test/moves/purify.test.ts
  test/moves/toxic.test.ts
  test/mystery-encounter/encounters/fiery-fallout-encounter.test.ts
Labels: Refactor

#1150 [Bug] Court Change no longer fails if the enemy is semi-invul
  src/data/init/init-moves.ts
  test/moves/court-change.test.ts
Labels: Move, P2, Tests

#1140 [Dev] Enable some `strict` options in `tsconfig.json`
  src/inputs-controller.ts
  src/system/game-speed.ts
  tsconfig.json
Labels: Development

#834 [AI-Rework] Add effect scores for ability-changing effects
  src/constants/ability-constants.ts
  src/constants/ai-constants.ts
  src/data/moves/move-attrs/ability-change-attr.ts
  src/data/moves/move-attrs/ability-copy-attr.ts
  src/data/moves/move-attrs/ability-give-attr.ts
  src/data/moves/move-attrs/suppress-abilities-attr.ts
  src/data/moves/move-attrs/switch-abilities-attr.ts
  src/data/moves/move.ts
  src/field/enemy-pokemon.ts
  src/field/pokemon.ts
  test/ai/move-effect-scores/ability-change.test.ts
  test/ai/move-effect-scores/ability-copy.test.ts
  test/ai/move-effect-scores/ability-give.test.ts
  test/ai/move-effect-scores/suppress-abilities.test.ts
  test/ai/move-effect-scores/switch-abilities.test.ts
  test/ai/utils/enemy-command-utils.ts
  test/test-utils/matchers/to-prefer-selecting-move-matcher.ts
Labels: AI, Addendum

#1147 [Refactor] Remove selfEffect from `chance-based-move-effect-attr.getMoveChance`
  src/data/moves/move-attrs/add-battler-tag-attr.ts
  src/data/moves/move-attrs/chance-based-move-effect-attr.ts
  src/data/moves/move-attrs/flinch-attr.ts
  src/data/moves/move-attrs/multi-status-effect-attr.ts
  src/data/moves/move-attrs/secret-power-attr.ts
  src/data/moves/move-attrs/status-effect-attr.ts
Labels: Move, Refactor

#1160 [UI][P3] Fix option select cursor misalignement when scrolling down
  src/ui/handlers/base-option-select-ui-handler.ts
Labels: P3, UI/UX

#1163 [Bug][Move] Fix firstTarget calculation when a target was fainted by a spread move
  src/phases/move-effect-phase.ts
  test/moves/make-it-rain.test.ts
Labels: Move, P2

#1153 [Dev] Add a `FORCE_ENEMY_TERA_OVERRIDE`
  src/field/pokemon.ts
  src/overrides.ts
  src/phases/enemy-command-phase.ts
  test/moves/tera-blast.test.ts
  test/test-utils/helpers/overridesHelper.ts
Labels: Development

#1152 [Bug] Fix timing of Terastallization phase
  src/enums/battle-command.ts
  src/phases/terastallization-phase.ts
  src/turn-command-manager.ts
Labels: P2, Refactor, Battle

#1159 [Dev] Add `VITE_MODIFIERS_DEBUG` var in `.env` files
  .env
  .env.beta
  .env.development
  .env.production
  .env.test
  src/battle-scene.ts
  src/loggers.ts
  src/modifier/modifier-type.ts
  src/vite.env.d.ts
  test/items/light-ball.test.ts
  test/items/metal-powder.test.ts
  test/items/quick-powder.test.ts
  test/items/thick-club.test.ts
Labels: Development

#1167 [P2] Protect's condition now considers full move history
  src/data/moves/move-attrs/protect-attr.ts
  test/moves/protect.test.ts
Labels: Move, P2

#1158 [AI-Rework] Add effect scores for arena-tag-based moves
  src/@types/ProtectConditionFunc.ts
  src/constants/ability-constants.ts
  src/constants/move-constants.ts
  src/data/arena-tag.ts
  src/data/init/init-moves.ts
  src/data/moves/move-attrs/add-arena-tag-attr.ts
  src/data/moves/move-attrs/add-entry-hazard-tag-attr.ts
  src/data/moves/move-attrs/add-pledge-effect-attr.ts
  src/data/moves/move-attrs/conditional-protect-attr.ts
  src/data/moves/move-attrs/fairy-lock-attr.ts
  src/data/moves/move-attrs/gravity-attr.ts
  src/data/moves/move-attrs/happy-hour-attr.ts
  src/data/moves/move-attrs/ion-deluge-attr.ts
  src/data/moves/move-attrs/mist-attr.ts
  src/data/moves/move-attrs/screen-attr.ts
  src/data/moves/move-attrs/tailwind-attr.ts
  src/data/moves/move-attrs/trick-room-attr.ts
  src/data/moves/move-attrs/type-immune-damage-over-time-attr.ts
  src/data/moves/move-attrs/weaken-move-type-attr.ts
  src/data/moves/move-attrs/wish-attr.ts
  src/data/moves/move.ts
  src/field/enemy-pokemon.ts
  src/field/pokemon.ts
  test/ai/enemy-command.test.ts
  test/ai/low-accuracy.test.ts
  test/ai/move-effect-scores/ability-change.test.ts
  test/ai/move-effect-scores/ability-copy.test.ts
  test/ai/move-effect-scores/ability-give.test.ts
  test/ai/move-effect-scores/conditional-protect.test.ts
  test/ai/move-effect-scores/gravity.test.ts
  test/ai/move-effect-scores/hazards.test.ts
  test/ai/move-effect-scores/ion-deluge.test.ts
  test/ai/move-effect-scores/mist.test.ts
  test/ai/move-effect-scores/screens.test.ts
  test/ai/move-effect-scores/suppress-abilities.test.ts
  test/ai/move-effect-scores/switch-abilities.test.ts
  test/ai/move-effect-scores/tailwind.test.ts
  test/ai/move-effect-scores/trick-room.test.ts
  test/ai/move-effect-scores/weaken-move-type.test.ts
  test/ai/move-effect-scores/wish.test.ts
  test/ai/priority.test.ts
  test/test-utils/enemy-command-utils.ts
  test/test-utils/matchers/to-never-select-move-matcher.ts
  test/test-utils/matchers/to-prefer-selecting-move-matcher.ts
Labels: AI, Addendum

#1148 [Checkup][Ability] Tangled feet
  src/battle-scene.ts
  src/constants/ability-constants.ts
  src/constants/battler-tag-constants.ts
  src/constants/game-constants.ts
  src/data/abilities/ab-attrs/heal-from-berry-use-ab-attr.ts
  src/data/abilities/ab-attrs/post-turn-loot-ab-attr.ts
  src/data/egg.ts
  src/data/trainer-config.ts
  src/field/pokemon.ts
  src/modifier/modifier-type.ts
  src/phases/attempt-run-phase.ts
  src/system/pokemon-data.ts
  src/ui/components/battle-info.ts
  src/ui/handlers/run-info-ui-handler.ts
  src/utils/common-utils.ts
  test/abilities/steadfast.test.ts
  test/abilities/tangled-feet.test.ts
  test/abilities/wonder-skin.test.ts
  test/test-utils/helpers/move-helper.ts
  test/test-utils/test-utils.ts
  test/utils/common-utils.test.ts
Labels: Ability, Checkup

#1161 [Save Data] Move unlocked natures and IVs from DexData to StarterData
  src/@types/DexData.ts
  src/@types/StarterData.ts
  src/constants/game-constants.ts
  src/data/challenge.ts
  src/data/egg-hatch-data.ts
  src/phases/scan-ivs-phase.ts
  src/phases/select-starter-phase.ts
  src/system/game-data.ts
  src/ui/components/pokemon-info-container.ts
  src/ui/handlers/battle-message-ui-handler.ts
  src/ui/handlers/starter-select-ui-handler.ts
  test/system/dex-data.test.ts
  test/system/set-pokemon-caught.test.ts
  test/system/update-species-ivs.test.ts
  test/test-utils/game-manager-utils.ts
  test/ui/starter-select.test.ts
Labels: Refactor, Save Data

#1179 [Dev] Add player IV override and player + enemy Nature override
  src/battle-scene.ts
  src/overrides.ts
  test/abilities/wimp-out.test.ts
  test/test-utils/helpers/classic-mode-helper.ts
  test/test-utils/helpers/overrides-helper.ts
Labels: Tests, Development

#1168 [Balance] Change Rival1's team from levels 10/9 to 5/5
  src/data/trainer-config.ts
  src/field/trainer.ts
Labels: Balance

#1174 [Bug] Prevent `min > max` in `clamp` function
  src/system/pokemon-data.ts
  src/utils/common-utils.ts
  test/utils/common-utils.test.ts
Labels: P2, Miscellaneous

#1178 [Refactor] Break up `arena-tag.ts` into separate files
  src/@types/ProtectConditionFunc.ts
  src/data/abilities/ab-attrs/post-defend-apply-entry-hazard-tag-ab-attr.ts
  src/data/arena-tag.ts
  src/data/arena-tags/arena-room-tag.ts
  src/data/arena-tags/arena-tag.ts
  src/data/arena-tags/aurora-veil-tag.ts
  src/data/arena-tags/conditional-protect-tag.ts
  src/data/arena-tags/crafty-shield-tag.ts
  src/data/arena-tags/delayed-attack-tag.ts
  src/data/arena-tags/entry-hazard-tag.ts
  src/data/arena-tags/fairy-lock-tag.ts
  src/data/arena-tags/fire-grass-pledge-tag.ts
  src/data/arena-tags/grass-water-pledge-tag.ts
  src/data/arena-tags/gravity-tag.ts
  src/data/arena-tags/happy-hour-tag.ts
  src/data/arena-tags/ion-deluge-tag.ts
  src/data/arena-tags/light-screen-tag.ts
  src/data/arena-tags/mat-block-tag.ts
  src/data/arena-tags/mist-tag.ts
  src/data/arena-tags/mud-sport-tag.ts
  src/data/arena-tags/no-crit-tag.ts
  src/data/arena-tags/pending-heal-tag.ts
  src/data/arena-tags/quick-guard-tag.ts
  src/data/arena-tags/reflect-tag.ts
  src/data/arena-tags/safeguard-tag.ts
  src/data/arena-tags/sharp-steel-tag.ts
  src/data/arena-tags/spikes-tag.ts
  src/data/arena-tags/stealth-rock-tag.ts
  src/data/arena-tags/sticky-web-tag.ts
  src/data/arena-tags/tailwind-tag.ts
  src/data/arena-tags/toxic-spikes-tag.ts
  src/data/arena-tags/trick-room-tag.ts
  src/data/arena-tags/type-hazard-tag.ts
  src/data/arena-tags/type-immune-damage-over-time-tag.ts
  src/data/arena-tags/utils/get-arena-tag.ts
  src/data/arena-tags/utils/load-arena-tag.ts
  src/data/arena-tags/water-fire-pledge-tag.ts
  src/data/arena-tags/water-sport-tag.ts
  src/data/arena-tags/weaken-move-screen-tag.ts
  src/data/arena-tags/weaken-move-type-tag.ts
  src/data/arena-tags/wide-guard-tag.ts
  src/data/arena-tags/wish-tag.ts
  src/data/moves/move-attrs/add-entry-hazard-tag-attr.ts
  src/data/moves/move-attrs/delayed-attack-attr.ts
  src/data/moves/move-attrs/sacrificial-full-restore-attr.ts
  src/enums/arena-tag-type.ts
  src/field/arena.ts
  src/field/trainer.ts
  src/phases/command-phase.ts
  src/system/arena-data.ts
  src/system/game-data.ts
  src/ui/components/arena-flyout.ts
  test/moves/ceaseless-edge.test.ts
  test/moves/destiny-bond.test.ts
  test/moves/protect.test.ts
  test/moves/toxic-spikes.test.ts
  tsconfig.json
Labels: Refactor

#1181 [Dev][GH] Merge lint workflows into one workflow file
  .github/workflows/biome.yml
  .github/workflows/dependencies.yml
  .github/workflows/eslint.yml
  .github/workflows/lint.yml
Labels: GitHub, Development

#1193 [Dev] Enable `lint/suspicious/noPrototypeBuiltins` Biome rule
  biome.jsonc
  src/battle-scene.ts
  src/data/challenge.ts
  src/data/egg.ts
  src/data/init/init-anims.ts
  src/data/mystery-encounters/encounters/the-expert-pokemon-breeder-encounter.ts
  src/data/mystery-encounters/mystery-encounter-requirements.ts
  src/data/mystery-encounters/utils/encounter-phase-utils.ts
  src/data/pokemon-species-form.ts
  src/data/pokemon-species.ts
  src/data/trainer-configs/rival-trainer-configs.ts
  src/field/pokemon.ts
  src/field/trainer.ts
  src/game-mode.ts
  src/modifier/modifier-type.ts
  src/modifier/modifier.ts
  src/phases/select-biome-phase.ts
  src/phases/title-phase.ts
  src/phases/trainer-victory-phase.ts
  src/system/game-data.ts
  src/system/pokemon-data.ts
  src/system/trainer-data.ts
  src/touch-controls.ts
  src/ui-inputs.ts
  src/ui/components/pokemon-hatch-info-container.ts
  src/ui/handlers/achievements-ui-handler.ts
  src/ui/handlers/base-option-select-ui-handler.ts
  src/ui/handlers/modal-ui-handler.ts
  src/ui/handlers/party-ui-handler.ts
  src/ui/handlers/starter-select-ui-handler.ts
  src/ui/handlers/summary-ui-handler.ts
  src/ui/ui-theme.ts
  src/utils/common-utils.ts
  test/sprites/pokemon-sprite.test.ts
  test/test-utils/mocks/mock-local-storage.ts
  tsconfig.json
Labels: Development

#1172 [Checkup][Ability] Marvel Scale
  src/constants/game-constants.ts
  src/data/abilities/ab-attrs/post-summon-user-field-remove-status-effect-ab-attr.ts
  src/data/abilities/ab-attrs/post-turn-reset-status-ab-attr.ts
  src/data/abilities/ab-attrs/pre-set-status-effect-immunity-ab-attr.ts
  src/data/abilities/ab-attrs/stat-multiplier-ab-attr.ts
  src/data/battler-tags/psycho-shift-tag.ts
  src/data/berry.ts
  src/data/init/init-abilities.ts
  src/data/init/init-moves.ts
  src/data/moves/move-attrs/heal-status-effect-attr.ts
  src/data/mystery-encounters/utils/encounter-pokemon-utils.ts
  src/field/pokemon.ts
  src/phases/attempt-capture-phase.ts
  src/phases/move-phase.ts
  src/phases/obtain-status-effect-phase.ts
  src/phases/pokemon-heal-phase.ts
  src/phases/post-turn-status-effect-phase.ts
  src/utils/status-effect-utils.ts
  test/abilities/magic-guard.test.ts
  test/abilities/marvel-scale.test.ts
  test/data/status-effect.test.ts
Labels: Ability, Checkup

#1199 [Docs] Add TSDocs to TypeScript enum utility functions
  src/battle-scene.ts
  src/data/animations/anim-config-schema.ts
  src/data/animations/battle-anims.ts
  src/data/egg-moves.ts
  src/data/init/init-anims.ts
  src/data/init/init-common-anims.ts
  src/data/init/init-encounter-anims.ts
  src/data/moves/move-attrs/metronome-attr.ts
  src/enums/anim-frame-target.ts
  src/field/arena.ts
  src/field/pokemon.ts
  src/inputs-controller.ts
  src/loading-scene.ts
  src/modifier/init-modifier-types.ts
  src/modifier/modifier-type.ts
  src/system/game-data.ts
  src/ui/components/daily-run-scoreboard.ts
  src/ui/handlers/egg-gacha-ui-handler.ts
  src/ui/handlers/menu-ui-handler.ts
  src/ui/handlers/summary-ui-handler.ts
  src/ui/settings/settings-ui-items.ts
  src/utils/common-utils.ts
  src/utils/move-utils.ts
  test/abilities/solar-power.test.ts
Labels: Documentation, Development

#1203 [UI][P2] Fix achievements screen scrolling behavior
  src/ui/handlers/achievements-ui-handler.ts
Labels: P2, UI/UX

#1195 [UI][Refactor][P3] Add mode attribute to Starter Select
  src/ui/handlers/starter-select-ui-handler.ts
Labels: P3, Refactor, UI/UX

#1196 [Save Data] Merge Starter Data's passive and ability attributes
  src/@types/starter-data.ts
  src/data/dex-attributes.ts
  src/data/egg-hatch-data.ts
  src/enums/passive.ts
  src/system/game-data.ts
  src/ui/handlers/starter-select-ui-handler.ts
  test/system/dex-data.test.ts
  test/test-utils/resources/saves/empty-save.pkty.txt
  test/test-utils/resources/saves/everything.pkty.txt
Labels: Save Data

#1202 [Refactor] Clean up `RunHistoryUiHandler#processInput`
  src/ui/handlers/run-history-ui-handler.ts
  src/ui/handlers/ui-handler.ts
Labels: Refactor, UI/UX

#1218 [Dev] Biome Lint: remove `.` from `biome-ci` script
  package.json
Labels: Development

#1212 [P2] Axe Kick guarantees a min of 3 turns of confusion when it procs
  src/data/battler-tags/confused-tag.ts
  src/data/init/init-moves.ts
  src/data/moves/move-attrs/confuse-attr.ts
Labels: Move, P2

#1223 [Dev] Add tag-based deployment
  .github/workflows/deploy-tag.yml
  package.json
Labels: Development

#1180 [Checkup][Ability] Guts
  src/data/abilities/ab-attrs/stat-multiplier-ab-attr.ts
  test/abilities/guts.test.ts
Labels: Ability, Checkup

#1177 [Save Data] Clean up shiny variants and passive attributes in system data
  src/@types/starter-data.ts
  src/account.ts
  src/constants/app-constants.ts
  src/data/dex-attributes.ts
  src/data/egg-hatch-data.ts
  src/enums/game-data-type.ts
  src/enums/passive.ts
  src/field/pokemon.ts
  src/system/game-data.ts
  src/ui/components/battle-info.ts
  src/ui/components/hatched-pokemon-container.ts
  src/ui/components/pokemon-info-container.ts
  src/ui/handlers/game-stats-ui-handler.ts
  src/ui/handlers/login-form-ui-handler.ts
  src/ui/handlers/menu-ui-handler.ts
  src/ui/handlers/save-slot-select-ui-handler.ts
  src/ui/handlers/starter-select-ui-handler.ts
  src/ui/settings/move-touch-controls-handler.ts
  test/system/dex-data.test.ts
  test/system/set-pokemon-caught.test.ts
  test/test-utils/resources/saves/empty-save.pkty.txt
  test/test-utils/resources/saves/everything.pkty.txt
  test/ui/starter-select.test.ts
Labels: Save Data

#1194 [Refactor] Replace `enum`s with `const` objects (part 1)
  src/@types/fight-command.ts
  src/battle-scene.ts
  src/constants/arena-tag-constants.ts
  src/constants/battler-tag-constants.ts
  src/data/abilities/ab-attrs/post-item-lost-apply-battler-tag-ab-attr.ts
  src/data/animations/anim-config-schema.ts
  src/data/biome-utils.ts
  src/data/init/init-anims.ts
  src/data/init/init-moves.ts
  src/data/moves/move-attrs/force-switch-out-attr.ts
  src/data/moves/move-attrs/swap-arena-tags-attr.ts
  src/data/mystery-encounters/utils/encounter-phase-utils.ts
  src/enums/ab-attr-flag.ts
  src/enums/ability-apply-mode.ts
  src/enums/achv-category.ts
  src/enums/achv-tier.ts
  src/enums/admin-mode.ts
  src/enums/ai-type.ts
  src/enums/anim-blend-type.ts
  src/enums/anim-focus.ts
  src/enums/anim-frame-target.ts
  src/enums/anim-timed-event-type.ts
  src/enums/arena-event-type.ts
  src/enums/arena-tag-relative-side.ts
  src/enums/arena-tag-side.ts
  src/enums/arena-tag-type.ts
  src/enums/battle-command.ts
  src/enums/battle-scene-event-type.ts
  src/enums/battle-style.ts
  src/enums/battle-type.ts
  src/enums/battler-tag-lapse-type.ts
  src/enums/battler-tag-type.ts
  src/enums/berry-type.ts
  src/enums/biome-id.ts
  src/enums/biome-pool-tier.ts
  src/enums/button.ts
  src/enums/challenge-type.ts
  src/field/arena.ts
  src/field/pokemon.ts
  src/loading-scene.ts
  src/modifier/init-modifier-types.ts
  src/modifier/modifier-type.ts
  src/modifier/modifier.ts
  src/phases/command-phase.ts
  src/phases/encounter-phase.ts
  src/phases/faint-phase.ts
  src/phases/mystery-encounter-phases/battle-start-cleanup-phase.ts
  src/phases/summon-phase.ts
  src/ui/components/arena-flyout.ts
  src/ui/handlers/command-ui-handler.ts
  src/utils/berry-utils.ts
  src/utils/challenge-utils.ts
  src/utils/common-utils.ts
  test/test-utils/helpers/overrides-helper.ts
  test/test-utils/helpers/settings-helper.ts
  test/test-utils/matchers/to-have-battler-tag-type-matcher.ts
Labels: Refactor
