Repository Despair-Games/poketernity, pull requests merged in 2025-03, with the labels that each got.

#723 [Bug] Fixed how the Arena Flyout handles transitions from Terrain/Weather to none
  src/data/ab-attrs/post-weather-lapse-damage-ab-attr.ts
  src/data/init-abilities.ts
  src/field/arena.ts
  src/system/game-data.ts
  src/ui/arena-flyout.ts
Labels: P3 Bug

#773 [Balance] Fix elite four aces
  src/data/balance/signatureSpecies.ts
  src/data/trainer-config.ts
Labels: Balance

#767 [Bug] Fix wild Pokemon not picking a random evolution species
  src/data/balance/pokemon-evolutions.ts
  src/data/daily-run.ts
  src/data/mystery-encounters/encounters/berries-abound-encounter.ts
  src/data/mystery-encounters/encounters/fight-or-flight-encounter.ts
  src/data/mystery-encounters/encounters/safari-zone-encounter.ts
  src/data/mystery-encounters/encounters/teleporting-hijinks-encounter.ts
  src/data/mystery-encounters/encounters/uncommon-breed-encounter.ts
  src/data/mystery-encounters/utils/encounter-pokemon-utils.ts
  src/data/pokemon-species.ts
  src/data/trainer-config.ts
  src/field/arena.ts
  src/field/trainer.ts
  test/pokemon/evolution.test.ts
Labels: P2 Bug, Balance, Beta

#782 [Misc] `getPokemonSpecies()` no longer accepts `undefined`
  src/utils/pokemon-species-utils.ts
  test/mystery-encounter/encounters/uncommon-breed-encounter.test.ts
Labels: Miscellaneous

#775 [Refactor] Removed a vast majority of achievements + unused 'score' property
  src/battle-scene.ts
  src/data/mystery-encounters/encounters/weird-dream-encounter.ts
  src/data/mystery-encounters/utils/encounter-pokemon-utils.ts
  src/enums/achv-category.ts
  src/field/pokemon.ts
  src/loading-scene.ts
  src/modifier/modifier.ts
  src/phases/attempt-capture-phase.ts
  src/phases/egg-hatch-phase.ts
  src/phases/egg-lapse-phase.ts
  src/phases/encounter-phase.ts
  src/phases/form-change-phase.ts
  src/phases/game-over-phase.ts
  src/phases/level-up-phase.ts
  src/phases/move-effect-phase.ts
  src/phases/pokemon-heal-phase.ts
  src/phases/trainer-victory-phase.ts
  src/system/achievements.ts
  src/system/achv.ts
  src/system/game-data.ts
  src/system/init-vouchers.ts
  src/ui/achv-bar.ts
  src/ui/achvs-ui-handler.ts
  test/achievements/achievement.test.ts
  test/phases/game-over-phase.test.ts
  test/testUtils/testFileInitialization.ts
Labels: Refactor

#761 [Refactor] Refactor Pokemon-evolutions into seperate files, (gen 1)
  src/battle-scene.ts
  src/data/balance/biomes.ts
  src/data/balance/pokemon-evolutions/enemy-pokemon-evolution-levels.ts
  src/data/balance/pokemon-evolutions/gen1-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/init-pokemon-evolutions.ts
  src/data/balance/trainer-configs/rival-trainer-configs.ts
  src/data/challenge.ts
  src/data/egg.ts
  src/data/mystery-encounters/mystery-encounter-requirements.ts
  src/data/pokemon-evolutions.ts
  src/data/pokemon-pre-evolutions.ts
  src/data/pokemon-species-form.ts
  src/data/pokemon-species.ts
  src/field/pokemon.ts
  src/field/trainer.ts
  src/loading-scene.ts
  src/modifier/init-modifier-pools.ts
  src/modifier/modifier-type.ts
  src/modifier/modifier.ts
  src/phases/evolution-phase.ts
  src/phases/game-over-phase.ts
  src/system/achievements.ts
  src/system/game-data.ts
  src/ui/party-ui-handler.ts
  src/ui/starter-select-ui-handler.ts
  test/pokemon/evolution.test.ts
  test/testUtils/testFileInitialization.ts
Labels: Balance, Refactor

#771 [P1] Fix consecutive-use moves infinitely queueing failing moves
  src/data/battler-tags.ts
  src/field/pokemon.ts
  src/phases/command-phase.ts
  test/moves/thrash.test.ts
Labels: Move, P1 Bug

#709 [Move][Checkup] Reimplement Imprison
  src/data/arena-tag.ts
  src/data/battler-tags.ts
  src/data/init-moves.ts
  src/data/move-attrs/add-battler-tag-attr.ts
  src/enums/arena-tag-type.ts
  src/enums/battler-tag-type.ts
  src/field/pokemon.ts
  src/phases/command-phase.ts
  src/phases/move-phase.ts
  src/phases/select-target-phase.ts
  src/utils/arena-tag-type-utils.ts
  test/abilities/aroma_veil.test.ts
  test/moves/imprison.test.ts
Labels: Move, P2 Bug, Refactor, Checkup

#712 [P2] Ignore non starter selectable forms in dex data + other fixes to game data updates when catching a Pokemon
  src/data/balance/starters.ts
  src/data/init-species.ts
  src/data/mystery-encounters/encounters/global-trade-system-encounter.ts
  src/data/mystery-encounters/encounters/weird-dream-encounter.ts
  src/data/mystery-encounters/utils/encounter-pokemon-utils.ts
  src/data/no-starter-form-keys.ts
  src/data/pokemon-form.ts
  src/field/pokemon.ts
  src/phases/evolution-phase.ts
  src/system/game-data.ts
  src/ui/pokemon-info-container.ts
  test/system/dex_data.test.ts
  test/system/set_pokemon_caught.test.ts
  test/ui/starter-select.test.ts
Labels: P2 Bug

#790 [P1][Beta] Fix egg summary not getting egg hatch data
  src/phases/egg-lapse-phase.ts
Labels: P1 Bug, Beta

#789 [Refactor] Break gens 7-9 evolutions into their own files
  src/data/balance/pokemon-evolutions/enemy-pokemon-evolution-levels.ts
  src/data/balance/pokemon-evolutions/gen1-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen6-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen7-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen8-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen9-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/init-pokemon-evolutions.ts
Labels: Balance, Refactor

#787 [Refactor] Break gens 2-9 evolutions into their own files
  src/data/balance/pokemon-evolutions/enemy-pokemon-evolution-levels.ts
  src/data/balance/pokemon-evolutions/gen1-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen2-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen3-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen4-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen5-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen6-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen7-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen8-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen9-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/init-pokemon-evolutions.ts
Labels: Balance, Refactor

#788 [Bug] Several fixes for learning moves upon changing forms
  src/constants.ts
  src/data/balance/pokemon-form-level-moves.ts
  src/data/balance/pokemon-level-moves.ts
  src/data/pokemon-forms.ts
  src/phases/form-change-phase.ts
  src/phases/learn-move-phase.ts
  test/data/moveset-data.test.ts
  test/phases/form-change-phase.test.ts
Labels: Enhancement, P1 Bug, P2 Bug, Item

#796 [Misc] Add some pre-defined imports to `overrides.ts`
  src/overrides.ts
Labels: Miscellaneous

#757 [Misc] Delete stale pokemon objects in `BattleEndPhase`
  src/phases/battle-end-phase.ts
  test/battle/battle.test.ts
  test/testUtils/gameManager.ts
  test/testUtils/phaseInterceptor.ts
Labels: Miscellaneous

#798 [Refactor] Remove enforce func in evolution condition
  src/data/balance/pokemon-evolutions/gen3-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen4-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen5-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen6-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen7-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen9-pokemon-family-evolutions.ts
  src/data/pokemon-evolutions.ts
  src/field/pokemon.ts
Labels: Refactor

#804 [P3] Sky Drop and Present no longer display critical hit message when they don't do damage
  src/field/damage-number-handler.ts
  src/phases/move-effect-phase.ts
Labels: Move, P3 Bug

#800 [Documentation] Add example to ITEM_REWARD_OVERRIDE
  src/overrides.ts
Labels: Documentation

#802 [Beta][P2] Breaking a shield against a g-max depletes the entire segment now
  src/field/pokemon.ts
Labels: P2 Bug, Beta

#736 [Balance] Change OHKO acc formula, go to bosses' next unbroken bar
  src/data/init-moves.ts
  src/data/move-attrs/one-hit-ko-accuracy-attr.ts
  src/data/move-attrs/one-hit-ko-attr.ts
  src/data/move-attrs/sheer-cold-accuracy-attr.ts
  src/field/pokemon.ts
  test/data/all_moves.json
  test/data/all_moves.test.ts
  test/moves/fissure.test.ts
  test/moves/ohko.test.ts
Labels: Move, Balance

#794 [Balance] Keep leftover friendship when receiving candy
  src/@types/StarterData.ts
  src/data/balance/starters.ts
  src/data/egg-hatch-data.ts
  src/field/pokemon.ts
  src/system/game-data.ts
  src/ui/starter-select-ui-handler.ts
  src/ui/summary-ui-handler.ts
  test/events/candy-friendship-event.test.ts
  test/system/dex_data.test.ts
Labels: Balance, Refactor

#758 [Bug] Using Trick Room will now cancel an active Trick Room
  src/data/arena-tag.ts
  test/moves/trick_room.test.ts
Labels: Move, P2 Bug

#814 [Misc] `StatsContainer.updateIvs()` now has proper param typing
  src/ui/starter-select-ui-handler.ts
  src/ui/stats-container.ts
Labels: Miscellaneous

#813 [Misc] Remove unused `target` and `move` params from anonymous function in `IncrementMovePriorityAttr`
  src/data/init-moves.ts
  src/data/move-attrs/increment-move-priority-attr.ts
  src/data/move.ts
  test/moves/grassy_glide.test.ts
Labels: Miscellaneous

#463 [AI-Rework] Add Move Attribute scoring parameters under `MoveAttrOptions`
  src/data/move-attrs/chance-based-move-effect-attr.ts
  src/data/move-attrs/move-attr.ts
  src/data/move-attrs/move-effect-attr.ts
  src/data/move.ts
  src/field/pokemon.ts
Labels: AI

#808 [Refactor][UI] Refactor Text Style
  src/battle-scene.ts
  src/data/nature.ts
  src/enums/color.ts
  src/enums/font-style.ts
  src/enums/text-style.ts
  src/loading-scene.ts
  src/modifier/modifier-type.ts
  src/modifier/modifier.ts
  src/phases/end-card-phase.ts
  src/plugins/i18n.ts
  src/system/settings/supported-languages.ts
  src/ui-constants.ts
  src/ui/ability-bar.ts
  src/ui/abstract-option-select-ui-handler.ts
  src/ui/achv-bar.ts
  src/ui/achvs-ui-handler.ts
  src/ui/arena-flyout.ts
  src/ui/ball-ui-handler.ts
  src/ui/battle-flyout.ts
  src/ui/battle-message-ui-handler.ts
  src/ui/bgm-bar.ts
  src/ui/challenges-select-ui-handler.ts
  src/ui/command-ui-handler.ts
  src/ui/daily-run-scoreboard.ts
  src/ui/egg-counter-container.ts
  src/ui/egg-gacha-ui-handler.ts
  src/ui/egg-list-ui-handler.ts
  src/ui/font-style.ts
  src/ui/form-change-scene-handler.ts
  src/ui/form-modal-ui-handler.ts
  src/ui/game-stats-ui-handler.ts
  src/ui/interfaces/font-style-options.ts
  src/ui/interfaces/text-style-options.ts
  src/ui/modifier-select-ui-handler.ts
  src/ui/move-info-overlay.ts
  src/ui/mystery-encounter-ui-handler.ts
  src/ui/pokemon-hatch-info-container.ts
  src/ui/pokemon-info-container.ts
  src/ui/registration-form-ui-handler.ts
  src/ui/run-history-ui-handler.ts
  src/ui/run-info-ui-handler.ts
  src/ui/save-slot-select-ui-handler.ts
  src/ui/session-reload-modal-ui-handler.ts
  src/ui/settings/abstract-settings-ui-handler.ts
  src/ui/starter-container.ts
  src/ui/starter-select-ui-handler.ts
  src/ui/stats-container.ts
  src/ui/summary-ui-handler.ts
  src/ui/text-color.ts
  src/ui/text-style.ts
  src/ui/text.ts
  src/ui/title-ui-handler.ts
  src/ui/ui.ts
  src/ui/unavailable-modal-ui-handler.ts
  src/utils.ts
Labels: Refactor, UI/UX

#797 [P2] Lightning Rod and Storm Drain now redirect based on a move's final type
  src/data/abilities/ab-attrs/redirect-move-ab-attr.ts
  src/data/abilities/ab-attrs/redirect-type-move-ab-attr.ts
  src/phases/move-phase.ts
  test/abilities/lightning_rod.test.ts
Labels: Ability, P2 Bug

#756 [Refactor] Simplify some `if`/`else` blocks in ME requirements code
  src/data/mystery-encounters/mystery-encounter-requirements.ts
Labels: Refactor

#819 [Refactor] Replace evo conditions with an array
  src/data/balance/pokemon-evolutions/gen1-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen2-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen3-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen4-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen5-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen6-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen7-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen8-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen9-pokemon-family-evolutions.ts
  src/data/mystery-encounters/mystery-encounter-requirements.ts
  src/data/pokemon-evolutions.ts
  src/field/pokemon.ts
  src/modifier/modifier-type.ts
  src/modifier/modifier.ts
Labels: Refactor

#827 [P3][UI] Fix the transfer item text being misplaced in the shop
  src/ui/modifier-select-ui-handler.ts
Labels: P3 Bug, UI/UX, Beta

#702 [Move] Fully Implement Rollout and Ice Ball
  src/data/battler-tags.ts
  src/data/init/init-moves.ts
  src/data/moves/move-attrs/add-battler-tag-attr.ts
  src/data/moves/move-attrs/consecutive-use-double-power-attr.ts
  src/data/moves/move-attrs/consecutive-use-power-multiplier-attr.ts
  src/data/moves/move-attrs/rolling-power-multiplier-attr.ts
  src/enums/battler-tag-type.ts
  src/utils/battler-tag-type-utils.ts
  test/moves/rollout.test.ts
Labels: Move

#835 [Refactor] Add `readonly` to TextColorCombination
  src/ui/interfaces/text-color-combination.ts
Labels: Refactor

#836 [Audio] Implement critical catch sfx from Gen 5
  public/audio/se/crit_throw.wav
  src/loading-scene.ts
  src/phases/attempt-capture-phase.ts
Labels: Audio

#837 [Refactor] Broke apart gender evo condition, added comments, added amped evo condition
  src/data/balance/pokemon-evolutions/gen3-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen4-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen5-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen6-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen7-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen8-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen9-pokemon-family-evolutions.ts
  src/data/pokemon-evolutions.ts
Labels: Documentation, Refactor

#844 [Test] Remove deprecated `forceEnemyMove` and update its usages
  test/abilities/commander.test.ts
  test/abilities/effect-spore.test.ts
  test/abilities/friend-guard.test.ts
  test/abilities/gorilla-tactics.test.ts
  test/abilities/gulp-missile.test.ts
  test/abilities/mimicry.test.ts
  test/abilities/post-defend-contact-apply-status.test.ts
  test/abilities/stakeout.test.ts
  test/abilities/stench.test.ts
  test/abilities/unburden.test.ts
  test/moves/chilly-reception.test.ts
  test/moves/dragon-darts.test.ts
  test/moves/dragon-tail.test.ts
  test/moves/encore.test.ts
  test/moves/fairy-lock.test.ts
  test/moves/flame-burst.test.ts
  test/moves/fly.test.ts
  test/moves/follow-me.test.ts
  test/moves/future-sight.test.ts
  test/moves/grudge.test.ts
  test/moves/instruct.test.ts
  test/moves/metal-burst.test.ts
  test/moves/mirror-move.test.ts
  test/moves/plasma-fists.test.ts
  test/moves/powder.test.ts
  test/moves/rage-powder.test.ts
  test/moves/reflect-type.test.ts
  test/moves/revival-blessing.test.ts
  test/moves/secret-power.test.ts
  test/moves/sky-drop.test.ts
  test/moves/spotlight.test.ts
  test/moves/taunt.test.ts
  test/moves/telekinesis.test.ts
  test/moves/torment.test.ts
  test/test-utils/gameManager.ts
  test/test-utils/helpers/moveHelper.ts
Labels: Tests

#842 [Test] Move `selectTarget` from `gameManager` to `moveHelper`
  test/abilities/moxie.test.ts
  test/test-utils/gameManager.ts
  test/test-utils/helpers/moveHelper.ts
Labels: Tests

#851 [Misc] Fix Vite warning when running tests
  test/vitest.setup.ts
Labels: Miscellaneous

#752 [Misc] Reformat `src/data/init/init-moves.ts`
  eslint.config.js
  src/data/init/init-moves.ts
Labels: Miscellaneous

#750 [Move][Ability] Implement Magic Coat and Magic Bounce
  src/battle-scene.ts
  src/data/abilities/ab-attrs/reflect-moves-ab-attr.ts
  src/data/battler-tags.ts
  src/data/init/init-abilities.ts
  src/data/init/init-moves.ts
  src/data/moves/move-attrs/add-battler-tag-attr.ts
  src/data/moves/move-attrs/encore-attr.ts
  src/data/moves/move-attrs/repeat-move-attr.ts
  src/data/moves/move.ts
  src/enums/ab-attr-flag.ts
  src/enums/battler-tag-type.ts
  src/enums/move-flags.ts
  src/field/pokemon.ts
  src/phases/move-effect-phase.ts
  src/phases/move-phase.ts
  test/abilities/magic-bounce.test.ts
  test/data/all-moves.json
  test/data/all-moves.test.ts
  test/moves/magic-coat.test.ts
  test/moves/uproar.test.ts
Labels: Ability, Move

#839 [BUG] Fix Locked Reroll not using Luck Score
  src/modifier/modifier-type.ts
Labels: P2 Bug

#856 [P3][Ui] Fix couple Text Style issues
  src/enums/text-style.ts
  src/ui/components/move-info-overlay.ts
  src/ui/handlers/message-ui-handler.ts
  src/ui/text/text-style.ts
Labels: P3 Bug, UI/UX

#859 [Test] Add helper for mocking a pokemon's ability
  test/abilities/arena-trap.test.ts
  test/abilities/forecast.test.ts
  test/abilities/friend-guard.test.ts
  test/abilities/lightning-rod.test.ts
  test/abilities/magic-bounce.test.ts
  test/abilities/mirror-armor.test.ts
  test/abilities/sand-veil.test.ts
  test/abilities/steely-spirit.test.ts
  test/moves/flame-burst.test.ts
  test/moves/magic-coat.test.ts
  test/moves/pledge-moves.test.ts
  test/test-utils/gameManager.ts
  test/test-utils/helpers/fieldHelper.ts
Labels: Tests

#753 [Refactor] Update damage and heal functions in the `Pokemon` class
  src/@types/DamageFunctionOptions.ts
  src/data/abilities/ab-attrs/form-block-damage-ab-attr.ts
  src/data/abilities/ab-attrs/post-defend-contact-damage-ab-attr.ts
  src/data/abilities/ab-attrs/post-faint-contact-damage-ab-attr.ts
  src/data/abilities/ab-attrs/post-faint-hp-damage-ab-attr.ts
  src/data/abilities/ab-attrs/post-turn-hurt-if-sleeping-ab-attr.ts
  src/data/abilities/ab-attrs/post-weather-lapse-damage-ab-attr.ts
  src/data/abilities/ab-attrs/received-move-damage-multiplier-ab-attr.ts
  src/data/arena-tag.ts
  src/data/battler-tags.ts
  src/data/moves/move-attrs/add-substitute-attr.ts
  src/data/moves/move-attrs/curse-attr.ts
  src/data/moves/move-attrs/cut-hp-stat-stage-boost-attr.ts
  src/data/moves/move-attrs/flame-burst-attr.ts
  src/data/moves/move-attrs/half-sacrificial-attr.ts
  src/data/moves/move-attrs/hit-heal-attr.ts
  src/data/moves/move-attrs/hp-split-attr.ts
  src/data/moves/move-attrs/recoil-attr.ts
  src/data/moves/move-attrs/sacrificial-attr.ts
  src/field/pokemon.ts
  src/phases/move-effect-phase.ts
  src/phases/pokemon-heal-phase.ts
  src/phases/post-turn-status-effect-phase.ts
  src/phases/weather-effect-phase.ts
  src/utils/move-utils.ts
  test/moves/present.test.ts
  test/test-utils/gameWrapper.ts
Labels: Refactor

#861 PR review for 858 - `Pokemon.getAlly()` changes
  src/battle-scene.ts
  src/data/abilities/ab-attrs/post-damage-force-switch-ab-attr.ts
  src/data/abilities/ab-attrs/post-defend-stat-stage-change-ab-attr.ts
  src/data/abilities/ab-attrs/post-turn-reset-status-ab-attr.ts
  src/data/init/init-moves.ts
  src/data/moves/move-attrs/ability-copy-attr.ts
  src/data/moves/move-attrs/force-switch-out-attr.ts
  src/data/moves/move-attrs/revival-blessing-attr.ts
  src/data/moves/move.ts
  src/field/pokemon.ts
  src/phases/command-phase.ts
  src/phases/faint-phase.ts
  src/phases/move-effect-phase.ts
Labels: Miscellaneous

#865 [Misc] Fix incorrect `isNullOrUndefined` import
  src/data/battler-tags/confused-tag.ts
Labels: Miscellaneous

#658 [Bug] Fix calculation of move base power
  src/data/moves/move.ts
  test/battle/damage-calculation.test.ts
Labels: Move, P2 Bug

#868 [Test] Tests for PR #860
  test/abilities/flower-gift.test.ts
  test/abilities/forecast.test.ts
Labels: Tests

#858 [P1] Make getAlly() check for player legal Pokemon
  src/battle-scene.ts
  src/data/abilities/ab-attrs/commander-ab-attr.ts
  src/data/abilities/ab-attrs/post-damage-force-switch-ab-attr.ts
  src/data/abilities/ab-attrs/post-defend-stat-stage-change-ab-attr.ts
  src/data/abilities/ab-attrs/post-turn-reset-status-ab-attr.ts
  src/data/init/init-abilities.ts
  src/data/init/init-moves.ts
  src/data/moves/move-attrs/ability-copy-attr.ts
  src/data/moves/move-attrs/await-combined-pledge-attr.ts
  src/data/moves/move-attrs/force-switch-out-attr.ts
  src/data/moves/move-attrs/last-move-double-power-attr.ts
  src/data/moves/move-attrs/revival-blessing-attr.ts
  src/data/moves/move.ts
  src/field/pokemon.ts
  src/phases/command-phase.ts
  src/phases/enemy-command-phase.ts
  src/phases/faint-phase.ts
  src/phases/move-effect-phase.ts
  src/phases/revival-blessing-phase.ts
Labels: Move, P1 Bug

#860 [P2] Castform and Cherrim revert to normal when primal weather disappears
  src/data/abilities/ab-attrs/post-weather-change-form-change-ab-attr.ts
  test/abilities/flower-gift.test.ts
  test/abilities/forecast.test.ts
Labels: Ability, P2 Bug

#864 [Move][P2] Fix Pollen Puff interactions when targeting an ally
  src/data/moves/move-attrs/heal-on-ally-attr.ts
  src/data/moves/move-attrs/present-power-attr.ts
  src/data/moves/move.ts
  src/field/pokemon.ts
  src/phases/move-effect-phase.ts
Labels: Move, P2 Bug

#869 [P0] Fix memory leak when Save & Quitting
  src/battle-scene.ts
  src/ui/settings/navigation-menu.ts
  src/ui/ui.ts
Labels: P0 Bug

#873 [Move][P2] Spicy extract is now bounceable
  src/data/init/init-moves.ts
  test/data/all-moves.json
Labels: Move, P2 Bug

#875 [Misc] Cleanly reload window when importing data
  src/system/game-data.ts
Labels: Refactor

#874 [Move] Make invalid move lists `ReadonlySet`s and update their contents
  src/data/moves/move-attrs/call-move-attr.ts
  src/data/moves/move-attrs/copycat-attr.ts
  src/data/moves/move-attrs/metronome-attr.ts
  src/data/moves/move-attrs/mirror-move-attr.ts
  src/data/moves/move-attrs/random-moveset-move-attr.ts
Labels: Move, Balance, Refactor

#876 [Refactor] Remove special handling for legacy egg and save data
  src/@types/StarterData.ts
  src/account.ts
  src/data/egg.ts
  src/data/mystery-encounters/encounters/a-trainers-test-encounter.ts
  src/data/mystery-encounters/encounters/the-expert-pokemon-breeder-encounter.ts
  src/data/mystery-encounters/utils/encounter-phase-utils.ts
  src/system/egg-data.ts
  src/system/game-data.ts
  src/ui/handlers/egg-gacha-ui-handler.ts
  src/ui/handlers/starter-select-ui-handler.ts
  test/eggs/egg.test.ts
  test/eggs/manaphy-egg.test.ts
  test/events/shiny-chance-event.test.ts
Labels: Refactor

#867 [Misc] Damage function refactor follow-up
  src/@types/DamageFunctionOptions.ts
  src/data/abilities/ab-attrs/form-block-damage-ab-attr.ts
  src/data/abilities/ab-attrs/post-defend-contact-damage-ab-attr.ts
  src/data/abilities/ab-attrs/post-faint-contact-damage-ab-attr.ts
  src/data/abilities/ab-attrs/post-turn-hurt-if-sleeping-ab-attr.ts
  src/data/abilities/ab-attrs/post-weather-lapse-damage-ab-attr.ts
  src/data/arena-tag.ts
  src/data/battler-tags/contact-damage-protected-tag.ts
  src/data/battler-tags/cursed-tag.ts
  src/data/battler-tags/damaging-trap-tag.ts
  src/data/battler-tags/destiny-bond-tag.ts
  src/data/battler-tags/gulp-missile-tag.ts
  src/data/battler-tags/nightmare-tag.ts
  src/data/battler-tags/perish-song-tag.ts
  src/data/battler-tags/powder-tag.ts
  src/data/battler-tags/salt-cured-tag.ts
  src/data/battler-tags/seed-tag.ts
  src/data/moves/move-attrs/add-substitute-attr.ts
  src/data/moves/move-attrs/curse-attr.ts
  src/data/moves/move-attrs/cut-hp-stat-stage-boost-attr.ts
  src/data/moves/move-attrs/flame-burst-attr.ts
  src/data/moves/move-attrs/half-sacrificial-attr.ts
  src/data/moves/move-attrs/hp-split-attr.ts
  src/data/moves/move-attrs/recoil-attr.ts
  src/data/moves/move-attrs/sacrificial-attr.ts
  src/enums/hit-result.ts
  src/field/pokemon.ts
  src/phases/damage-anim-phase.ts
  src/utils/move-utils.ts
Labels: P2 Bug, P3 Bug, Miscellaneous

#776 [Refactor] Re-implement save migration system
  src/@types/SessionSaveMigrator.ts
  src/@types/SettingsSaveMigrator.ts
  src/@types/SystemSaveMigrator.ts
  src/system/version_migration/version_converter.ts
  test/system/game-data.test.ts
Labels: Refactor

#855 [Move] Implement Snatch
  src/battle-scene.ts
  src/data/battler-tags/snatch-tag.ts
  src/data/battler-tags/utils/get-battler-tag.ts
  src/data/init/init-abilities.ts
  src/data/init/init-moves.ts
  src/data/moves/move-attrs/add-battler-tag-attr.ts
  src/data/moves/move-attrs/swallow-heal-attr.ts
  src/data/moves/move-conditions/has-stockpile-stacks-condition.ts
  src/data/moves/move.ts
  src/enums/battler-tag-type.ts
  src/enums/move-flags.ts
  src/phases/move-phase.ts
  test/data/all-moves.json
  test/data/all-moves.test.ts
  test/moves/snatch.test.ts
Labels: Move, Localization

#883 [Test] Move "RNG sweeps" to a new helper
  test/abilities/effect-spore.test.ts
  test/battle/double-battle.test.ts
  test/eggs/manaphy-egg.test.ts
  test/moves/metronome.test.ts
  test/moves/present.test.ts
  test/mystery-encounter/encounters/safari-zone.test.ts
  test/mystery-encounter/encounters/the-pokemon-salesman-encounter.test.ts
  test/pokemon/evolution.test.ts
  test/test-utils/gameManager.ts
  test/test-utils/helpers/rngHelper.ts
Labels: Tests

#866 [Balance] Change how friendship works
  src/battle-scene.ts
  src/constants.ts
  src/data/balance/pokemon-evolutions/gen1-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen2-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen3-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen4-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen5-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen7-pokemon-family-evolutions.ts
  src/data/balance/pokemon-evolutions/gen8-pokemon-family-evolutions.ts
  src/data/balance/starters.ts
  src/data/pokemon-evolutions.ts
  src/field/pokemon.ts
  src/modifier/modifier.ts
  src/phases/encounter-phase.ts
  src/phases/faint-phase.ts
  src/phases/level-up-phase.ts
  src/phases/next-encounter-phase.ts
  test/events/candy-friendship-event.test.ts
  test/mystery-encounter/encounters/the-expert-breeder-encounter.test.ts
Labels: Balance

#820 [Move] Implement Me First
  src/data/battler-tags/me-first-power-boost-tag.ts
  src/data/battler-tags/move-lock-tag.ts
  src/data/battler-tags/utils/get-battler-tag.ts
  src/data/init/init-moves.ts
  src/data/moves/move-attrs/add-battler-tag-attr.ts
  src/data/moves/move-attrs/me-first-attr.ts
  src/data/moves/move.ts
  src/enums/battler-tag-type.ts
  test/moves/me-first.test.ts
Labels: Move

#888 [Misc] Reformat `src/init/init-abilities.ts`
  src/data/init/init-abilities.ts
Labels: Miscellaneous
