Repository Despair-Games/poketernity, pull requests merged in 2025-06, with the labels that each got.

#1229 [Refactor] Rename FLYING battler tag to MID_AIR
  src/constants/battler-tag-constants.ts
  src/data/arena-tags/gravity-tag.ts
  src/data/battler-tags/interrupted-tag.ts
  src/data/battler-tags/utils/get-battler-tag.ts
  src/data/init/init-moves.ts
  src/data/moves/move-attrs/add-battler-tag-attr.ts
  src/enums/battler-tag-type.ts
  test/arena/gravity.test.ts
  test/moves/court-change.test.ts
  test/moves/fly.test.ts
  test/moves/whirlwind.test.ts
Labels: Refactor

#1208 [Dev] Migrate from `npm` to `pnpm`
  .dependency-cruiser.cjs
  .github/pull_request_template.md
  .github/workflows/deploy-beta.yml
  .github/workflows/deploy-tag.yml
  .github/workflows/deploy.yml
  .github/workflows/github-pages.yml
  .github/workflows/lint.yml
  .github/workflows/test-shard-template.yml
  .npmrc
  README.md
  biome.jsonc
  docs/linting.md
  lefthook.yml
  package-lock.json
  package.json
  pnpm-lock.yaml
  scripts/create-test/create-test.js
Labels: Development

#1239 [Addendum] Add support for multi-Phase input in Phase scheduling methods
  src/data/abilities/ab-attrs/post-damage-force-switch-ab-attr.ts
  src/data/moves/move-attrs/force-switch-out-attr.ts
  src/data/mystery-encounters/utils/encounter-phase-utils.ts
  src/field/player-pokemon.ts
  src/phase-manager.ts
  src/phases/command-phase.ts
  src/phases/revival-blessing-phase.ts
  src/turn-command-manager.ts
  src/ui/handlers/starter-select-ui-handler.ts
Labels: Addendum

#1240 [Dev] Enforce type-only imports in `@types/` and `enums/`
  .dependency-cruiser.cjs
  src/@types/pokemon-summon-data.ts
  src/enums/challenge-type.ts
Labels: Development

#1244 [Dev] Update test mocks
  test/test-utils/mocks/mock-game-object-creator.ts
  test/test-utils/mocks/mock-game-object.ts
  test/test-utils/mocks/mock-texture-manager.ts
  test/test-utils/mocks/mock-video-game-object.ts
  test/test-utils/mocks/mocks-container/mock-bbcode-text.ts
  test/test-utils/mocks/mocks-container/mock-container.ts
  test/test-utils/mocks/mocks-container/mock-graphics.ts
  test/test-utils/mocks/mocks-container/mock-image.ts
  test/test-utils/mocks/mocks-container/mock-input-text.ts
  test/test-utils/mocks/mocks-container/mock-nineslice.ts
  test/test-utils/mocks/mocks-container/mock-polygon.ts
  test/test-utils/mocks/mocks-container/mock-rectangle.ts
  test/test-utils/mocks/mocks-container/mock-sprite.ts
  test/test-utils/mocks/mocks-container/mock-text.ts
  test/test-utils/mocks/mocks-container/mock-texture.ts
  test/test-utils/mocks/mocksContainer/mock-container.ts
  test/test-utils/mocks/mocksContainer/mock-sprite.ts
  test/test-utils/test-file-initialization.ts
  test/ui/type-hints.test.ts
Labels: Tests, Development

#1232 [Refactor] Pokemon IVs are now 6 randomly generated numbers
  src/battle-scene.ts
  src/data/egg.ts
  src/field/pokemon.ts
  src/utils/pokemon-utils.ts
  src/utils/random-utils.ts
Labels: Refactor

#1238 [Dev] Update packages, update `phaser.d.ts`
  .npmrc
  package.json
  pnpm-lock.yaml
  src/@types/phaser.d.ts
Labels: Dependencies, Development

#1242 [Refactor][UI] Refactor Game Stats Ui Handler
  src/enums/font-style.ts
  src/ui/components/text-list-container.ts
  src/ui/handlers/game-stats-ui-handler.ts
  src/ui/interfaces/font-style-options.ts
  src/ui/text/font-style.ts
  src/ui/text/text-style.ts
  src/ui/text/text-utils.ts
Labels: Refactor, UI/UX

#1259 Review for PR 1250
  src/@types/phase-types.ts
  src/phase-manager.ts
  src/phase.ts
  test/test-utils/phase-interceptor.ts
Labels: Addendum

#1230 [UI] Initialize and destroy UI handlers dynamically
  .env
  .env.beta
  .env.development
  .env.production
  .env.test
  src/battle-scene.ts
  src/enums/battle-scene-event-type.ts
  src/enums/font-style.ts
  src/events/battle-scene.ts
  src/loggers.ts
  src/phases/encounter-phase.ts
  src/phases/end-card-phase.ts
  src/phases/level-up-phase.ts
  src/phases/post-game-over-phase.ts
  src/phases/scan-ivs-phase.ts
  src/phases/title-phase.ts
  src/ui/components/text-list-container.ts
  src/ui/handlers/achievements-ui-handler.ts
  src/ui/handlers/battle-message-ui-handler.ts
  src/ui/handlers/command-ui-handler.ts
  src/ui/handlers/egg-hatch-scene-ui-handler.ts
  src/ui/handlers/fight-ui-handler.ts
  src/ui/handlers/game-stats-ui-handler.ts
  src/ui/handlers/menu-ui-handler.ts
  src/ui/handlers/message-ui-handler.ts
  src/ui/handlers/mystery-encounter-ui-handler.ts
  src/ui/handlers/rename-pokemon-ui-handler.ts
  src/ui/handlers/title-ui-handler.ts
  src/ui/interfaces/font-style-options.ts
  src/ui/settings/controls-settings-ui-handler.ts
  src/ui/settings/general-settings-ui-handler.ts
  src/ui/settings/settings-ui-handler.ts
  src/ui/text/font-style.ts
  src/ui/text/text-style.ts
  src/ui/text/text-utils.ts
  src/ui/ui.ts
  src/vite.env.d.ts
  test/test-utils/mocks/mock-console.ts
  test/test-utils/phase-interceptor.ts
Labels: Refactor, UI/UX

#1264 [Refactor] Replace `Localizable` pattern with localized getters
  src/@types/locales.ts
  src/battle-scene.ts
  src/data/abilities/ability.ts
  src/data/moves/move.ts
  src/data/pokemon-species.ts
  src/modifier/init-modifier-types.ts
  src/modifier/modifier-type.ts
  src/modifier/modifier.ts
  src/ui/handlers/modifier-select-ui-handler.ts
  src/ui/handlers/summary-ui-handler.ts
  src/ui/settings/settings-ui-handler.ts
Labels: Refactor, Localization

#1265 [Dev] Update brace-expansion from 1.1.11 -> 1.1.12 and 2.0.1 -> 2.0.2
  pnpm-lock.yaml
Labels: Development

#1269 [Refactor] Add `FieldBattlerIndex` type
  src/@types/attack-move-result.ts
  src/data/animations/move-anim.ts
  src/data/animations/move-charge-anim.ts
  src/data/arena-tags/delayed-attack-tag.ts
  src/data/arena-tags/pending-heal-tag.ts
  src/data/arena-tags/wish-tag.ts
  src/data/moves/move.ts
  src/data/mystery-encounters/mystery-encounter.ts
  src/data/mystery-encounters/utils/encounter-phase-utils.ts
  src/enums/battler-index.ts
  src/field/arena.ts
  src/field/damage-number-handler.ts
  src/field/enemy-pokemon.ts
  src/field/player-pokemon.ts
  src/field/pokemon.ts
  src/phase-manager.ts
  src/phases/abstract-pokemon-phase.ts
  src/phases/common-anim-phase.ts
  src/phases/damage-anim-phase.ts
  src/phases/faint-phase.ts
  src/phases/move-effect-phase.ts
  src/phases/obtain-status-effect-phase.ts
  src/phases/pokemon-heal-phase.ts
  src/phases/pokemon-transform-phase.ts
  src/phases/post-action-phase.ts
  src/phases/post-knockout-phase.ts
  src/phases/scan-ivs-phase.ts
  src/phases/show-ability-phase.ts
  src/phases/stat-stage-change-phase.ts
  src/utils/move-utils.ts
  test/moves/destiny-bond.test.ts
  test/moves/encore.test.ts
  test/test-utils/game-manager.ts
  test/test-utils/helpers/field-helper.ts
Labels: Refactor

#1277 Review suggestions for PR1260
  src/field/pokemon-move.ts
  test/moves/powder.test.ts
  test/moves/sketch.test.ts
  test/mystery-encounter/encounters/an-offer-you-cant-refuse-encounter.test.ts
  test/mystery-encounter/encounters/clowning-around-encounter.test.ts
  test/mystery-encounter/encounters/dancing-lessons-encounter.test.ts
  test/mystery-encounter/encounters/fight-or-flight-encounter.test.ts
  test/mystery-encounter/encounters/part-timer-encounter.test.ts
  test/mystery-encounter/encounters/the-strong-stuff-encounter.test.ts
  test/mystery-encounter/encounters/trash-to-treasure-encounter.test.ts
  test/mystery-encounter/encounters/uncommon-breed-encounter.test.ts
Labels: Addendum
