Repository Despair-Games/poketernity, pull requests merged in 2025-02, with the labels that each got.

#411 [Move] Remove edge case notes from Foul Play + Body Press
  src/data/all-moves.ts
Labels: Move

#410 [Test] Add eslint rule enforcing proper `await` usage in tests
  eslint.config.js
  test/moves/dragon_rage.test.ts
  test/moves/fissure.test.ts
  test/mystery-encounter/mystery-encounter-utils.test.ts
  test/pokemon/evolution.test.ts
  test/ui/transfer-item.test.ts
Labels: Tests

#397 [Dev] Add npm script `test:full` (= `typecheck` + `test:silent`)
  package.json
Labels: Miscellaneous

#416 [Ability] Revert Perish Body to previous behavior and add tests
  src/data/ab-attrs/post-defend-perish-song-ab-attr.ts
  src/data/all-abilities.ts
  test/abilities/perish_body.test.ts
Labels: Ability, P2 Bug

#423 [Test] Group together weather tests even further
  test/abilities/block_weather_damage.test.ts
  test/abilities/post_weather_lapse_heal.test.ts
Labels: Ability, Tests, Checkup

#418 [UI][P3] Fix moves getting hidden when pressing C with move info disabled
  src/ui/fight-ui-handler.ts
Labels: P3 Bug, UI/UX

#427 [Beta][P3] Fix new players not being asked for their preferred gender
  src/phases/login-phase.ts
  src/system/settings/default-settings.ts
Labels: P3 Bug, Beta

#414 [Ability][Checkup] Post-Weather Lapse Heal Abilities (Rain Dish, Ice Body, and Dry Skin)
  src/data/ab-attrs/post-weather-lapse-heal-ab-attr.ts
  src/data/all-abilities.ts
  test/abilities/block_weather_damage.test.ts
  test/abilities/post_weather_lapse_heal.test.ts
  test/abilities/sand_rush.test.ts
Labels: Checkup

#430 [Bug] `PreSetStatusEffectImmunityAbAttr` no longer prevents fainting
  src/data/ab-attrs/pre-set-status-effect-immunity-ab-attr.ts
Labels: Ability, P1 Bug

#428 [Bug] Fix end-of-turn weather effects occurring when weather expires
  src/phases/turn-end-phase.ts
  src/phases/weather-effect-phase.ts
  test/arena/grassy_terrain.test.ts
  test/arena/weather_sandstorm.test.ts
Labels: Ability, P2 Bug

#392 [Balance] New boss teams
  src/data/balance/trainer-configs/evil-boss-trainer-configs.ts
Labels: Balance

#434 [Bug][Misc] Update create-test to use the new move enum name
  create-test-boilerplate.js
Labels: P3 Bug

#404 [Ability] Implement Mirror Armor + Fully Implement Infiltrator
  src/data/ab-attrs/download-ab-attr.ts
  src/data/ab-attrs/flinch-stat-stage-change-ab-attr.ts
  src/data/ab-attrs/moody-ab-attr.ts
  src/data/ab-attrs/move-immunity-stat-stage-change-ab-attr.ts
  src/data/ab-attrs/post-battle-init-stat-stage-change-ab-attr.ts
  src/data/ab-attrs/post-defend-crit-stat-stage-change-ab-attr.ts
  src/data/ab-attrs/post-defend-hp-gated-stat-tage-change-ab-attr.ts
  src/data/ab-attrs/post-defend-stat-stage-change-ab-attr.ts
  src/data/ab-attrs/post-intimidate-stat-stage-change-ab-attr.ts
  src/data/ab-attrs/post-knock-out-stat-stage-change-ab-attr.ts
  src/data/ab-attrs/post-stat-stage-change-stat-stage-change-ab-attr.ts
  src/data/ab-attrs/post-summon-stat-stage-change-ab-attr.ts
  src/data/ab-attrs/post-victory-stat-stage-change-ab-attr.ts
  src/data/ab-attrs/reflect-stat-stage-change-ab-attr.ts
  src/data/ab-attrs/speed-boost-ab-attr.ts
  src/data/ab-attrs/stat-stage-change-copy-ab-attr.ts
  src/data/ab-attrs/type-immunity-stat-stage-change-ab-attr.ts
  src/data/all-abilities.ts
  src/data/arena-tag.ts
  src/data/battler-tags.ts
  src/data/berry.ts
  src/data/move-attrs/acupressure-stat-stage-change-attr.ts
  src/data/move-attrs/curse-attr.ts
  src/data/move-attrs/order-up-stat-boost-attr.ts
  src/data/move-attrs/stat-stage-change-attr.ts
  src/data/mystery-encounters/encounters/absolute-avarice-encounter.ts
  src/data/mystery-encounters/encounters/berries-abound-encounter.ts
  src/data/mystery-encounters/encounters/dancing-lessons-encounter.ts
  src/data/mystery-encounters/encounters/fiery-fallout-encounter.ts
  src/data/mystery-encounters/encounters/fight-or-flight-encounter.ts
  src/data/mystery-encounters/encounters/teleporting-hijinks-encounter.ts
  src/data/mystery-encounters/encounters/the-strong-stuff-encounter.ts
  src/data/mystery-encounters/encounters/uncommon-breed-encounter.ts
  src/field/pokemon.ts
  src/phases/stat-stage-change-phase.ts
  test/abilities/contrary.test.ts
  test/abilities/infiltrator.test.ts
  test/abilities/mirror_armor.test.ts
Labels: Ability

#403 [AI-Rework] Rewrite enemy command selection
  src/data/ab-attrs/add-second-strike-ab-attr.ts
  src/data/all-abilities.ts
  src/data/all-moves.ts
  src/data/move-attrs/beat-up-attr.ts
  src/data/move-attrs/combined-pledge-power-attr.ts
  src/data/move-attrs/combined-pledge-stab-boost-attr.ts
  src/data/move-attrs/combined-pledge-type-attr.ts
  src/data/move-attrs/counter-damage-attr.ts
  src/data/move-attrs/hit-count-power-attr.ts
  src/data/move-attrs/last-move-double-power-attr.ts
  src/data/move-attrs/move-attr.ts
  src/data/move-attrs/multi-hit-power-increment-attr.ts
  src/data/move-attrs/present-power-attr.ts
  src/data/move-attrs/turn-damaged-double-power-attr.ts
  src/data/move-conditions.ts
  src/data/move.ts
  src/data/mystery-encounters/encounters/berries-abound-encounter.ts
  src/field/pokemon.ts
  src/overrides.ts
  src/phases/battle-end-phase.ts
  src/phases/enemy-command-phase.ts
  test/abilities/stakeout.test.ts
  test/ai/enemy_command.test.ts
  test/arena/type_hazard.test.ts
  test/moves/ceaseless_edge.test.ts
  test/moves/chilly_reception.test.ts
  test/moves/focus_punch.test.ts
  test/moves/fusion_flare_bolt.test.ts
  test/moves/spikes.test.ts
  test/moves/substitute.test.ts
  test/testUtils/gameManager.ts
  test/testUtils/helpers/overridesHelper.ts
Labels: AI

#398 [Audio] Remove music preference option
  src/@types/Settings.ts
  src/battle.ts
  src/data/balance/trainer-configs/champion-double-trainer-configs.ts
  src/data/balance/trainer-configs/champion-trainer-configs.ts
  src/data/balance/trainer-configs/elite-four-trainer-configs.ts
  src/data/balance/trainer-configs/evil-team-trainer-configs.ts
  src/data/balance/trainer-configs/gym-leader-configs.ts
  src/data/balance/trainer-configs/me-trainer-configs.ts
  src/data/balance/trainer-configs/rival-trainer-configs.ts
  src/data/music-constants.ts
  src/data/mystery-encounters/encounters/berries-abound-encounter.ts
  src/data/mystery-encounters/encounters/global-trade-system-encounter.ts
  src/data/trainer-config.ts
  src/enums/music-preference.ts
  src/field/trainer.ts
  src/system/settings/default-settings.ts
  src/ui/settings/abstract-settings-ui-handler.ts
  src/ui/settings/settings-audio-ui-handler.ts
  src/ui/settings/settings-ui-items.ts
Labels: Audio

#446 [Move][P2] Bouncy bubble is single target and heals 100%
  src/data/all-moves.ts
  test/moves/bouncy_bubble.test.ts
Labels: Move, P2 Bug

#421 [Items] Removed Leek and Lens items
  src/data/move-attrs/target-half-hp-damage-attr.ts
  src/data/move.ts
  src/data/mystery-encounters/encounters/clowning-around-encounter.ts
  src/data/mystery-encounters/encounters/fun-and-games-encounter.ts
  src/data/mystery-encounters/encounters/the-winstrate-challenge-encounter.ts
  src/field/pokemon.ts
  src/modifier/modifier-type.ts
  src/modifier/modifier.ts
  src/phases/move-effect-phase.ts
  test/abilities/parental_bond.test.ts
  test/abilities/unburden.test.ts
  test/abilities/wimp_out.test.ts
  test/items/leek.test.ts
  test/items/multi_lens.test.ts
  test/items/scope_lens.test.ts
  test/moves/beak_blast.test.ts
  test/moves/ceaseless_edge.test.ts
  test/moves/electro_shot.test.ts
  test/moves/glaive_rush.test.ts
  test/mystery-encounter/encounters/fun-and-games-encounter.test.ts
Labels: Item

#453 [P2][Move] Fix flail/reversal damage formula
  src/data/move-attrs/low-hp-power-attr.ts
  test/moves/flail.test.ts
Labels: Move, P2 Bug, Checkup

#452 [Balance] G-Max Pokemon now learn their G-Max moves on evolution
  src/data/balance/pokemon-form-level-moves.ts
Labels: Enhancement, Balance

#458 [Beta P2] Fix incorrect G-Max move learning (Venusuar, Blastoise, Copperajah), G-Max Pokemon can now remember base form EVOLVE_MOVEs
  src/data/balance/pokemon-form-level-moves.ts
Labels: P2 Bug, Beta

#442 [AI-Rework] Add move-property-based scoring
  src/data/move-attrs/move-attr.ts
  src/data/move.ts
  src/field/pokemon.ts
  test/ai/enemy_command.test.ts
  test/ai/low_accuracy.test.ts
  test/ai/priority.test.ts
  test/ai/utils/enemy_command_utils.ts
Labels: AI

#457 [Test] Fix `allMoves` being empty before `beforeAll` gets run
  test/testUtils/testFileInitialization.ts
  test/vitest.setup.ts
  vitest.config.ts
Labels: Tests

#443 [Feature] Add item framework
  src/item/base-item.ts
  src/item/consumable-item.ts
  src/item/held-item.ts
  src/item/key-item.ts
Labels: Enhancement, Refactor, Item

#456 [Ability][Checkup] Quick Feet Checkup
  src/data/ab-attrs/bypass-para-speed-reduction-ab-attr.ts
  src/data/all-abilities.ts
  src/field/pokemon.ts
  test/abilities/quick_feet.test.ts
Labels: Tests, Checkup

#422 [Refactor][Move] Field-based move targeting no longer requires a target Pokemon
  src/data/all-abilities.ts
  src/data/all-moves.ts
  src/data/move-attrs/add-arena-tag-attr.ts
  src/data/move-attrs/add-arena-trap-tag-attr.ts
  src/data/move-attrs/add-pledge-effect-attr.ts
  src/data/move-attrs/move-effect-attr.ts
  src/data/move-attrs/terrain-change-attr.ts
  src/data/move-attrs/weather-change-attr.ts
  src/data/move.ts
  src/enums/battler-index.ts
  src/field/pokemon.ts
  src/phases/command-phase.ts
  src/phases/move-effect-phase.ts
  src/phases/move-phase.ts
  src/ui/target-select-ui-handler.ts
  test/abilities/good_as_gold.test.ts
  test/moves/ceaseless_edge.test.ts
Labels: Move, Refactor

#468 [Bug] Psychic Terrain will now display the proper failure message
  src/phases/move-phase.ts
Labels: Move, P3 Bug

#459 [Test] Add tests for learning moves via form change
  test/phases/form-change-phase.test.ts
Labels: Tests

#464 [Balance] G-Max Pikachu/Eevee use partner stats, G-Max Toxtricity has plus now
  src/data/init-species.ts
Labels: Balance

#645 [Bug][Misc] Re-added BypassParaSpeedReductionAbAttr
  src/data/init-abilities.ts
Labels: P3 Bug, Miscellaneous

#647 Readded SmellYaLater as a possible release message
  src/battle-scene.ts
Labels: Localization

#467 [Refactor] Make use of color enums
  index.html
  src/battle-scene.ts
  src/data/challenge.ts
  src/data/exp.ts
  src/data/gender.ts
  src/data/type.ts
  src/enums/color.ts
  src/field/damage-number-handler.ts
  src/loading-scene.ts
  src/modifier/modifier.ts
  src/ui/challenges-select-ui-handler.ts
  src/ui/party-ui-handler.ts
  src/ui/run-history-ui-handler.ts
  src/ui/run-info-ui-handler.ts
  src/ui/save-slot-select-ui-handler.ts
  src/ui/text.ts
  test/ui/type-hints.test.ts
Labels: Refactor

#649 [Checkup] Super Luck documentation and tests
  src/data/ab-attrs/bonus-crit-ab-attr.ts
  src/data/init-abilities.ts
  src/field/pokemon.ts
  test/abilities/super_luck.test.ts
Labels: Checkup

#652 [Move] Fully implement rage
  src/data/battler-tags.ts
  src/data/init-moves.ts
  src/data/move-attrs/rage-attr.ts
  src/enums/battler-tag-type.ts
  test/moves/rage.test.ts
Labels: Move

#659 [Documentation][Refactor] Document and refactor arena.ts
  src/field/arena.ts
Labels: Documentation, Refactor

#675 [Beta][Bug] Fix typo in generateBossBiomeTier
  src/field/arena.ts
Labels: P1 Bug, P2 Bug, Beta

#466 [Balance] G-Max Pokemon take 1/3 less damage
  src/constants.ts
  src/field/pokemon.ts
  test/battle/gmax_damage_calculation.test.ts
  test/testUtils/helpers/overridesHelper.ts
Labels: Balance

#662 [P2] HA Giratina no longer loses HA when going from origin->altered
  src/data/init-species.ts
Labels: P2 Bug

#682 [P3][Beta] Fix settings showing wrong number of window types
  src/ui/settings/settings-ui-items.ts
Labels: P3 Bug, Beta

#665 [Move] Add `edgeCase` to moves with "unselectable" conditions
  src/data/init-moves.ts
Labels: Move, P3 Bug

#676 [Refactor] Add arena utils, fix wrong checks for biome indoors and props
  src/data/ab-attrs/post-biome-change-terrain-change-ab-attr.ts
  src/data/ab-attrs/post-biome-change-weather-change-ab-attr.ts
  src/data/ab-attrs/post-defend-terrain-change-ab-attr.ts
  src/data/ab-attrs/post-defend-weather-change-ab-attr.ts
  src/data/ab-attrs/post-summon-terrain-change-ab-attr.ts
  src/data/ab-attrs/post-summon-weather-change-ab-attr.ts
  src/data/ab-attrs/post-weather-lapse-ab-attr.ts
  src/data/balance/pokemon-evolutions.ts
  src/data/battler-tags.ts
  src/data/init-abilities.ts
  src/data/init-moves.ts
  src/data/move-attrs/anti-sunlight-power-decrease-attr.ts
  src/data/move-attrs/blizzard-accuracy-attr.ts
  src/data/move-attrs/chilly-reception-attr.ts
  src/data/move-attrs/clear-weather-attr.ts
  src/data/move-attrs/growth-stat-stage-change-attr.ts
  src/data/move-attrs/ignore-weather-type-debuff-attr.ts
  src/data/move-attrs/storm-accuracy-attr.ts
  src/data/move-attrs/terrain-change-attr.ts
  src/data/move.ts
  src/data/mystery-encounters/encounters/the-expert-pokemon-breeder-encounter.ts
  src/data/pokemon-forms.ts
  src/data/species-form-change-triggers/species-form-change-time-of-day-trigger.ts
  src/field/arena.ts
  src/field/pokemon.ts
  src/utils/ability-utils.ts
  test/abilities/sand_veil.test.ts
  test/abilities/sap_sipper.test.ts
  test/arena/grassy_terrain.test.ts
  test/moves/camouflage.test.ts
  test/testUtils/helpers/overridesHelper.ts
Labels: P3 Bug, Refactor

#679 [Test] Various fixes and colour coding for `MockConsole`
  test/testUtils/TextInterceptor.ts
  test/testUtils/gameWrapper.ts
  test/testUtils/mocks/mockConsole.ts
  test/testUtils/mocks/mockConsoleLog.ts
  test/testUtils/testFileInitialization.ts
  test/vitest.setup.ts
Labels: Tests

#670 [Move] Fully Implement Conversion 2
  src/@types/TurnMove.ts
  src/data/battler-tags.ts
  src/data/init-moves.ts
  src/data/move-attrs/delayed-attack-attr.ts
  src/data/move-attrs/resist-last-move-type-attr.ts
  src/phases/move-charge-phase.ts
  src/phases/move-effect-phase.ts
  src/phases/move-phase.ts
  test/moves/conversion_2.test.ts
  test/moves/disable.test.ts
  test/moves/instruct.test.ts
  test/moves/spit_up.test.ts
  test/moves/stockpile.test.ts
  test/moves/swallow.test.ts
Labels: Move

#663 [Refactor][Misc] Cleaned up critical capture code.
  src/data/pokeball.ts
Labels: Refactor, Miscellaneous

#694 [P2] Fix Poltergeist's pre-move message triggering during enemy move evaluation
  src/data/move-attrs/attacked-by-item-attr.ts
  src/phases/move-phase.ts
Labels: Move, P2 Bug

#687 [Move][Refactor] Reimplement "Frenzy" moves
  src/data/battler-tags.ts
  src/data/init-moves.ts
  src/data/move-attrs/frenzy-attr.ts
  src/data/move-attrs/move-effect-attr.ts
  src/data/move-attrs/sky-drop-attr.ts
  src/phases/move-phase.ts
  src/utils/battler-tag-type-utils.ts
  src/utils/move-utils.ts
  test/moves/sky_drop.test.ts
  test/moves/thrash.test.ts
  test/phases/frenzy-move-reset.test.ts
Labels: Move, Refactor, Checkup

#690 [P3] Fix settings giving a warning due to unset player gender
  src/ui/settings/abstract-settings-ui-handler.ts
Labels: P3 Bug

#432 [Refactor] Remove `StatusEffect.FAINT`, add `Pokemon.faint()`
  src/data/ab-attrs/post-summon-user-field-remove-status-effect-ab-attr.ts
  src/data/ab-attrs/post-turn-reset-status-ab-attr.ts
  src/data/ab-attrs/pre-set-status-effect-immunity-ab-attr.ts
  src/data/berry.ts
  src/data/init-abilities.ts
  src/data/move-attrs/party-status-cure-attr.ts
  src/data/mystery-encounters/encounters/fun-and-games-encounter.ts
  src/data/mystery-encounters/utils/encounter-phase-utils.ts
  src/data/mystery-encounters/utils/encounter-pokemon-utils.ts
  src/data/status-effect.ts
  src/enums/status-effect.ts
  src/field/pokemon.ts
  src/modifier/modifier.ts
  src/phases/abstract-pokemon-phase.ts
  src/phases/attempt-capture-phase.ts
  src/phases/attempt-run-phase.ts
  src/phases/faint-phase.ts
  src/phases/victory-phase.ts
  src/ui/battle-info.ts
  src/ui/party-ui-handler.ts
  src/ui/summary-ui-handler.ts
  test/abilities/battle_bond.test.ts
  test/abilities/power_construct.test.ts
  test/abilities/schooling.test.ts
  test/abilities/shields_down.test.ts
  test/abilities/zen_mode.test.ts
  test/abilities/zero_to_hero.test.ts
  test/battle/double_battle.test.ts
  test/moves/dragon_tail.test.ts
  test/moves/flame_burst.test.ts
  test/moves/whirlwind.test.ts
  test/mystery-encounter/encounter-test-utils.ts
  test/mystery-encounter/encounters/the-winstrate-challenge-encounter.test.ts
  test/mystery-encounter/mystery-encounter-utils.test.ts
Labels: Refactor

#707 [P2] Change sheer force multiplier from 1.33 -> 1.3
  src/data/init-abilities.ts
  test/abilities/sheer_force.test.ts
  test/moves/burning_jealousy.test.ts
Labels: Ability, P2 Bug

#701 [AI] Give all battler tags target benefit score
  src/data/battler-tags.ts
  src/data/move-attrs/add-battler-tag-attr.ts
  src/enums/battler-tag-type.ts
  src/field/pokemon.ts
Labels: Ability, Move, AI

#714 [Refactor][Bug] Add `canSetWeather` utility + Fix Chilly Reception
  src/data/ab-attrs/post-biome-change-weather-change-ab-attr.ts
  src/data/ab-attrs/post-defend-weather-change-ab-attr.ts
  src/data/ab-attrs/suppress-weather-effect-ab-attr.ts
  src/data/move-attrs/weather-change-attr.ts
  src/data/weather.ts
  src/field/arena.ts
  test/arena/primal_weather.test.ts
Labels: P2 Bug, Refactor

#713 [P3] Fix map and gender select menu configurations
  src/phases/select-biome-phase.ts
  src/phases/select-gender-phase.ts
  src/ui/login-form-ui-handler.ts
  src/ui/menu-ui-handler.ts
  src/ui/starter-select-ui-handler.ts
Labels: Refactor, UI/UX

#672 [Test] Display caution message when a Pokemon is damaged to low HP
  test/moves/grudge.test.ts
  test/testUtils/TextInterceptor.ts
  test/testUtils/gameWrapper.ts
  test/testUtils/mocks/mockConsole.ts
  test/testUtils/mocks/mockConsoleLog.ts
  test/testUtils/testFileInitialization.ts
  test/vitest.setup.ts
Labels: Tests

#708 [Misc] Rename `ArenaTrapTag` to `EntryHazardTag`
  src/data/ab-attrs/post-defend-apply-entry-hazard-tag-ab-attr.ts
  src/data/arena-tag.ts
  src/data/init-abilities.ts
  src/data/init-moves.ts
  src/data/move-attrs/add-entry-hazard-tag-attr.ts
  src/data/move-attrs/remove-entry-hazard-attr.ts
  src/events/arena.ts
  src/field/arena.ts
  src/field/trainer.ts
  src/phases/post-summon-phase.ts
  src/system/game-data.ts
  src/ui/arena-flyout.ts
  src/utils/arena-tag-type-utils.ts
  test/moves/ceaseless_edge.test.ts
  test/moves/destiny_bond.test.ts
  test/moves/protect.test.ts
  test/moves/toxic_spikes.test.ts
  test/utils/arena_tag_type_utils.test.ts
Labels: Miscellaneous

#727 [Test] The sprite test will now output useful error messages on fail
  test/sprites/pokemonSprite.test.ts
Labels: Tests

#730 [Refactor] Add `ArenaTag.i18nSideKey` to consolidate player side checks
  src/data/arena-tag.ts
Labels: Refactor

#724 [P2][P3] Starter moveset for Pokemon with forms now updates properly
  src/ui/starter-select-ui-handler.ts
Labels: P2 Bug, UI/UX

#728 [Balance] Multi-hit moves now use gen 5+ behavior
  src/data/move-attrs/multi-hit-attr.ts
Labels: Balance

#731 [Balance] Remove custom Hidden Abilities from all species
  src/data/balance/trainer-configs/evil-boss-trainer-configs.ts
  src/data/init-species.ts
Labels: Balance

#735 [P2] Fog can be suppressed
  src/constants.ts
  src/data/move.ts
  test/arena/weather_fog.test.ts
Labels: Ability, P2 Bug

#734 [P2] Sand Spit and Seed Sower activate even on KO
  src/data/init-abilities.ts
  test/abilities/sand_spit.test.ts
Labels: Ability, P2 Bug

#726 [Misc] Update logging in `EncounterPhase`
  src/data/mystery-encounters/utils/encounter-phase-utils.ts
  src/phases/encounter-phase.ts
Labels: Enhancement, Miscellaneous

#747 [P3] Damaging arena tags should not proc on fainted Pokemon
  src/data/arena-tag.ts
Labels: Move, P3 Bug, Beta

#746 [Test] Overhaul of Reflect, Light Screen, and Aurora Veil tests
  src/constants.ts
  src/data/arena-tag.ts
  test/moves/aurora_veil.test.ts
  test/moves/light_screen.test.ts
  test/moves/reflect.test.ts
  test/moves/screens.test.ts
Labels: Tests

#739 [P2] Crits bypass screens
  src/constants.ts
  src/data/arena-tag.ts
  src/field/pokemon.ts
  test/moves/aurora_veil.test.ts
  test/moves/light_screen.test.ts
  test/moves/reflect.test.ts
  test/moves/screens.test.ts
Labels: Move, P2 Bug

#737 [P2] Perish song KOs g-max Pokemon now
  src/data/battler-tags.ts
  test/battle/gmax_damage_calculation.test.ts
Labels: P2 Bug, Beta

#717 [Misc] Set version to `0.1.0`, add version update commands
  .github/pull_request_template.md
  package-lock.json
  package.json
  src/system/pokemon-data.ts
  src/system/version_migration/version_converter.ts
  src/system/version_migration/versions/v1_0_4.ts
  src/system/version_migration/versions/v1_1_0.ts
Labels: Miscellaneous

#754 [Bug] Fix status effects not being saved
  src/system/pokemon-data.ts
  test/battle/reload.test.ts
Labels: P2 Bug, Miscellaneous

#718 [Balance] Update Paldea gyms and gym leader teras
  src/data/balance/signatureSpecies.ts
  src/data/balance/trainer-configs/gym-leader-configs.ts
  src/data/trainer-config.ts
Labels: Balance

#755 [Misc] Update interface usage in phase constructors
  src/battle-scene.ts
  src/phases/pokemon-heal-phase.ts
  src/phases/select-modifier-phase.ts
  src/phases/stat-stage-change-phase.ts
Labels: Miscellaneous

#706 [Refactor] Refactor timed events
  public/images/banners/welcome_en.png
  public/images/banners/welcome_fr.png
  public/images/events/august-variant-update.png
  public/images/events/egg-update_de.png
  public/images/events/egg-update_en.png
  public/images/events/egg-update_es.png
  public/images/events/egg-update_fr.png
  public/images/events/egg-update_it.png
  public/images/events/egg-update_ja.png
  public/images/events/egg-update_ko.png
  public/images/events/egg-update_pt-BR.png
  public/images/events/egg-update_zh-CN.png
  public/images/events/halloween2024-event-de.png
  public/images/events/halloween2024-event-en.png
  public/images/events/halloween2024-event-es-ES.png
  public/images/events/halloween2024-event-fr.png
  public/images/events/halloween2024-event-it.png
  public/images/events/halloween2024-event-ja.png
  public/images/events/halloween2024-event-ko.png
  public/images/events/halloween2024-event-pt-BR.png
  public/images/events/halloween2024-event-zh-CN.png
  public/images/events/pride-update.png
  public/images/events/september-update-de.png
  public/images/events/september-update-en.png
  public/images/events/september-update-es.png
  public/images/events/september-update-fr.png
  public/images/events/september-update-it.png
  public/images/events/september-update-ja.png
  public/images/events/september-update-ko.png
  public/images/events/september-update-pt-BR.png
  public/images/events/september-update-zh-CN.png
  src/@types/TimedEvent.ts
  src/battle-scene.ts
  src/data/all-timed-events.ts
  src/data/mystery-encounters/encounters/global-trade-system-encounter.ts
  src/enums/event-modifier-type.ts
  src/enums/event-type.ts
  src/enums/images-folders.ts
  src/field/pokemon.ts
  src/loading-scene.ts
  src/phases/trainer-victory-phase.ts
  src/timed-event-manager.ts
  src/ui/timed-event-display.ts
  src/ui/title-ui-handler.ts
  test/events/candy-friendship-event.test.ts
  test/events/shiny-chance-event.test.ts
  test/events/timed-event-manager.test.ts
  test/testUtils/gameManager.ts
  test/testUtils/gameWrapper.ts
  test/testUtils/helpers/overridesHelper.ts
  test/testUtils/mocks/mockTextureManager.ts
  test/testUtils/mocks/mockTimedEventManager.ts
Labels: Refactor

#759 [Bug] Several fixes for moves that call other moves
  src/data/init-moves.ts
  src/data/move-attrs/copycat-attr.ts
  src/data/move-attrs/metronome-attr.ts
  src/data/move-attrs/mirror-move-attr.ts
  src/data/move-attrs/nature-power-attr.ts
  src/data/move-attrs/random-moveset-move-attr.ts
  src/utils/move-utils.ts
  test/abilities/sap_sipper.test.ts
  test/moves/copycat.test.ts
  test/moves/future_sight.test.ts
  test/moves/metronome.test.ts
  test/moves/mirror_move.test.ts
  test/moves/moongeist_beam.test.ts
  test/moves/nature_power.test.ts
  test/moves/sketch.test.ts
Labels: Move, P1 Bug, P2 Bug, Beta

#705 [Dev] Update documentation for the localization process
  .github/pull_request_template.md
  README.md
  docs/localization.md
Labels: Documentation
