Repository Despair-Games/poketernity, pull requests merged in 2025-04, with the labels that each got.

#892 [Test] Add more Corrosion tests
  test/abilities/corrosion.test.ts
Labels: Tests

#893 [Refactor] Add `Pokemon#hasTag()` function
  src/data/battler-tags/interrupted-tag.ts
  src/data/battler-tags/roosted-tag.ts
  src/data/init/init-abilities.ts
  src/data/init/init-moves.ts
  src/field/pokemon.ts
  src/phases/hit-check-phase.ts
  src/turn-command-manager.ts
  src/ui/handlers/target-select-ui-handler.ts
  test/abilities/sweet-veil.test.ts
Labels: Refactor

#891 [Bug] Perish Body now triggers even if the defender faints
  src/data/abilities/ab-attrs/post-defend-perish-song-ab-attr.ts
  src/data/init/init-abilities.ts
  test/abilities/perish-body.test.ts
Labels: Ability, P2 Bug

#901 [Balance] Wild Shedinja no longer spawn, Venonat/Spinarak appear in Forest night common pool
  src/data/biomes/forest.ts
  src/data/biomes/tall-grass.ts
Labels: Balance

#903 [Documentation] Documenting TrainerType + fix typos
  src/data/balance/trainer-configs/all-trainer-configs.ts
  src/data/balance/trainer-configs/evil-team-trainer-configs.ts
  src/data/balance/trainer-configs/generic-trainer-configs.ts
  src/enums/trainer-type.ts
Labels: Documentation

#898 [Refactor] Biome random weather + trainers added
  src/data/biome.ts
  src/data/biomes/abyss.ts
  src/data/biomes/badlands.ts
  src/data/biomes/beach.ts
  src/data/biomes/cave.ts
  src/data/biomes/construction-site.ts
  src/data/biomes/desert.ts
  src/data/biomes/dojo.ts
  src/data/biomes/end.ts
  src/data/biomes/factory.ts
  src/data/biomes/fairy-cave.ts
  src/data/biomes/forest.ts
  src/data/biomes/grass.ts
  src/data/biomes/graveyard.ts
  src/data/biomes/ice-cave.ts
  src/data/biomes/island.ts
  src/data/biomes/jungle.ts
  src/data/biomes/laboratory.ts
  src/data/biomes/lake.ts
  src/data/biomes/meadow.ts
  src/data/biomes/metropolis.ts
  src/data/biomes/mountain.ts
  src/data/biomes/plains.ts
  src/data/biomes/power-plant.ts
  src/data/biomes/ruins.ts
  src/data/biomes/sea.ts
  src/data/biomes/seabed.ts
  src/data/biomes/slum.ts
  src/data/biomes/snowy-forest.ts
  src/data/biomes/space.ts
  src/data/biomes/swamp.ts
  src/data/biomes/tall-grass.ts
  src/data/biomes/temple.ts
  src/data/biomes/town.ts
  src/data/biomes/volcano.ts
  src/data/biomes/wasteland.ts
  src/data/weather.ts
  src/field/arena.ts
  src/phases/encounter-phase.ts
  src/phases/new-biome-encounter-phase.ts
  src/utils.ts
Labels: Refactor

#908 [Move] Remove edgeCase from defiant/competitive
  src/data/init/init-abilities.ts
Labels: Move

#906 [Refactor] Add hardcoded uncatchableSpecies list
  src/battle-scene.ts
  src/data/balance/no-random-species-spawn.ts
  src/data/balance/uncatchable-species.ts
  src/data/pokemon-species-form.ts
Labels: P2 Bug, Balance, Refactor

#911 [Docs] Update comments in version migration examples
  src/system/version_migration/version_converter.ts
Labels: Documentation

#907 [Balance] Biomes can now generate terrain
  src/data/biome.ts
  src/data/biomes/abyss.ts
  src/data/biomes/badlands.ts
  src/data/biomes/beach.ts
  src/data/biomes/cave.ts
  src/data/biomes/construction-site.ts
  src/data/biomes/desert.ts
  src/data/biomes/dojo.ts
  src/data/biomes/end.ts
  src/data/biomes/factory.ts
  src/data/biomes/fairy-cave.ts
  src/data/biomes/forest.ts
  src/data/biomes/grass.ts
  src/data/biomes/graveyard.ts
  src/data/biomes/ice-cave.ts
  src/data/biomes/island.ts
  src/data/biomes/jungle.ts
  src/data/biomes/laboratory.ts
  src/data/biomes/lake.ts
  src/data/biomes/meadow.ts
  src/data/biomes/metropolis.ts
  src/data/biomes/mountain.ts
  src/data/biomes/plains.ts
  src/data/biomes/power-plant.ts
  src/data/biomes/ruins.ts
  src/data/biomes/sea.ts
  src/data/biomes/seabed.ts
  src/data/biomes/slum.ts
  src/data/biomes/snowy-forest.ts
  src/data/biomes/space.ts
  src/data/biomes/swamp.ts
  src/data/biomes/tall-grass.ts
  src/data/biomes/temple.ts
  src/data/biomes/town.ts
  src/data/biomes/volcano.ts
  src/data/biomes/wasteland.ts
  src/field/arena.ts
  src/phases/encounter-phase.ts
  src/phases/next-encounter-phase.ts
Labels: Balance

#915 [PR910] Review suggestions
  src/phase-manager.ts
Labels: Addendum

#900 [P1] `WeatherEffectPhase` no longer requires an active Pokemon
  src/phases/weather-effect-phase.ts
Labels: P1 Bug, Addendum

#917 [Refactor] Ensure stale object deletion doesn't fail early
  src/phases/battle-end-phase.ts
Labels: Refactor

#916 [Refactor] Add bgmLoopPoint and original music back to biomes
  src/data/biome.ts
  src/data/biomes/abyss.ts
  src/data/biomes/badlands.ts
  src/data/biomes/beach.ts
  src/data/biomes/cave.ts
  src/data/biomes/construction-site.ts
  src/data/biomes/desert.ts
  src/data/biomes/dojo.ts
  src/data/biomes/end.ts
  src/data/biomes/factory.ts
  src/data/biomes/fairy-cave.ts
  src/data/biomes/forest.ts
  src/data/biomes/grass.ts
  src/data/biomes/graveyard.ts
  src/data/biomes/ice-cave.ts
  src/data/biomes/island.ts
  src/data/biomes/jungle.ts
  src/data/biomes/laboratory.ts
  src/data/biomes/lake.ts
  src/data/biomes/meadow.ts
  src/data/biomes/metropolis.ts
  src/data/biomes/mountain.ts
  src/data/biomes/plains.ts
  src/data/biomes/power-plant.ts
  src/data/biomes/ruins.ts
  src/data/biomes/sea.ts
  src/data/biomes/seabed.ts
  src/data/biomes/slum.ts
  src/data/biomes/snowy-forest.ts
  src/data/biomes/space.ts
  src/data/biomes/swamp.ts
  src/data/biomes/tall-grass.ts
  src/data/biomes/temple.ts
  src/data/biomes/town.ts
  src/data/biomes/volcano.ts
  src/data/biomes/wasteland.ts
  src/field/arena.ts
Labels: Refactor

#913 [Doc] Add `BattleAnim` comments and minor cleanup
  src/data/animations/anim-config.ts
  src/data/animations/battle-anims.ts
  src/data/animations/common-battle-anim.ts
  src/data/animations/encounter-battle-anim.ts
  src/data/animations/move-anim.ts
  src/data/arena-tag.ts
  src/data/battler-tags/confused-tag.ts
  src/data/battler-tags/cursed-tag.ts
  src/data/battler-tags/damaging-trap-tag.ts
  src/data/battler-tags/infatuated-tag.ts
  src/data/battler-tags/nightmare-tag.ts
  src/data/battler-tags/powder-tag.ts
  src/data/battler-tags/salt-cured-tag.ts
  src/data/battler-tags/seed-tag.ts
  src/enums/anim-focus.ts
  src/enums/anim-frame-target.ts
  src/field/arena.ts
  src/phases/berry-phase.ts
  src/phases/common-anim-phase.ts
  src/phases/move-phase.ts
  src/phases/pokemon-heal-phase.ts
  src/phases/weather-effect-phase.ts
Labels: Documentation, Refactor

#918 [Documentation] Add documentation for how to add a new biome
  src/data/biomes/README.md
Labels: Documentation

#922 [Refactor] Remove a bunch of `!!`
  src/battle-scene.ts
  src/data/animations/battle-anims.ts
  src/data/arena-tag.ts
  src/data/berry.ts
  src/data/init/init-moves.ts
  src/data/moves/move-attrs/counter-damage-attr.ts
  src/data/moves/move-attrs/friendship-power-attr.ts
  src/data/moves/move-attrs/heal-attr.ts
  src/data/moves/move-attrs/hits-tag-attr.ts
  src/data/moves/move-conditions/upper-hand-condition.ts
  src/data/moves/move.ts
  src/data/mystery-encounters/encounters/bug-type-superfan-encounter.ts
  src/data/mystery-encounters/encounters/mysterious-challengers-encounter.ts
  src/data/mystery-encounters/encounters/weird-dream-encounter.ts
  src/data/mystery-encounters/utils/encounter-phase-utils.ts
  src/data/pokeball.ts
  src/data/pokemon-evolutions.ts
  src/data/pokemon-forms.ts
  src/data/pokemon-species.ts
  src/data/species-form-change-triggers/species-form-change-compound-trigger.ts
  src/data/species-form-change-triggers/species-form-change-move-learned-trigger.ts
  src/data/species-form-change-triggers/species-form-change-post-move-trigger.ts
  src/data/terrain.ts
  src/data/trainer-config.ts
  src/data/trainer-configs/generic-trainer-configs.ts
  src/data/weather.ts
  src/field/arena.ts
  src/field/mystery-encounter-intro.ts
  src/field/pokemon.ts
  src/field/trainer.ts
  src/modifier/init-modifier-pools.ts
  src/modifier/modifier.ts
  src/phases/command-phase.ts
  src/phases/encounter-phase.ts
  src/phases/evolution-phase.ts
  src/phases/faint-phase.ts
  src/phases/form-change-phase.ts
  src/system/pokemon-data.ts
  src/ui/components/battle-info.ts
  src/ui/components/iv-graph.ts
  src/ui/components/pokemon-info-container.ts
  src/ui/handlers/game-stats-ui-handler.ts
  src/ui/handlers/message-ui-handler.ts
  src/ui/handlers/modifier-select-ui-handler.ts
  src/ui/handlers/starter-select-ui-handler.ts
  test/system/dex-data.test.ts
  test/ui/starter-select.test.ts
Labels: Refactor

#924 [Balance] Update Galar gyms
  src/data/signatureSpecies.ts
Labels: Balance

#920 [Refactor] Create `AnimConfig` JSON schema w/ new JSON format
  package-lock.json
  package.json
  src/data/animations/anim-config-schema.ts
  src/data/animations/anim-config.ts
  src/data/animations/battle-anims.ts
  src/data/animations/ease-functions.ts
  src/enums/anim-frame-target.ts
  test/animations/validate-battle-anims.test.ts
Labels: Refactor, Art / Graphics

#919 [Balance] Gym leaders now occur every 20 waves from 20-160
  src/battle-scene.ts
  src/data/trainer-config.ts
  src/field/arena.ts
  src/game-mode.ts
  src/loggers.ts
  src/phases/victory-phase.ts
Labels: Balance

#959 [GitHub] Populate type field in issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: GitHub

#955 [P2] Shed tail hp cost rounds up
  src/data/init/init-moves.ts
  src/data/moves/move-attrs/add-substitute-attr.ts
  test/moves/shed-tail.test.ts
Labels: Move, P2

#967 [Test] Update `create-test-boilerplate.js` with enum name changes
  create-test-boilerplate.js
Labels: Tests

#971 [Test] Add test for effectiveness of Ghost moves vs Normal pkmn
  test/moves/effectiveness.test.ts
Labels: Tests

#972 [Misc] Remove unused overworld forms of [Mir|Kor]aidon
  src/data/init/init-species.ts
Labels: Miscellaneous

#926 [Balance] Add chargestone cave biome
  public/audio/bgm/chargestone_cave.mp3
  public/images/arenas/chargestone_cave_a.png
  public/images/arenas/chargestone_cave_b.png
  public/images/arenas/chargestone_cave_bg.png
  src/data/biome-links.ts
  src/data/biomes/chargestone-cave.ts
  src/data/init/init-biomes.ts
  src/data/moves/move-attrs/copy-biome-type-attr.ts
  src/data/moves/move-attrs/nature-power-attr.ts
  src/data/moves/move-attrs/secret-power-attr.ts
  src/data/mystery-encounters/encounters/dancing-lessons-encounter.ts
  src/data/mystery-encounters/encounters/teleporting-hijinks-encounter.ts
  src/data/mystery-encounters/mystery-encounters.ts
  src/data/pokemon-evolutions/gen8-pokemon-family-evolutions.ts
  src/enums/biome-id.ts
  src/field/arena.ts
Labels: Balance, Biomes

#961 [Refactor] Mark `Move.hasFlag()` as deprecated
  src/data/moves/move.ts
Labels: Refactor

#974 [P2] Fix Rattled activating at end of turn when intimidated
  src/data/abilities/ab-attrs/intimidate-immunity-ab-attr.ts
  src/data/abilities/ab-attrs/post-intimidate-stat-stage-change-ab-attr.ts
  src/data/abilities/ab-attrs/post-summon-stat-stage-change-ab-attr.ts
  src/data/init/init-abilities.ts
  src/enums/ab-attr-flag.ts
  test/abilities/rattled.test.ts
Labels: Ability, P2

#970 [Ability][Checkup] Defiant + Competitive checkup
  src/@types/PokemonStatStageChangeCondition.ts
  src/data/abilities/ab-attrs/defiant-competitive-ab-attr.ts
  src/data/abilities/ab-attrs/post-stat-stage-change-ab-attr.ts
  src/data/abilities/ab-attrs/post-stat-stage-change-stat-stage-change-ab-attr.ts
  src/data/arena-tag.ts
  src/data/battler-tags/octolock-tag.ts
  src/data/battler-tags/syrup-bomb-tag.ts
  src/data/init/init-abilities.ts
  src/phase-manager.ts
  src/phases/stat-stage-change-phase.ts
  test/abilities/competitive.test.ts
  test/abilities/defiant-competitive.test.ts
  test/abilities/defiant.test.ts
Labels: Ability, Checkup

#975 [Dep] Update multiple dependencies
  package-lock.json
  package.json
  test/battler-tags/stockpiling.test.ts
Labels: Dependencies

#977 [Refactor] Use `Move.checkFlag()` instead of `.hasFlag()`
  src/data/abilities/ab-attrs/move-flag-power-boost-ab-attr.ts
  src/data/animations/battle-anims.ts
  src/data/animations/move-anim.ts
  src/data/battler-tags/beak-blast-charging-tag.ts
  src/data/battler-tags/contact-burn-protected-tag.ts
  src/data/battler-tags/contact-damage-protected-tag.ts
  src/data/battler-tags/contact-poison-protected-tag.ts
  src/data/battler-tags/contact-stat-stage-change-protected-tag.ts
  src/data/battler-tags/heal-block-tag.ts
  src/data/battler-tags/throat-chopped-tag.ts
  src/data/init/init-abilities.ts
  src/data/moves/move-attrs/mirror-move-attr.ts
  src/data/moves/move-attrs/shell-side-arm-category-attr.ts
  src/data/moves/move.ts
  src/phases/hit-check-phase.ts
  src/phases/move-phase.ts
  test/abilities/fluffy.test.ts
  test/abilities/gooey.test.ts
  test/abilities/mega-launcher.test.ts
  test/abilities/move-flag-immunity.test.ts
  test/abilities/move-flag-power-boost.test.ts
  test/abilities/soundproof.test.ts
  test/abilities/triage.test.ts
  test/data/all-moves.test.ts
  test/moves/metronome.test.ts
Labels: Refactor

#968 [Refactor] Break part of `VictoryPhase` into `PostKnockoutPhase`
  src/data/mystery-encounters/utils/encounter-pokemon-utils.ts
  src/enums/phase-id.ts
  src/phases/attempt-capture-phase.ts
  src/phases/faint-phase.ts
  src/phases/post-knockout-phase.ts
  src/phases/victory-phase.ts
  test/mystery-encounter/encounter-test-utils.ts
  test/mystery-encounter/encounters/the-winstrate-challenge-encounter.test.ts
Labels: Refactor

#978 [Test] Fix `EvolutionPhase` tests and add `LEVEL_CAP_OVERRIDE`
  src/battle-scene.ts
  src/overrides.ts
  test/phases/evolution-phase.test.ts
  test/test-utils/helpers/overridesHelper.ts
Labels: Tests

#982 [Refactor] Replace `is*Tag` in battler-tags
  src/data/battler-tags/battler-tag.ts
  src/data/battler-tags/mystery-encounter-post-summon-tag.ts
  src/data/battler-tags/type-boost-tag.ts
  src/data/moves/move.ts
  src/phases/post-summon-phase.ts
  src/utils/battler-tag-type-utils.ts
Labels: Refactor

#960 [P2][Balance] Thief and Covet always proc (no more global RNG)
  src/data/init/init-moves.ts
  src/data/moves/move-attrs/steal-held-item-attr.ts
  test/abilities/sticky-hold.test.ts
  test/abilities/unburden.test.ts
  test/moves/substitute.test.ts
Labels: Move, P2, Balance

#984 [Dev] Update Node to 22
  .github/workflows/dependencies.yml
  .github/workflows/deploy-beta.yml
  .github/workflows/deploy.yml
  .github/workflows/eslint.yml
  .github/workflows/github-pages.yml
  .github/workflows/test-shard-template.yml
  .nvmrc
  README.md
  lefthook.yml
  package-lock.json
  package.json
Labels: Dependencies, Development

#976 [Refactor][Documentation] Update Biome README and do more refactoring
  src/data/biome-utils.ts
  src/data/biomes/README.md
  src/data/moves/move-attrs/copy-biome-type-attr.ts
  src/data/mystery-encounters/encounters/dancing-lessons-encounter.ts
  src/data/mystery-encounters/encounters/teleporting-hijinks-encounter.ts
  src/data/mystery-encounters/mystery-encounters.ts
  src/data/pokemon-evolutions.ts
  src/data/pokemon-evolutions/gen8-pokemon-family-evolutions.ts
  src/field/arena.ts
  test/mystery-encounter/encounters/a-trainers-test-encounter.test.ts
  test/mystery-encounter/encounters/an-offer-you-cant-refuse-encounter.test.ts
  test/mystery-encounter/encounters/department-store-sale-encounter.test.ts
  test/mystery-encounter/encounters/fun-and-games-encounter.test.ts
  test/mystery-encounter/encounters/global-trade-system-encounter.test.ts
  test/mystery-encounter/encounters/mysterious-challengers-encounter.test.ts
  test/mystery-encounter/encounters/part-timer-encounter.test.ts
  test/mystery-encounter/encounters/the-expert-breeder-encounter.test.ts
  test/mystery-encounter/encounters/the-pokemon-salesman-encounter.test.ts
  test/mystery-encounter/encounters/the-winstrate-challenge-encounter.test.ts
Labels: Documentation, Refactor

#999 [Addendum][payday] add pay day & gmax goldrush tests
  src/constants.ts
  src/game-mode.ts
  test/moves/pay-day-g-gmax-gold-rush.test.ts
  test/test-utils/gameManager.ts
Labels: Addendum

#993 [Feature] Wrap battle animation tween repeat in try/catch
  src/data/animations/battle-anims.ts
Labels: Enhancement

#996 [Balance] Payday no longer awards money if flee
  src/constants.ts
  src/game-mode.ts
  src/phases/battle-end-phase.ts
  test/moves/pay-day-g-gmax-gold-rush.test.ts
  test/test-utils/gameManager.ts
Labels: Move, Balance

#973 [Refactor] Rewrite `AnimConfig` JSON Schema
  src/data/animations/anim-config-schema.ts
Labels: Refactor, Art / Graphics

#897 [UI] Theme-dependant Input autofill color
  index.css
  src/battle-scene.ts
  src/inputs-controller.ts
  src/touch-controls.ts
  src/ui/ui-theme.ts
Labels: UI/UX

#991 [Bug] Fix wave skip from simultaneous KO in double battle
  src/battle-scene.ts
  src/data/mystery-encounters/utils/encounter-phase-utils.ts
  src/field/arena.ts
  src/overrides.ts
  src/phases/post-knockout-phase.ts
  test/battle/boss-pokemon.test.ts
  test/battle/double-battle.test.ts
  test/battle/reload.test.ts
  test/game-modes/daily-mode.test.ts
  test/mystery-encounter/encounters/a-trainers-test-encounter.test.ts
  test/mystery-encounter/encounters/absolute-avarice-encounter.test.ts
  test/mystery-encounter/encounters/an-offer-you-cant-refuse-encounter.test.ts
  test/mystery-encounter/encounters/berries-abound-encounter.test.ts
  test/mystery-encounter/encounters/bug-type-superfan-encounter.test.ts
  test/mystery-encounter/encounters/clowning-around-encounter.test.ts
  test/mystery-encounter/encounters/dancing-lessons-encounter.test.ts
  test/mystery-encounter/encounters/delibirdy-encounter.test.ts
  test/mystery-encounter/encounters/department-store-sale-encounter.test.ts
  test/mystery-encounter/encounters/field-trip-encounter.test.ts
  test/mystery-encounter/encounters/fiery-fallout-encounter.test.ts
  test/mystery-encounter/encounters/fight-or-flight-encounter.test.ts
  test/mystery-encounter/encounters/fun-and-games-encounter.test.ts
  test/mystery-encounter/encounters/global-trade-system-encounter.test.ts
  test/mystery-encounter/encounters/lost-at-sea-encounter.test.ts
  test/mystery-encounter/encounters/mysterious-challengers-encounter.test.ts
  test/mystery-encounter/encounters/part-timer-encounter.test.ts
  test/mystery-encounter/encounters/safari-zone.test.ts
  test/mystery-encounter/encounters/teleporting-hijinks-encounter.test.ts
  test/mystery-encounter/encounters/the-expert-breeder-encounter.test.ts
  test/mystery-encounter/encounters/the-pokemon-salesman-encounter.test.ts
  test/mystery-encounter/encounters/the-strong-stuff-encounter.test.ts
  test/mystery-encounter/encounters/the-winstrate-challenge-encounter.test.ts
  test/mystery-encounter/encounters/trash-to-treasure-encounter.test.ts
  test/mystery-encounter/encounters/uncommon-breed-encounter.test.ts
  test/mystery-encounter/encounters/weird-dream-encounter.test.ts
  test/test-utils/gameManager.ts
  test/test-utils/helpers/overridesHelper.ts
Labels: P2, Battle

#1001 [Refactor] add "matcher" suffix to matchers & filenames
  test/@types/vitest.d.ts
  test/matchers.setup.ts
  test/matchers/to-have-move-result-matcher.ts
  test/matchers/to-have-used-move-matcher.ts
Labels: Refactor

#1004 [Test] Add test to check for Fake Out flinching the target
  test/moves/fake-out.test.ts
Labels: Tests

#995 [Bug] Fix crash with trapping move animations
  src/data/animations/anim-config-schema.ts
  src/data/animations/anim-config.ts
  src/data/animations/battle-anims.ts
  src/data/animations/move-anim.ts
  src/enums/anim-frame-target.ts
Labels: P1, Art / Graphics

#1012 [Refactor] Remove unused `forHistory` param from `PokemonData`
  src/system/pokemon-data.ts
Labels: Refactor

#1009 [Bug] Fix HP bar rounding errors
  src/ui/components/battle-info.ts
Labels: P3, UI/UX

#1014 [Addendum #994] Fix STAB multiplier for combined Pledge moves + complete tests in `stab.test.ts`
  src/data/moves/move-attrs/combined-pledge-stab-boost-attr.ts
  src/field/pokemon.ts
  test/pokemon/stab.test.ts
Labels: Checkup, Addendum

#1016 [Refactor][Tests] Remove `kill` wording from `GameManager`
  test/abilities/battle-bond.test.ts
  test/abilities/disguise.test.ts
  test/abilities/ice-face.test.ts
  test/abilities/power-construct.test.ts
  test/abilities/schooling.test.ts
  test/abilities/shields-down.test.ts
  test/abilities/zen-mode.test.ts
  test/abilities/zero-to-hero.test.ts
  test/battle/battle.test.ts
  test/battle/double-battle.test.ts
  test/battle/reload.test.ts
  test/game-modes/daily-mode.test.ts
  test/items/dire-hit.test.ts
  test/items/double-battle-chance-booster.test.ts
  test/items/temp-stat-stage-booster.test.ts
  test/moves/fake-out.test.ts
  test/moves/geomancy.test.ts
  test/moves/gigaton-hammer.test.ts
  test/moves/jaw-lock.test.ts
  test/moves/multi-target.test.ts
  test/moves/parting-shot.test.ts
  test/moves/relic-song.test.ts
  test/moves/toxic-spikes.test.ts
  test/phases/evolution-phase.test.ts
  test/phases/form-change-phase.test.ts
  test/phases/learn-move-phase.test.ts
  test/pokemon/evolution.test.ts
  test/test-utils/gameManager.ts
  test/ui/battle-info.test.ts
Labels: Refactor, Tests

#1015 [Refactor] Document and refactor some exp code
  src/battle-scene.ts
  src/battle.ts
  src/data/exp.ts
  src/ui/handlers/starter-select-ui-handler.ts
Labels: Documentation, Refactor

#1020 [Test] Fix the Clowning Around double KO test
  test/mystery-encounter/encounters/clowning-around-encounter.test.ts
Labels: Tests

#994 [Check][Ability] Add Adaptability Ability Checkup
  docs/stab.md
  src/data/abilities/ab-attrs/stab-boost-ab-attr.ts
  src/data/moves/move-attrs/combined-pledge-stab-boost-attr.ts
  src/field/pokemon.ts
  src/plugins/api/api-base.ts
  src/utils/move-utils.ts
  test/abilities/adaptability.test.ts
  test/matchers/to-have-move-result-matcher.ts
  test/matchers/to-have-used-move-matcher.ts
  test/pokemon/pokemon.test.ts
  test/pokemon/stab.test.ts
Labels: Ability, Checkup

#1021 [Documentation] Correct documentation for exp in battle.ts
  src/battle.ts
Labels: Documentation

#1053 [UI][P3] Fix scrolling offset for hover callbacks in Option Select UI
  src/ui/handlers/abstract-option-select-ui-handler.ts
Labels: P3, UI/UX

#1002 [Check][Ability] Add Solar Power Ability Checkup
  src/constants/weather.ts
  src/data/abilities/ab-attrs/post-weather-lapse-damage-ab-attr.ts
  src/enums/weather-type.ts
  src/field/arena.ts
  src/overrides.ts
  src/plugins/api/api-base.ts
  test/@types/vitest.d.ts
  test/abilities/solar-power.test.ts
  test/matchers.setup.ts
  test/matchers/to-have-effective-stat-matcher.ts
  test/matchers/to-have-full-hp.ts
  test/matchers/to-have-move-result-matcher.ts
  test/matchers/to-have-stat-matcher.ts
  test/matchers/to-have-taken-damage-matcher.ts
  test/matchers/to-have-used-move-matcher.ts
  test/matchers/to-have-weather.ts
  test/test-utils/helpers/overridesHelper.ts
  test/test-utils/testUtils.ts
Labels: Ability, Checkup

#1013 [Refactor] Remove `any` from `PokemonData` constructor
  src/system/game-data.ts
  src/system/pokemon-data.ts
  src/utils.ts
Labels: Refactor, Save Data

#1054 [Bug][UI/UX] Fix visual misalignment in enemy hp bar and type icons
  src/game.ts
Labels: UI/UX

#1064 [Refactor] Minor refactoring in exp
  src/battle-scene.ts
  src/constants/game.ts
  src/field/trainer.ts
Labels: Refactor

#1065 [Dev] Add `ban-ts-comment` TypeScript-ESLint rule
  eslint.config.js
  src/battle-scene.ts
  src/data/data-lists.ts
  src/data/mystery-encounters/encounters/clowning-around-encounter.ts
  src/data/mystery-encounters/encounters/mysterious-challengers-encounter.ts
  src/touch-controls.ts
  test/sprites/pokemon-sprite.test.ts
  test/test-utils/gameWrapper.ts
  test/test-utils/inputsHandler.ts
  test/test-utils/mocks/mocksContainer/mockSprite.ts
Labels: Development

#1070 [Dev] Update to latest upstream Prettier
  .prettierrc
  .vscode/extensions.json
  index.css
  package-lock.json
  package.json
  test/abilities/adaptability.test.ts
  tsconfig.json
Labels: Dependencies, Development

#1066 [Refactor] Phaser stuff cleanup
  src/@types/ConditionFn.ts
  src/@types/phaser.d.ts
  src/data/mystery-encounters/utils/encounter-pokemon-utils.ts
  src/data/mystery-encounters/utils/encounter-transformation-sequence.ts
  src/main.ts
  src/phaser-extensions.ts
  src/phases/attempt-capture-phase.ts
  src/phases/evolution-phase.ts
  src/phases/form-change-phase.ts
  src/system/achievements.ts
  src/system/voucher.ts
  src/typings/phaser/index.d.ts
  src/ui/components/iv-graph.ts
  src/ui/handlers/admin-ui-handler.ts
  src/ui/handlers/modifier-select-ui-handler.ts
  src/ui/handlers/target-select-ui-handler.ts
  src/ui/handlers/test-dialogue-ui-handler.ts
  test/test-utils/testFileInitialization.ts
Labels: Refactor

#1067 [Addendum][Tests] Add Matchers `this` type and return type
  test/matchers.setup.ts
  test/matchers/to-have-effective-stat-matcher.ts
  test/matchers/to-have-full-hp-matcher.ts
  test/matchers/to-have-move-result-matcher.ts
  test/matchers/to-have-stat-matcher.ts
  test/matchers/to-have-taken-damage-matcher.ts
  test/matchers/to-have-used-move-matcher.ts
  test/matchers/to-have-weather-matcher.ts
Labels: Tests, Addendum

#1063 [Test] Fix test matchers' behaviour when receiving wrong object type
  test/matchers.setup.ts
  test/matchers/to-have-effective-stat-matcher.ts
  test/matchers/to-have-full-hp-matcher.ts
  test/matchers/to-have-move-result-matcher.ts
  test/matchers/to-have-stat-matcher.ts
  test/matchers/to-have-taken-damage-matcher.ts
  test/matchers/to-have-used-move-matcher.ts
  test/matchers/to-have-weather-matcher.ts
  test/test-utils/testUtils.ts
Labels: Tests

#1077 [Dev] Add enemy pokemon level to encounter logging
  src/data/mystery-encounters/utils/encounter-phase-utils.ts
  src/phases/encounter-phase.ts
Labels: Development

#1086 [Refactor][Tests] Move matchers into test-utils
  test/@types/vitest.d.ts
  test/matchers.setup.ts
  test/test-utils/matchers/to-have-effective-stat-matcher.ts
  test/test-utils/matchers/to-have-full-hp-matcher.ts
  test/test-utils/matchers/to-have-move-result-matcher.ts
  test/test-utils/matchers/to-have-stat-matcher.ts
  test/test-utils/matchers/to-have-status-effect-matcher.ts
  test/test-utils/matchers/to-have-taken-damage-matcher.ts
  test/test-utils/matchers/to-have-used-move-matcher.ts
  test/test-utils/matchers/to-have-weather-matcher.ts
Labels: Refactor, Tests

#1088 Add `Battle#isTrainerBattle`, reformat functions, update comments
  src/battle.ts
  src/data/exp.ts
Labels: Addendum

#1076 [Ability] Implement Teraform Zero
  src/constants/game.ts
  src/data/abilities/ab-attrs/post-tera-form-change-clear-weather-terrain-ab-attr.ts
  src/data/init/init-abilities.ts
  src/enums/ab-attr-flag.ts
  src/field/arena.ts
  src/overrides.ts
  src/phases/quiet-form-change-phase.ts
  test/@types/vitest.d.ts
  test/abilities/teraform-zero.test.ts
  test/matchers.setup.ts
  test/test-utils/helpers/fieldHelper.ts
  test/test-utils/helpers/moveHelper.ts
  test/test-utils/helpers/overridesHelper.ts
  test/test-utils/matchers/to-have-terrain-matcher.ts
  test/test-utils/matchers/to-have-weather-matcher.ts
Labels: Enhancement, Ability

#1091 [Beta] Fix typo for levels between 191-200
  src/data/exp.ts
Labels: P2, Beta

#1096 [P2] Transistor is 1.3x instead of 1.5x
  src/data/init/init-abilities.ts
Labels: Ability, P2
